//! **v50.0.0 (CIRISPersist#924, CIRISConstitution#112) — the ONE dimension
//! matcher.**
//!
//! CC 3.1.7 R3 (rc5) carries the dimension grammar as manifest DATA
//! (`_meta.case_rule` + `families[].segments[]`, `leaves`/`leaves_closed`,
//! `reserved_stems`, `external_standards`, `version_segment`) and implements it
//! once, in the Constitution's `tools/cc_namespace_match.py`. This module is a
//! port of that reference matcher, and it is the only place persist resolves a
//! wire `dimension` to a registry family.
//!
//! Before this cut persist ran four matchers that disagreed with CC and with
//! each other: `load_bearing::prefix_match_score` (arity-exact scoring over the
//! supersets families), `registry::lookup` (longest literal prefix),
//! `registry::is_family_registered` (first-colon stem membership) and
//! `consent_grammar::covers` (raw `starts_with`, no grammar at all). Each now
//! calls [`match_family`]; the first three are deleted.
//!
//! # Drift control
//!
//! CC publishes `manifests/namespace_match_vectors.json` — 1040 dimensions (rc6) with
//! the family each resolves to and the refusal each earns — and requires every
//! consumer to replay them against its own matcher, "so a matcher that drifts
//! from this one fails a build, not a card". The file is vendored byte-for-byte
//! beside the registry ([`VECTORS_JSON`]); `tests::namespace_match_vectors_replay`
//! replays all of them and additionally compares every `binds` map to the
//! reference's own output (`namespace_match_binds.json`, generated by running
//! the reference matcher over the vendored vectors — the vectors file carries
//! no binds).
//!
//! # Read from the manifest, never re-spelled
//!
//! Every pattern, token, stem and exemption below is read from the vendored
//! manifest. Nothing here restates a CC value; the only literals are the three
//! the reference itself hard-codes (`HEX_PATTERN` and the `VERSION_LIKE` /
//! `VERSION_ATTEMPT` detectors, which are deliberately looser than the
//! manifest's version pattern so an uppercase `V1` or a `v1beta` is *detected*
//! as a malformed version tail).
//!
//! # Full match (`_meta.case_rule.match_semantics`, CIRISConstitution#116)
//!
//! Every manifest pattern must match the WHOLE segment, and a `$` anchor does
//! not admit a trailing newline. `compile` makes that structural: it wraps
//! each pattern as `^(?:p)$`, so a row whose pattern forgot its anchors still
//! cannot partial-match (`tests::compile_is_a_full_match`).

use std::collections::BTreeMap;
use std::sync::OnceLock;

use regex::Regex;

/// The CC-published match vectors, vendored byte-for-byte from the same
/// CIRISConstitution commit as the registry
/// ([`VENDORED_CC_COMMIT`](super::registry::VENDORED_CC_COMMIT)).
pub const VECTORS_JSON: &str = include_str!("namespace_match_vectors.json");

/// The reference's default for a `hex` segment with no `pattern` of its own.
const HEX_PATTERN: &str = "^[0-9a-f]+$";

/// The reference's version-tail DETECTOR — case-insensitive on the `v` so a
/// `V1` tail is recognised in order to be refused, never admitted.
///
/// Full-match, like every manifest pattern: since CIRISConstitution#128 the
/// reference applies its two detectors with `re.fullmatch`, so a segment
/// carrying a trailing newline is neither a version nor a version attempt
/// (`no_such_family:v1\n:v2` is open vocabulary, not a malformed tail). `\z`
/// is that reading; before #128 the reference used `re.match`, whose `$`
/// admitted one trailing newline, and this port reproduced it with `\n?\z`.
const VERSION_LIKE: &str = "^[vV][0-9]+(?:\\.[0-9]+)*\\z";

/// The reference's `VERSION_ATTEMPT` (rc5 at c60d0a6): a segment that starts
/// like a version (`v` + digit) but is not one — `v1beta`, `v1.`, `V1x`. In
/// LAST place it is an attempt at the version tail, so it is malformed. A bare
/// `vx` is a leaf name (a version begins `v` + digit, R3).
const VERSION_ATTEMPT: &str = "^[vV][0-9][0-9A-Za-z_.\\-]*\\z";

/// A refusal the grammar names. Each spells the manifest's own token
/// (`_meta.case_rule.refusal_tokens`) — never a bespoke string; the mapping is
/// pinned by `tests::refusal_tokens_are_the_manifests`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Refusal {
    /// A segment breaks its class (R3), a version tail is uppercase or
    /// duplicated, or a registered stem is case-mutated.
    CaseMalformed,
    /// A leaf under a reserved stem, or an unmatched descendant of a closed
    /// family (a reserved wildcard, or a parameterized parent closed in its
    /// leaves such as `consent:{kind}`), that no row claims (R2(b), CC 3.4).
    FamilyUnregistered,
    /// A registered, non-exempt family carried no trailing version segment.
    MissingVersionSegment,
    /// The Private Use range (`x_private:`) never federates (R2).
    PrivateUseNotFederatable,
    /// A value outside a CLOSED `segments[].values` enumeration.
    VocabValueUnregistered,
}

impl Refusal {
    /// Every variant, for the token-pin test.
    pub const ALL: [Refusal; 5] = [
        Refusal::CaseMalformed,
        Refusal::FamilyUnregistered,
        Refusal::MissingVersionSegment,
        Refusal::PrivateUseNotFederatable,
        Refusal::VocabValueUnregistered,
    ];

    /// The `_meta.case_rule.refusal_tokens` KEY this variant stands for.
    #[must_use]
    pub const fn manifest_key(self) -> &'static str {
        match self {
            Refusal::CaseMalformed => "case_malformed",
            Refusal::FamilyUnregistered => "family_unregistered",
            Refusal::MissingVersionSegment => "missing_version_segment",
            Refusal::PrivateUseNotFederatable => "private_use_not_federatable",
            Refusal::VocabValueUnregistered => "vocab_value_unregistered",
        }
    }

    /// The wire token, read from the manifest.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        rules()
            .tokens
            .get(self.manifest_key())
            .map(String::as_str)
            .unwrap_or_else(|| self.manifest_key())
    }

    fn from_token(token: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|r| r.as_str() == token)
    }
}

impl std::fmt::Display for Refusal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// The answer [`match_family`] gives for one wire dimension: the reference
/// matcher's `(family_prefix | None, binds, refusal | None)`.
///
/// `family: None` with `refusal: None` is **open vocabulary** — no row claims
/// the dimension and the grammar has nothing to say about it (it still carries
/// its one trailing version segment: R3 is global). A refusal with a family
/// names the family the dimension was judged against — on
/// [`Refusal::CaseMalformed`], the registered row it mutates where one
/// resolves cleanly, else the refused hit (exact, per the released rc5
/// vectors' contract).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FamilyMatch {
    /// The registry family prefix, verbatim (`"config:{scope}"`, `"accord:*"`).
    pub family: Option<&'static str>,
    /// Placeholder name → the value it bound (`"scope" → "admission"`), plus
    /// `"*"` for a variadic tail and `"version"` for the stripped version.
    pub binds: BTreeMap<String, String>,
    /// The refusal the dimension earns, if any.
    pub refusal: Option<Refusal>,
}

impl FamilyMatch {
    fn bare(refusal: Option<Refusal>) -> Self {
        Self {
            family: None,
            binds: BTreeMap::new(),
            refusal,
        }
    }
}

// ── the grammar, read from the manifest ─────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Class {
    Literal,
    Vocab,
    External,
    Value,
    Hex,
    Wildcard,
}

#[derive(Debug)]
struct Seg {
    /// The segment as written in the prefix (`"config"`, `"{scope}"`, `"*"`).
    segment: String,
    /// `segment` without its braces — the bind name.
    name: String,
    class: Class,
    pattern: Option<Regex>,
    values: Option<Vec<String>>,
    open: bool,
    multi: bool,
}

#[derive(Debug)]
struct Fam {
    prefix: &'static str,
    segments: Vec<Seg>,
    leaves: Vec<String>,
    leaves_closed: bool,
}

impl Fam {
    fn score(&self) -> (usize, u8, usize) {
        let literals = self
            .segments
            .iter()
            .filter(|s| s.class == Class::Literal)
            .count();
        let wildcard = self.last_class() == Some(Class::Wildcard);
        (literals, u8::from(!wildcard), self.segments.len())
    }

    fn last_class(&self) -> Option<Class> {
        self.segments.last().map(|s| s.class)
    }

    fn ends_version(&self) -> bool {
        self.segments
            .last()
            .is_some_and(|s| s.segment == "{version}")
    }
}

struct Rules {
    vocab: Regex,
    private: String,
    version: Regex,
    version_required: bool,
    exempt: Vec<String>,
    tokens: BTreeMap<String, String>,
    external: BTreeMap<String, Regex>,
    reserved_stems: Vec<String>,
    /// Stems of CLOSED families: a `leaves_closed` wildcard's prefix minus the
    /// `*`, or a closed parameterized parent's first segment plus `:`. Any
    /// unmatched descendant beneath one is unregistered, like a reserved stem.
    closed_stems: Vec<String>,
    /// `(stem, rule, cc_ref)` per `_meta.case_rule.reserved_stems` entry of
    /// `kind: reserved`.
    reserved_stem_rules: Vec<(String, String, String)>,
    families: Vec<Fam>,
    hex: Regex,
    version_like: Regex,
    version_attempt: Regex,
}

/// Compile a manifest pattern with **full-match** semantics
/// (`_meta.case_rule.match_semantics`): the whole segment must match, and a
/// `$` never admits a trailing newline (Rust's `$` is end-of-text). The
/// wrapper makes that hold even for a pattern that forgot its own anchors.
fn compile(p: &str) -> Regex {
    Regex::new(&format!("^(?:{p})$"))
        .unwrap_or_else(|e| panic!("vendored manifest pattern {p:?} does not compile: {e}"))
}

/// Compile one of the reference's two hard-coded DETECTORS verbatim (they
/// carry their own anchors; `\z` is full-match, CIRISConstitution#128).
fn compile_detector(p: &str) -> Regex {
    Regex::new(p).unwrap_or_else(|e| panic!("detector {p:?} does not compile: {e}"))
}

fn rules() -> &'static Rules {
    static RULES: OnceLock<Rules> = OnceLock::new();
    RULES.get_or_init(|| {
        let root: serde_json::Value = serde_json::from_str(super::registry::REGISTRY_JSON)
            .expect("vendored namespace_registry.json is valid");
        parse_rules(root)
    })
}

fn str_of<'a>(v: &'a serde_json::Value, what: &str) -> &'a str {
    v.as_str()
        .unwrap_or_else(|| panic!("manifest field {what} is not a string"))
}

fn parse_rules(root: serde_json::Value) -> Rules {
    let meta = &root["_meta"];
    let cr = &meta["case_rule"];
    let vs = &cr["version_segment"];
    let tokens = cr["refusal_tokens"]
        .as_object()
        .expect("_meta.case_rule.refusal_tokens")
        .iter()
        .map(|(k, v)| (k.clone(), str_of(v, "refusal token").to_owned()))
        .collect();
    let external = cr
        .get("external_standards")
        .and_then(|v| v.as_object())
        .map(|o| {
            o.iter()
                .filter_map(|(name, spec)| {
                    spec.get("pattern")
                        .and_then(|p| p.as_str())
                        .map(|p| (name.clone(), compile(p)))
                })
                .collect()
        })
        .unwrap_or_default();
    let reserved_stems = cr
        .get("reserved_stems")
        .and_then(|v| v.as_array())
        .map(|a| {
            a.iter()
                .map(|s| str_of(&s["stem"], "reserved stem").to_owned())
                .collect()
        })
        .unwrap_or_default();
    let reserved_stem_rules = cr
        .get("reserved_stems")
        .and_then(|v| v.as_array())
        .map(|a| {
            a.iter()
                // `kind: gated` (`age_self_declared:`) carries an emitter rule
                // WITHOUT a reservation (CC 3.1.7 R3) — not a reserved rule.
                .filter(|s| s.get("kind").and_then(|k| k.as_str()) == Some("reserved"))
                .map(|s| {
                    (
                        str_of(&s["stem"], "reserved stem").to_owned(),
                        str_of(&s["rule"], "reserved stem rule").to_owned(),
                        str_of(&s["cc_ref"], "reserved stem cc_ref").to_owned(),
                    )
                })
                .collect()
        })
        .unwrap_or_default();
    let exempt = vs
        .get("exempt")
        .and_then(|v| v.as_array())
        .map(|a| a.iter().map(|e| str_of(e, "exempt").to_owned()).collect())
        .unwrap_or_default();
    let families: Vec<Fam> = root["families"]
        .as_array()
        .expect("families[]")
        .iter()
        .map(|f| {
            // Leaked once per process: the family prefixes are the `&'static
            // str` every caller keys on, and the registry is immutable.
            let prefix: &'static str =
                Box::leak(str_of(&f["prefix"], "prefix").to_owned().into_boxed_str());
            let segments = f["segments"]
                .as_array()
                .unwrap_or_else(|| panic!("{prefix}: segments[]"))
                .iter()
                .map(|s| {
                    let segment = str_of(&s["segment"], "segment").to_owned();
                    let class = match str_of(&s["class"], "class") {
                        "literal" => Class::Literal,
                        "vocab" => Class::Vocab,
                        "external" => Class::External,
                        "value" => Class::Value,
                        "hex" => Class::Hex,
                        "wildcard" => Class::Wildcard,
                        other => panic!("{prefix}: unknown segment class {other:?}"),
                    };
                    Seg {
                        name: segment.trim_matches(['{', '}']).to_owned(),
                        segment,
                        class,
                        pattern: s.get("pattern").and_then(|p| p.as_str()).map(compile),
                        values: s
                            .get("values")
                            .and_then(|v| v.as_array())
                            .map(|a| a.iter().map(|x| str_of(x, "value").to_owned()).collect()),
                        open: s.get("open").and_then(|o| o.as_bool()).unwrap_or(false),
                        multi: s.get("multi").and_then(|o| o.as_bool()).unwrap_or(false),
                    }
                })
                .collect();
            Fam {
                prefix,
                segments,
                leaves: f
                    .get("leaves")
                    .and_then(|v| v.as_array())
                    .map(|a| a.iter().map(|x| str_of(x, "leaf").to_owned()).collect())
                    .unwrap_or_default(),
                leaves_closed: f
                    .get("leaves_closed")
                    .and_then(|v| v.as_bool())
                    .unwrap_or(false),
            }
        })
        .collect();
    // The reference's `closed_stems`: sorted, de-duplicated.
    let closed_stems: Vec<String> = families
        .iter()
        .filter(|f| f.leaves_closed)
        .map(|f| {
            if f.last_class() == Some(Class::Wildcard) {
                f.prefix[..f.prefix.len() - 1].to_owned()
            } else {
                format!("{}:", f.prefix.split(':').next().unwrap_or_default())
            }
        })
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();
    Rules {
        vocab: compile(str_of(&cr["vocab_pattern"], "vocab_pattern")),
        private: str_of(&meta["private_use_prefix"], "private_use_prefix").to_owned(),
        version: compile(str_of(&vs["pattern"], "version_segment.pattern")),
        version_required: vs.get("required").and_then(|r| r.as_bool()).unwrap_or(true),
        exempt,
        tokens,
        external,
        reserved_stems,
        reserved_stem_rules,
        closed_stems,
        families,
        hex: compile(HEX_PATTERN),
        version_like: compile_detector(VERSION_LIKE),
        version_attempt: compile_detector(VERSION_ATTEMPT),
    }
}

impl Rules {
    fn family(&self, prefix: &str) -> Option<&Fam> {
        self.families.iter().find(|f| f.prefix == prefix)
    }
}

// ── the matcher (a port of cc_namespace_match.py) ───────────────────────

/// The refusal a single placeholder value earns under its class, or `None`.
fn check_seg(seg: &Seg, got: &str, r: &Rules) -> Option<Refusal> {
    if got.is_empty() {
        return Some(Refusal::CaseMalformed);
    }
    if seg.segment == "{version}" {
        return (!r.version.is_match(got)).then_some(Refusal::CaseMalformed);
    }
    match seg.class {
        Class::Vocab => {
            if !r.vocab.is_match(got) {
                return Some(Refusal::CaseMalformed);
            }
            match &seg.values {
                Some(values)
                    if !values.is_empty() && !seg.open && !values.iter().any(|v| v == got) =>
                {
                    Some(Refusal::VocabValueUnregistered)
                }
                _ => None,
            }
        }
        Class::Hex => {
            let pat = seg.pattern.as_ref().unwrap_or(&r.hex);
            (!pat.is_match(got)).then_some(Refusal::CaseMalformed)
        }
        Class::External => {
            let pat = seg.pattern.as_ref().or_else(|| r.external.get(&seg.name));
            pat.is_some_and(|p| !p.is_match(got))
                .then_some(Refusal::CaseMalformed)
        }
        // value: verbatim, case-preserved — unless the row pins a shape.
        Class::Value | Class::Literal | Class::Wildcard => seg
            .pattern
            .as_ref()
            .is_some_and(|p| !p.is_match(got))
            .then_some(Refusal::CaseMalformed),
    }
}

/// `Some((binds, refusal))` iff `parts` fits `segs`; `None` when this is not
/// the family at all. A `multi` placeholder spans one or more segments; a
/// trailing `*` is variadic (one or more further segments).
fn match_segments(
    segs: &[Seg],
    parts: &[&str],
    r: &Rules,
) -> Option<(BTreeMap<String, String>, Option<Refusal>)> {
    let wildcard = segs.last().is_some_and(|s| s.class == Class::Wildcard);
    let fixed = if wildcard {
        &segs[..segs.len() - 1]
    } else {
        segs
    };
    let multi = fixed.iter().position(|s| s.multi);
    let extra = if wildcard {
        if parts.len() < fixed.len() + 1 {
            return None;
        }
        0
    } else if multi.is_some() {
        parts.len().checked_sub(fixed.len())?
    } else if parts.len() != fixed.len() {
        return None;
    } else {
        0
    };
    let mut binds = BTreeMap::new();
    let mut refusal: Option<Refusal> = None;
    let mut pi = 0usize;
    for (i, seg) in fixed.iter().enumerate() {
        if multi == Some(i) {
            let span = &parts[pi..pi + 1 + extra];
            pi += 1 + extra;
            for got in span {
                // Every component of a multi-segment value is verbatim —
                // `registry:v1` is a source id — so no version-shape test
                // applies inside the span (rc5 reference, #113 review).
                refusal = refusal.or_else(|| check_seg(seg, got, r));
            }
            binds.insert(seg.name.clone(), span.join(":"));
            continue;
        }
        let got = parts[pi];
        pi += 1;
        if seg.class == Class::Literal {
            if seg.segment != got {
                return None; // not this family at all
            }
            continue;
        }
        refusal = refusal.or_else(|| check_seg(seg, got, r));
        binds.insert(seg.name.clone(), got.to_owned());
    }
    let tail = &parts[pi..];
    for (k, got) in tail.iter().enumerate() {
        // Segments below a variadic tail. A version-like token here is an
        // uppercase or duplicated version tail — the real version was stripped
        // before matching — so it is malformed, never a leaf; so is a version
        // attempt (`v1beta`) in last place.
        let last = pi + k == parts.len() - 1;
        if got.is_empty()
            || !r.vocab.is_match(got)
            || r.version_like.is_match(got)
            || (last && r.version_attempt.is_match(got))
        {
            refusal = refusal.or(Some(Refusal::CaseMalformed));
        }
    }
    if !tail.is_empty() {
        binds.insert("*".to_owned(), tail.join(":"));
    }
    Some((binds, refusal))
}

type Candidate<'r> = ((usize, u8, usize), Resolved<'r>);

/// Keep `found` if it outscores the best so far. On a tie the FIRST candidate
/// in manifest order stays, as the reference's stable `sort(reverse=True)`
/// keeps it.
fn offer<'r>(
    best: &mut Option<Candidate<'r>>,
    fam: &'r Fam,
    found: Option<(BTreeMap<String, String>, Option<Refusal>)>,
    has_version: bool,
) {
    if let Some((binds, refusal)) = found {
        let score = fam.score();
        if best.as_ref().is_none_or(|(s, _)| score > *s) {
            *best = Some((
                score,
                Resolved {
                    fam,
                    binds,
                    refusal,
                    has_version,
                },
            ));
        }
    }
}

struct Resolved<'r> {
    fam: &'r Fam,
    binds: BTreeMap<String, String>,
    refusal: Option<Refusal>,
    has_version: bool,
}

/// A last segment shaped like a version tail but not one: uppercase
/// (`V1`) or an attempt (`v1beta`) — the reference's `_mutated_tail`.
fn mutated_tail(r: &Rules, seg: &str) -> bool {
    (r.version_like.is_match(seg) && !r.version.is_match(seg)) || r.version_attempt.is_match(seg)
}

/// The best candidate family for `parts`, or `None`.
fn resolve<'r>(r: &'r Rules, parts: &[&str]) -> Option<Resolved<'r>> {
    let versioned = parts.last().is_some_and(|p| r.version.is_match(p));
    let mut best: Option<Candidate<'r>> = None;
    for fam in &r.families {
        let ends_version = fam.ends_version();
        if ends_version && !versioned {
            // Recognise the family by its other segments (missing tail), and
            // also as written (a malformed tail such as `V1` is then refused,
            // not open vocabulary).
            let headless = &fam.segments[..fam.segments.len() - 1];
            offer(&mut best, fam, match_segments(headless, parts, r), false);
            offer(
                &mut best,
                fam,
                match_segments(&fam.segments, parts, r),
                true,
            );
        } else if ends_version || !versioned {
            let found = match_segments(&fam.segments, parts, r).map(|(binds, refusal)| {
                // An unversioned input whose last segment is a MUTATED version
                // tail (`V1`, `v1beta`) is malformed whatever class absorbed it.
                let mutated = !versioned && parts.last().is_some_and(|p| mutated_tail(r, p));
                (binds, refusal.or(mutated.then_some(Refusal::CaseMalformed)))
            });
            offer(&mut best, fam, found, ends_version);
        } else if parts.len() > 1 {
            // The trailing version segment is the version — never a value or
            // a wildcard tail.
            offer(
                &mut best,
                fam,
                match_segments(&fam.segments, &parts[..parts.len() - 1], r),
                true,
            );
        }
    }
    if best.is_none() && versioned {
        // The last segment is version-SHAPED but nothing matched with it
        // stripped: it may be a VALUE that happens to look like a version
        // (`config:v1` = `config:{scope}` with the tail omitted). Read it as
        // an unversioned instance so the family is recognised and refused for
        // the missing tail, never called open vocabulary.
        for fam in &r.families {
            if fam.ends_version() {
                continue;
            }
            offer(
                &mut best,
                fam,
                match_segments(&fam.segments, parts, r),
                false,
            );
        }
    }
    best.map(|(_, res)| res)
}

/// A dimension no row claims may still be a MALFORMED form of a registered
/// family — a case-mutated stem, an uppercase, attempted or duplicated version
/// tail. Fold and strip only to DETECT, never to admit. With `clean_only` the
/// variant must resolve WITHOUT a refusal.
fn detect_malformed(r: &Rules, parts: &[&str], clean_only: bool) -> Option<&'static str> {
    let low: Vec<String> = parts.iter().map(|p| p.to_lowercase()).collect();
    let low: Vec<&str> = low.iter().map(String::as_str).collect();
    let mut variants: Vec<&[&str]> = Vec::new();
    if low != parts {
        variants.push(&low);
    }
    let n = parts.len();
    if n > 1 && (r.version_like.is_match(parts[n - 1]) || r.version_attempt.is_match(parts[n - 1]))
    {
        variants.push(&parts[..n - 1]);
        variants.push(&low[..n - 1]);
        if n > 2 && r.version_like.is_match(parts[n - 2]) {
            variants.push(&parts[..n - 2]);
            variants.push(&low[..n - 2]);
        }
    }
    variants.into_iter().find_map(|v| {
        resolve(r, v)
            .filter(|hit| hit.refusal.is_none() || !clean_only)
            .map(|hit| hit.fam.prefix)
    })
}

/// Python's `str.strip()` whitespace: Unicode `White_Space` plus the four
/// ASCII separators (`\x1c`–`\x1f`) that `str.isspace()` also counts.
fn is_py_space(c: char) -> bool {
    c.is_whitespace() || ('\u{1c}'..='\u{1f}').contains(&c)
}

/// **Resolve a wire dimension** — CC 3.1.7 R3, the reference matcher's
/// `match_family(dimension) -> (family | None, binds, refusal | None)`.
///
/// - segments split on `:` and compare byte-exactly; nothing case-folds;
/// - one trailing version segment (`_meta.case_rule.version_segment.pattern`)
///   is stripped before matching unless the family's last segment is
///   `{version}`, in which case it IS that segment; a registered, non-exempt
///   family without one refuses [`Refusal::MissingVersionSegment`];
/// - a closed enumeration (`segments[].values`, `open: false`) refuses a
///   value outside it with [`Refusal::VocabValueUnregistered`];
/// - a leaf under a `leaves_closed` wildcard family, or under a reserved stem
///   no row claims, refuses [`Refusal::FamilyUnregistered`];
/// - a malformed form of a registered family (case-mutated stem, uppercase or
///   duplicated version tail) refuses [`Refusal::CaseMalformed`] rather than
///   falling into open vocabulary;
/// - the most specific family wins: most literal segments, then a
///   non-wildcard over a wildcard, then the longer prefix.
#[must_use]
pub fn match_family(dimension: &str) -> FamilyMatch {
    let r = rules();
    if dimension.is_empty() || dimension.trim_matches(is_py_space) != dimension {
        return FamilyMatch::bare(Some(Refusal::CaseMalformed));
    }
    if dimension.starts_with(r.private.as_str()) {
        return FamilyMatch::bare(Some(Refusal::PrivateUseNotFederatable));
    }
    let parts: Vec<&str> = dimension.split(':').collect();
    if parts.iter().any(|p| p.is_empty()) {
        return FamilyMatch::bare(Some(Refusal::CaseMalformed));
    }
    let malformed_as = |family: &'static str| FamilyMatch {
        family: Some(family),
        binds: BTreeMap::new(),
        refusal: Some(Refusal::CaseMalformed),
    };
    let Some(hit) = resolve(r, &parts) else {
        if let Some(mutated) = detect_malformed(r, &parts, false) {
            return malformed_as(mutated);
        }
        // A stem CC 3.4 reserves as a whole, or the stem of a CLOSED family:
        // an unclaimed leaf or an unmatched descendant beneath it
        // (`consent:totally:new:v1`) is unregistered, never open vocabulary.
        let fenced = || r.reserved_stems.iter().chain(&r.closed_stems);
        if fenced().any(|stem| dimension.starts_with(stem.as_str())) {
            return FamilyMatch::bare(Some(Refusal::FamilyUnregistered));
        }
        // A case-mutated reserved or closed stem (`Capacity:zz:v1`) is
        // malformed, never a bypass: fold only to DETECT the fence.
        let low = dimension.to_lowercase();
        if low != dimension && fenced().any(|stem| low.starts_with(stem.as_str())) {
            return FamilyMatch::bare(Some(Refusal::CaseMalformed));
        }
        // Open vocabulary: no row claims it — but R3's version grammar is
        // global: exactly one trailing version segment.
        let last = parts[parts.len() - 1];
        if r.version_required && !r.version.is_match(last) {
            return FamilyMatch::bare(Some(if mutated_tail(r, last) {
                Refusal::CaseMalformed
            } else {
                Refusal::MissingVersionSegment
            }));
        }
        // A duplicated tail (`third_party:signal:v1:v2`), or a version with no
        // family segment before it (`v1`), is malformed.
        if parts.len() < 2 || r.version_like.is_match(parts[parts.len() - 2]) {
            return FamilyMatch::bare(Some(Refusal::CaseMalformed));
        }
        return FamilyMatch::bare(None);
    };
    let Resolved {
        fam,
        mut binds,
        refusal,
        has_version,
    } = hit;
    let with = |binds, refusal| FamilyMatch {
        family: Some(fam.prefix),
        binds,
        refusal,
    };
    if refusal.is_some() {
        // A refused hit may be a MALFORMED form of a different row that
        // resolves cleanly once folded or stripped — a leaf under a wildcard
        // parent (`accord:lifecycle:V1`), or a companion row hidden by an
        // arity-exact sibling (`capacity_assurance:reversible_excluded:
        // medical:v1:v2`). The clean row is the family it mutates (#116).
        if let Some(mutated) = detect_malformed(r, &parts, true) {
            if mutated != fam.prefix {
                return malformed_as(mutated);
            }
        }
        return with(binds, refusal);
    }
    let versioned = parts.last().is_some_and(|p| r.version.is_match(p));
    // Closed leaves: a wildcard family — or a parameterized parent whose row
    // is closed in its leaves (`consent:{kind}`) — only admits the leaves CC
    // names.
    if fam.leaves_closed && matches!(fam.last_class(), Some(Class::Wildcard | Class::Vocab)) {
        let leaf_parts = if versioned && has_version {
            &parts[..parts.len() - 1]
        } else {
            &parts[..]
        };
        let ok_leaf = fam.leaves.iter().any(|l| {
            r.family(l)
                .is_some_and(|lf| match_segments(&lf.segments, leaf_parts, r).is_some())
        });
        if !ok_leaf {
            return with(binds, Some(Refusal::FamilyUnregistered));
        }
    }
    if r.version_required && !r.exempt.iter().any(|e| e == fam.prefix) && !has_version {
        return with(binds, Some(Refusal::MissingVersionSegment));
    }
    if has_version {
        binds.insert(
            "version".to_owned(),
            (*parts.last().unwrap_or(&"")).to_owned(),
        );
    }
    with(binds, None)
}

/// The families [`match_family`] can resolve to, in manifest order.
pub fn families() -> impl Iterator<Item = &'static str> {
    rules().families.iter().map(|f| f.prefix)
}

// ── the version segment (one parser) ────────────────────────────────────

/// **The one version parser** (v50.0.0, CIRISPersist#924) — does `segment`
/// match `_meta.case_rule.version_segment.pattern` (`^v[0-9]+(\.[0-9]+)*$` on
/// rc5)?
///
/// Replaces the three persist carried: `admission::contains_version_segment`
/// (a `:v[0-9]+` byte scan ANYWHERE in the dimension), `schema_resolver::
/// is_version_segment` (`^v[0-9]+$`, no dotted versions) and the ledger gate's
/// `strip_prefix('v')`.
#[must_use]
pub fn is_version_segment(segment: &str) -> bool {
    rules().version.is_match(segment)
}

/// Does `token` match `_meta.case_rule.vocab_pattern` (a lowercase CC
/// vocabulary token)? For hand checks the registry cannot express as a row.
#[must_use]
pub fn is_vocab_token(token: &str) -> bool {
    rules().vocab.is_match(token)
}

/// The trailing version segment of `dimension` — its LAST `:`-segment, when
/// that matches the manifest's pattern. CC 3.1.7 R3: the version is trailing,
/// exactly one, after the family's own segments.
#[must_use]
pub fn trailing_version(dimension: &str) -> Option<&str> {
    dimension
        .rsplit(':')
        .next()
        .filter(|last| dimension.contains(':') && is_version_segment(last))
}

/// Is `family` (a registry prefix) in `_meta.case_rule.version_segment.exempt`
/// — the families that carry no version tail (the five mechanism-named
/// attestation-ladder families and `identity:canonical_binding:{canonical_hash}`)?
///
/// The two carve-outs persist used to spell in code
/// (`is_attestation_ladder_dimension`, `parse_canonical_binding_hash`) are this
/// list; they stopped being code in v50.0.0.
#[must_use]
pub fn is_version_exempt(family: &str) -> bool {
    rules().exempt.iter().any(|e| e == family)
}

/// Whether the manifest REQUIRES the version segment
/// (`_meta.case_rule.version_segment.required`).
#[must_use]
pub fn version_segment_required() -> bool {
    rules().version_required
}

/// The `_meta.case_rule.reserved_stems` stems, in manifest order.
pub fn reserved_stems() -> impl Iterator<Item = &'static str> {
    rules().reserved_stems.iter().map(String::as_str)
}

/// The `(rule, cc_ref)` of the longest `_meta.case_rule.reserved_stems` stem
/// of `kind: reserved` that `dimension` sits under, if any. (A `kind: gated`
/// stem — `age_self_declared:` — states an emitter rule without a
/// reservation, so it is not a reserved rule; the matcher still refuses its
/// unclaimed leaves.) What a classifier reports for a dimension
/// under a reserved stem that no row claims — the reservation covers the
/// leaves nobody minted yet (CC 3.1.7 R3), so it must not read as open.
#[must_use]
pub fn reserved_stem_rule(dimension: &str) -> Option<(&'static str, &'static str)> {
    rules()
        .reserved_stem_rules
        .iter()
        .filter(|(stem, _, _)| dimension.starts_with(stem.as_str()))
        .max_by_key(|(stem, _, _)| stem.len())
        .map(|(_, rule, cc_ref)| (rule.as_str(), cc_ref.as_str()))
}

/// A family's `{placeholder}` values, when its row enumerates them
/// (`segments[].values`), with whether the enumeration is OPEN.
#[must_use]
pub fn placeholder_values(family: &str, placeholder: &str) -> Option<(&'static [String], bool)> {
    let fam = rules().family(family)?;
    let seg = fam.segments.iter().find(|s| s.segment == placeholder)?;
    seg.values.as_deref().map(|v| (v, seg.open))
}

/// A wildcard family's published `leaves`, and whether they are closed.
#[must_use]
pub fn family_leaves(family: &str) -> Option<(&'static [String], bool)> {
    let fam = rules().family(family)?;
    Some((fam.leaves.as_slice(), fam.leaves_closed))
}

/// A class-conformant sample dimension for `family` — a port of the
/// reference's `instantiate(fam, with_version=True)`, the same sample CC's
/// generator round-trips every family through. For tests that need "an
/// ordinary dimension on this family" (a literal stem such as `"system:"` is
/// not one: it has an empty segment and is malformed).
#[cfg(test)]
#[must_use]
pub(crate) fn sample_dimension(family: &str) -> Option<String> {
    let fam = rules().family(family)?;
    let mut out: Vec<String> = Vec::new();
    for seg in &fam.segments {
        let tok = match seg.class {
            Class::Literal => seg.segment.clone(),
            Class::Wildcard => "leaf".to_owned(),
            Class::Vocab => {
                let t = match &seg.values {
                    Some(v) if !v.is_empty() => v[0].clone(),
                    _ if seg.segment == "{version}" => "v1".to_owned(),
                    _ => "sample".to_owned(),
                };
                if seg.multi {
                    format!("{t}:sub")
                } else {
                    t
                }
            }
            Class::External => match seg.name.as_str() {
                "lang_code" => "en-US".to_owned(),
                "rating" => "PG-13".to_owned(),
                _ => "USD".to_owned(),
            },
            Class::Value | Class::Hex => match seg.pattern.as_ref().map(Regex::as_str) {
                Some(p) if p.contains("0-9") && !p.contains("a-f") => "42".to_owned(),
                Some(p) if p.contains("{64}") => "abcdef0123456789".repeat(4),
                _ if seg.class == Class::Hex => "ab12".to_owned(),
                _ if seg.multi => "id1:id2".to_owned(),
                _ => "id1".to_owned(),
            },
        };
        out.push(tok);
    }
    if !fam.ends_version() {
        out.push("v1".to_owned());
    }
    Some(out.join(":"))
}

/// Is `prefix` (ending in `:`) a run of LITERAL segments that some registry
/// family starts with, byte for byte — `"detection:distributive:access:"` for
/// `detection:distributive:access:{resource_type}`, `"system:"` for
/// `system:*`? The spelling check a hand-written reserved-rule prefix must
/// pass (`reserved_prefix_rules_match_manifest_leaves`).
#[must_use]
pub fn is_literal_family_prefix(prefix: &str) -> bool {
    let Some(body) = prefix.strip_suffix(':') else {
        return false;
    };
    let want: Vec<&str> = body.split(':').collect();
    rules().families.iter().any(|f| {
        f.segments.len() > want.len()
            && f.segments
                .iter()
                .zip(&want)
                .all(|(s, w)| s.class == Class::Literal && s.segment == *w)
    })
}

/// Refusal lookup by its wire token (the inverse of [`Refusal::as_str`]).
#[must_use]
pub fn refusal_from_token(token: &str) -> Option<Refusal> {
    Refusal::from_token(token)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The reference's own `(family, binds, refusal)` per vector, generated by
    /// `scripts/gen_namespace_match_binds.py` (see the module doc).
    const BINDS_JSON: &str = include_str!("namespace_match_binds.json");

    fn vectors() -> Vec<serde_json::Value> {
        let root: serde_json::Value = serde_json::from_str(VECTORS_JSON).unwrap();
        root["vectors"].as_array().unwrap().clone()
    }

    /// CC 3.1.7 R3 / CIRISConstitution#112 — **every published vector yields
    /// the reference's `(family, binds, refusal)`.**
    ///
    /// Two checks per vector. (1) CC's own contract against the published
    /// vector: family and refusal exact. (Before rc5's release the family was
    /// best-effort on a `namespace_dimension_case_malformed` refusal; the
    /// released vectors name exactly what the reference answers,
    /// CIRISConstitution#116.) (2) The port against the REFERENCE's own output
    /// (`namespace_match_binds.json`): family, binds and refusal all exact —
    /// the vectors carry no binds, so a porting defect in the binds would
    /// otherwise pass.
    #[test]
    fn namespace_match_vectors_replay() {
        let vs = vectors();
        assert_eq!(
            vs.len(),
            1040,
            "the rc6 vectors file at 1f45ebe carries 1040 dimension vectors"
        );
        let oracle: serde_json::Value = serde_json::from_str(BINDS_JSON).unwrap();
        let oracle = oracle["binds"].as_array().unwrap();
        assert_eq!(oracle.len(), vs.len(), "one oracle entry per vector");
        let mut bad = Vec::new();
        for (v, o) in vs.iter().zip(oracle) {
            let dim = v["dimension"].as_str().unwrap();
            assert_eq!(o["dimension"], v["dimension"], "oracle out of order");
            let got = match_family(dim);
            let got_refusal = got.refusal.map(Refusal::as_str);
            // (1) CC's contract against the published vector.
            let want_refusal = v["refusal"].as_str();
            if got.family != v["family"].as_str() || got_refusal != want_refusal {
                bad.push(format!(
                    "{dim:?}: vector wants ({:?}, {want_refusal:?}) got ({:?}, {got_refusal:?})",
                    v["family"].as_str(),
                    got.family
                ));
            }
            // (2) the reference's exact output.
            let ref_binds: BTreeMap<String, String> =
                serde_json::from_value(o["binds"].clone()).unwrap();
            if got.family != o["family"].as_str()
                || got_refusal != o["refusal"].as_str()
                || got.binds != ref_binds
            {
                bad.push(format!(
                    "{dim:?}: reference gives ({:?}, {ref_binds:?}, {:?}) got ({:?}, {:?}, \
                     {got_refusal:?})",
                    o["family"].as_str(),
                    o["refusal"].as_str(),
                    got.family,
                    got.binds
                ));
            }
        }
        assert!(
            bad.is_empty(),
            "{} divergence(s) from the CC reference matcher over {} vectors:\n{}",
            bad.len(),
            vs.len(),
            bad.join("\n")
        );
    }

    /// The vectors exercise every refusal the grammar has — a replay over a
    /// file that stopped carrying one would stop measuring it.
    #[test]
    fn the_vectors_cover_every_refusal_and_open_vocabulary() {
        let vs = vectors();
        for r in Refusal::ALL {
            assert!(
                vs.iter().any(|v| v["refusal"] == r.as_str()),
                "no vector refuses {r}"
            );
        }
        assert!(vs
            .iter()
            .any(|v| v["family"].is_null() && v["refusal"].is_null()));
    }

    /// The enum spells exactly the manifest's `refusal_tokens`, both ways.
    #[test]
    fn refusal_tokens_are_the_manifests() {
        let root: serde_json::Value =
            serde_json::from_str(super::super::registry::REGISTRY_JSON).unwrap();
        let tokens = root["_meta"]["case_rule"]["refusal_tokens"]
            .as_object()
            .unwrap();
        // The manifest's token table also names the ROW-TYPE refusal (CC 2.4,
        // `_meta.row_types.refusal`). It refuses an `attestation_type`, never a
        // dimension, so the dimension matcher has no variant for it: it is
        // excluded here by reading it from the manifest, not by spelling it.
        let row_type_refusal = root["_meta"]["row_types"]["refusal"].as_str().unwrap();
        let dimension_tokens: Vec<&str> = tokens
            .values()
            .filter_map(|t| t.as_str())
            .filter(|t| *t != row_type_refusal)
            .collect();
        assert_eq!(dimension_tokens.len() + 1, tokens.len());
        assert_eq!(dimension_tokens.len(), Refusal::ALL.len());
        assert_eq!(refusal_from_token(row_type_refusal), None);
        for r in Refusal::ALL {
            assert_eq!(
                tokens.get(r.manifest_key()).and_then(|t| t.as_str()),
                Some(r.as_str())
            );
            assert_eq!(refusal_from_token(r.as_str()), Some(r));
        }
    }

    /// The no-drift half: the vendored vectors ARE CC's file (byte equality is
    /// checked against the CC repo at vendor time; here, the file names the
    /// grammar it was generated from, and the binds oracle names the same
    /// dimensions in the same order).
    #[test]
    fn vendored_vectors_name_the_vendored_grammar() {
        let root: serde_json::Value = serde_json::from_str(VECTORS_JSON).unwrap();
        assert_eq!(
            root["_meta"]["registry_sha256"],
            super::super::registry::VENDORED_REGISTRY_SHA256
        );
        assert_eq!(root["_meta"]["generator"], "tools/cc_namespace_match.py");
        let binds: serde_json::Value = serde_json::from_str(BINDS_JSON).unwrap();
        assert_eq!(
            binds["_meta"]["cc_commit"],
            super::super::registry::VENDORED_CC_COMMIT
        );
        assert_eq!(
            binds["_meta"]["vectors_sha256"],
            {
                use sha2::{Digest, Sha256};
                hex::encode(Sha256::digest(VECTORS_JSON.as_bytes()))
            },
            "the binds oracle was generated from a different vectors file"
        );
    }

    /// The reference generator's round-trip gate, replayed: every family's
    /// class-conformant sample resolves to that family and no other, with no
    /// refusal (exempt families included: a tail is tolerated). Closed
    /// families — a wildcard, or since the released rc5 a parameterized
    /// parent closed in its leaves (`consent:{kind}`) — are skipped exactly as
    /// the reference skips them: their sample leaf is, by design, unregistered
    /// (each listed leaf round-trips on its own row).
    #[test]
    fn every_family_sample_round_trips_to_itself() {
        let r = rules();
        let mut bad = Vec::new();
        for fam in families() {
            let f = r.family(fam).unwrap();
            if f.leaves_closed && matches!(f.last_class(), Some(Class::Wildcard | Class::Vocab)) {
                continue;
            }
            let dim = sample_dimension(fam).unwrap();
            let got = match_family(&dim);
            if got.family != Some(fam) || got.refusal.is_some() {
                bad.push(format!("{fam}: {dim:?} -> {got:?}"));
            }
        }
        assert!(bad.is_empty(), "{bad:#?}");
    }

    /// `_meta.case_rule.match_semantics` (CIRISConstitution#116) — the
    /// full-match half made structural. `compile` anchors every manifest
    /// pattern, so an UNANCHORED pattern cannot partial-match, and a `$` never
    /// admits a trailing newline.
    #[test]
    fn compile_is_a_full_match() {
        let unanchored = compile("[a-z]+");
        assert!(unanchored.is_match("abc"));
        for partial in ["abc1", "1abc", "ab-c", "abc\n", ""] {
            assert!(
                !unanchored.is_match(partial),
                "unanchored pattern partial-matched {partial:?}"
            );
        }
        let anchored = compile("^[a-z]+$");
        assert!(
            !anchored.is_match("abc\n"),
            "`$` admitted a trailing newline"
        );
        // Through the matcher: a segment carrying a newline fails its pattern
        // (the rc5 vector `config:admission\n:v1`), and so does the version.
        assert_eq!(
            match_family("config:admission\n:v1").refusal,
            Some(Refusal::CaseMalformed)
        );
        assert!(!is_version_segment("v1\n"));
        assert!(!is_vocab_token("abc\n"));
    }

    /// The manifest DECLARES full-match semantics — a re-vendor that drops the
    /// declaration (or changes its meaning) must be looked at, not absorbed.
    #[test]
    fn the_manifest_declares_full_match_semantics() {
        let root: serde_json::Value =
            serde_json::from_str(super::super::registry::REGISTRY_JSON).unwrap();
        let ms = root["_meta"]["case_rule"]["match_semantics"]
            .as_str()
            .expect("_meta.case_rule.match_semantics is present");
        assert!(ms.starts_with("full-match"), "{ms:?}");
    }

    /// Edges no published vector reaches, answered by the released reference
    /// (`tools/cc_namespace_match.py` at c60d0a6, run over the vendored
    /// registry): a closed
    /// parameterized parent's unlisted and case-mutated kinds, and a version
    /// ATTEMPT on a companion row and on open vocabulary. (The two
    /// newline-bearing `no_such_family:v1\n:v2` edges left this table at the
    /// rc6 re-vendor: CIRISConstitution#128 made the detectors full-match, the
    /// answer became open vocabulary, and they are published vectors now.)
    #[test]
    fn reference_edges_beyond_the_vectors() {
        /// `(dimension, family, binds, refusal)` as the reference answers.
        type Edge = (
            &'static str,
            Option<&'static str>,
            &'static [(&'static str, &'static str)],
            Refusal,
        );
        let cases: [Edge; 6] = [
            (
                "consent:made_up:v1",
                Some("consent:{kind}"),
                &[("kind", "made_up")],
                Refusal::FamilyUnregistered,
            ),
            (
                "consent:Made:v1",
                Some("consent:{kind}"),
                &[("kind", "Made")],
                Refusal::CaseMalformed,
            ),
            (
                "Consent:made_up:v1",
                Some("consent:{kind}"),
                &[],
                Refusal::CaseMalformed,
            ),
            (
                "capacity_assurance:reversible_excluded:financial:v1beta",
                Some("capacity_assurance:reversible_excluded:{domain}:{version}"),
                &[("domain", "financial"), ("version", "v1beta")],
                Refusal::CaseMalformed,
            ),
            (
                "no_such_family:leaf:v1beta",
                None,
                &[],
                Refusal::CaseMalformed,
            ),
            (
                "system:foo:v1beta\n:v1",
                Some("system:*"),
                &[("*", "foo:v1beta\n")],
                Refusal::CaseMalformed,
            ),
        ];
        for (dim, family, binds, refusal) in cases {
            let got = match_family(dim);
            let want: BTreeMap<String, String> = binds
                .iter()
                .map(|(k, v)| ((*k).to_owned(), (*v).to_owned()))
                .collect();
            assert_eq!(
                (got.family, got.binds, got.refusal),
                (family, want, Some(refusal)),
                "{dim:?}"
            );
        }
    }

    /// The released rc5 rewrote `{lang_code}` to canonical-cased RFC 5646
    /// (no extlang; private use and the five grandfathered tags without a
    /// preferred value admitted literally). The provenance-locale witness
    /// (`en-US`) still holds; these are the spellings whose answer MOVED.
    #[test]
    fn provenance_locale_is_canonical_bcp47() {
        let dim = |tag: &str| format!("provenance:build_manifest:agent-3.2.1:locale:{tag}:v1");
        let family = Some("provenance:build_manifest:{target}:locale:{lang_code}");
        for ok in [
            "en-US",
            "en",
            "zh-Hans-CN",
            "es-419",
            "de-CH-1996",
            "x-private",
            "i-default",
        ] {
            let m = match_family(&dim(ok));
            assert_eq!((m.family, m.refusal), (family, None), "{ok}");
        }
        // Admitted by the pre-release pattern, refused now: non-canonical
        // casing and extlang forms (written as their preferred value).
        for bad in ["en-us", "EN", "zh-hans-cn", "zh-cmn-Hans-CN", "sgn-BE-FR"] {
            let m = match_family(&dim(bad));
            assert_eq!(
                (m.family, m.refusal),
                (family, Some(Refusal::CaseMalformed)),
                "{bad}"
            );
        }
    }

    #[test]
    fn version_segment_parser_reads_the_manifest_pattern() {
        for ok in ["v1", "v2", "v10", "v1.2", "v1.2.3"] {
            assert!(is_version_segment(ok), "{ok}");
        }
        for bad in ["V1", "v", "v1.", "1", "v1a", "vv1", "v1:v2", ""] {
            assert!(!is_version_segment(bad), "{bad}");
        }
        assert_eq!(trailing_version("objection:raised:v1"), Some("v1"));
        assert_eq!(trailing_version("benchmark:he300:x:v1.2"), Some("v1.2"));
        assert_eq!(trailing_version("foo:v1:bar"), None, "trailing only");
        assert_eq!(trailing_version("v1"), None, "a lone segment is no tail");
        assert!(is_version_exempt("attestation:self_verify"));
        assert!(is_version_exempt(
            "identity:canonical_binding:{canonical_hash}"
        ));
        assert!(!is_version_exempt("config:{scope}"));
    }
}
