//! **CIRISPersist#425 — the vendored CC-3.1 namespace registry + `authority_for`.**
//!
//! The dimension-namespace catalog (CC 3.1 `part_3_the_namespace.md`) rendered
//! machine-readable and vendored as [`namespace_registry.json`]. **CC is the
//! single source of truth**: the file is GENERATED by the Constitution's
//! `tools/build_cc_namespace.py`, never hand-authored here. Persist is a
//! distribution channel so downstream (CIRISEdge#425 replication engine, the
//! manifest verifier) resolves `authority_for(dimension)` from data rather than
//! re-deriving it from CC prose.
//!
//! **Drift control.** [`VENDORED_CC_VERSION`] / [`VENDORED_SOURCE_SHA256`] /
//! [`VENDORED_N_FAMILIES`] pin the exact CC cut this copy was generated from; a
//! test asserts the vendored file's `_meta` matches. Re-vendoring after a CC
//! change is therefore a deliberate, reviewable bump of all three consts — the
//! copy can never silently drift from the Constitution it mirrors.
//!
//! **The removal direction is the dangerous one** (CIRISPersist#590).
//! A count bump plus a source-hash bump is the signature of *any* re-vendor —
//! including one that silently DROPS families. CC's own first CC-3.1.7-R2
//! regeneration lost four (`judge_model:verdict`, `health:liveness`,
//! `seed_holder_voting_alignment`, `watchlist`) to a prose paragraph inserted
//! mid-table (a blank line plus prose terminates a markdown table), and the
//! only signal was a count discrepancy that was very nearly reconciled away.
//! So the drift control is not only the three consts: [`VENDORED_FAMILY_PREFIXES`]
//! pins every family this cut carries and
//! [`tests::no_vendored_family_silently_disappears`] fails on any prefix that
//! vanishes. Additions are cheap and pass; a removal must be moved to
//! [`RETIRED_FAMILIES`] by hand, with a reason — which is exactly the review a
//! silent drop never gets.
//!
//! [`namespace_registry.json`]: <the vendored file in this directory>

use super::{Authority, AuthorityClass, ReservedRule};
use std::sync::OnceLock;

/// The vendored copy of the Constitution manifest, compiled in.
const REGISTRY_JSON: &str = include_str!("namespace_registry.json");

/// The CC version [`REGISTRY_JSON`] was generated from. Bump in lockstep when
/// re-vendoring (the drift gate asserts the file's `_meta.cc_version` matches).
pub const VENDORED_CC_VERSION: &str = "1.0-rc5";
/// SHA-256 of the CC `part_3_the_namespace.md` bytes the manifest was generated
/// from (the manifest's `_meta.source_sha256`). Pins the exact source cut.
pub const VENDORED_SOURCE_SHA256: &str =
    "1b1a248a4e863130d9ad6ec6cc6c8b3e57e9311b0b710ffb735b04d4c926afa3";
/// The number of prefix families in this vendored cut (the enumerated leaf
/// count; CC 3.1's "83" summary is stale — see CIRISConstitution#30).
pub const VENDORED_N_FAMILIES: usize = 116;

/// One resolved namespace family — a CC 3.1 prefix, its owning component, and
/// the [`Authority`] its reserved-prefix rule (CC 3.4) demands.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NamespaceEntry {
    /// The catalogued family prefix, verbatim from CC 3.1 (e.g.
    /// `"provenance:build_manifest:{target}"`, `"accord:*"`,
    /// `"audit_chain:hash_continuity"`).
    pub prefix: String,
    /// The literal prefix a concrete `dimension` is matched against — `prefix`
    /// truncated at its first `{` parameter or `*` wildcard (e.g.
    /// `"provenance:build_manifest:"`, `"accord:"`). Longest match wins in
    /// [`authority_for`].
    pub match_prefix: String,
    /// The owning component slug (CC 3.1.N heading), e.g. `"persist"`,
    /// `"attestation"`, `"registry"`.
    pub owning_component: String,
    /// The steward repo, when the manifest records one.
    pub owning_repo: Option<String>,
    /// The CC section the family is catalogued in (e.g. `"3.1.2"`).
    pub cc_section: String,
    /// The row's catalogue PROSE, verbatim from the manifest (the generator's
    /// first-sentence extract of the CC 3.1 table cell).
    ///
    /// Carried since CIRISPersist#571 for one reason: several rc3 rows state an
    /// emitter rule in this field while generating `reserved: false` with no
    /// [`Authority::reserved`] — `regime:{artifact}:{version}` says *"reserved —
    /// substrate-steward-emitted"* and resolves `ProducerSteward`/`None`. Persist
    /// deliberately does **not** enforce anything read from here (that would be
    /// the section-walk heuristic CC 3.1.7 R2 forbids); it exists so a test can
    /// quote the row's own words back and FAIL when structure and prose
    /// disagree, instead of that disagreement living in a comment.
    pub description: String,
    /// The resolved emit authority (class + any CC 3.4 reserved rule).
    pub authority: Authority,
}

// ── raw serde shapes matching the generated manifest ────────────────────

#[derive(serde::Deserialize)]
struct RawManifest {
    #[serde(rename = "_meta")]
    meta: RawMeta,
    families: Vec<RawFamily>,
}

#[derive(serde::Deserialize)]
struct RawMeta {
    cc_version: String,
    source_sha256: String,
    n_families: usize,
    /// **The `_meta` key the R2 Private Use ask asked for, and the rc3
    /// re-vendor delivered.** `x_private:` on this cut.
    ///
    /// [`PRIVATE_USE_FAMILY_STEM`](crate::federation::admission::PRIVATE_USE_FAMILY_STEM)
    /// says of itself that it is "a prose transcription", and names the remedy
    /// in its own doc: *"a machine-readable range field in the generated
    /// manifest (a `_meta` key, not a family row, since it is not a family)"*.
    /// That field now exists, so
    /// [`tests::the_private_use_range_is_machine_readable_now`] binds the
    /// transcription to it — the const stops being a claim about CC prose that
    /// nothing can contradict and becomes one the vendored artifact can.
    ///
    /// Worth noting what this is NOT: it does not make persist enforce the
    /// range from the manifest. The refusal
    /// ([`check_private_use_not_federatable`](crate::federation::admission::check_private_use_not_federatable))
    /// still matches on the const, because a range read from a mutable data
    /// file is a range an attacker who can influence the vendored bytes could
    /// move. What the field buys is that the const can no longer be silently
    /// WRONG.
    ///
    /// `Option` because a cut generated before CC shipped the field carries
    /// none, and the gate should say WHICH cut is stale rather than fail to
    /// parse.
    #[serde(default)]
    private_use_prefix: Option<String>,
}

#[derive(serde::Deserialize)]
struct RawFamily {
    prefix: String,
    owning_component: String,
    #[serde(default)]
    owning_repo: Option<String>,
    cc_section: String,
    #[serde(default)]
    description: String,
    // NOTE: the manifest's `reserved` bool is redundant with `reserved_rule`
    // presence (which carries the CC 3.4 specifics) — serde ignores it.
    #[serde(default)]
    reserved_rule: Option<RawReservedRule>,
}

#[derive(serde::Deserialize)]
struct RawReservedRule {
    rule: String,
    /// **Optional in the manifest.** Most reserved families name the CC 3.4
    /// clause that rules them (`"CC 3.4.1"`); a family whose reservation is
    /// stated in its own CC 3.1 catalogue row rather than a separate clause
    /// carries `"cc_ref": null` (rc3: `trust:{job}:{version}`). Deserializing
    /// that into a `String` is what a `serde` `missing field`/`invalid type`
    /// panic at first `authority_for` call looks like, so it is typed
    /// `Option` and resolved to the family's own catalogue section in
    /// [`parse_manifest`] — never to an empty string, which would be a
    /// citation that reads as present and points nowhere.
    #[serde(default)]
    cc_ref: Option<String>,
}

/// The literal stem of a family prefix — everything before the first `{`
/// parameter or `*` wildcard. `"accord:*"` → `"accord:"`;
/// `"provenance:build_manifest:{target}"` → `"provenance:build_manifest:"`;
/// `"audit_chain:hash_continuity"` → itself.
fn match_prefix_of(prefix: &str) -> String {
    let cut = prefix.find(['{', '*']).unwrap_or(prefix.len());
    prefix[..cut].to_string()
}

/// **The one match_prefix this classifier answers from persist's own source
/// rather than from the manifest** (CIRISPersist#519).
///
/// A build manifest is accord-co-scrubbed — identical authority to a canonical
/// seed, which is what closes the chicken/egg at genesis. CC's
/// `provenance:build_manifest:{target}` row states no `reserved_rule`, so
/// [`authority_for`] returns an authority the Constitution's artifact never
/// carried, and nothing downstream can audit that answer against CC.
///
/// Named rather than inlined so [`crate::federation::family_rules`] can read
/// the assertion at its source and pin it as the gap it is
/// (`RowRuleGap::ClassAssertedByPersistNotTheRow`); the ask is to land the
/// rule on the row and delete the arm.
pub const ACCORD_CO_SCRUB_MATCH_PREFIX: &str = "provenance:build_manifest";

/// Derive the emit [`AuthorityClass`] for a family from its catalogued
/// reserved-emit rule, layering persist's own trust-root knowledge on top.
///
/// - `provenance:build_manifest:*` → [`AccordCoScrub`](AuthorityClass::AccordCoScrub):
///   a build manifest is accord-co-scrubbed (the `infra:attest` gate), identical
///   authority to a canonical seed — the property that closes the chicken/egg.
/// - `substrate-self-report` (CC 3.4.3) → [`SubstrateSelf`](AuthorityClass::SubstrateSelf).
/// - any other reserved rule (accord_holder-only, detector-only, witness-emitter,
///   co-stewarded, no-self-emit) or an unreserved dimension →
///   [`ProducerSteward`](AuthorityClass::ProducerSteward); the CC 3.4 specifics
///   ride in [`Authority::reserved`].
///
/// NOTE: no CC 3.1 *dimension* prefix resolves to
/// [`SelfIdentity`](AuthorityClass::SelfIdentity) — that authority governs the
/// CC 3.3 *subject-kind* objects (key records, identity occurrences, transport
/// bindings), which the edge engine authorizes structurally (via the object
/// kind), not through this dimension registry.
fn class_for(match_prefix: &str, rule: Option<&str>) -> AuthorityClass {
    if match_prefix.starts_with(ACCORD_CO_SCRUB_MATCH_PREFIX) {
        return AuthorityClass::AccordCoScrub;
    }
    match rule {
        Some("substrate-self-report") => AuthorityClass::SubstrateSelf,
        _ => AuthorityClass::ProducerSteward,
    }
}

fn parse_manifest() -> Vec<NamespaceEntry> {
    let raw: RawManifest =
        serde_json::from_str(REGISTRY_JSON).expect("vendored namespace_registry.json is valid");
    // Drift invariants (also enforced as a hard test in this module): the
    // vendored cut must be the one the consts pin, and be self-consistent.
    debug_assert_eq!(raw.meta.cc_version, VENDORED_CC_VERSION, "cc_version drift");
    debug_assert_eq!(
        raw.meta.source_sha256, VENDORED_SOURCE_SHA256,
        "CC part_3 source hash drift — regenerate + re-vendor"
    );
    assert_eq!(
        raw.families.len(),
        raw.meta.n_families,
        "manifest self-consistency: families[] != _meta.n_families"
    );
    let mut entries: Vec<NamespaceEntry> = raw
        .families
        .into_iter()
        .map(|f| {
            let match_prefix = match_prefix_of(&f.prefix);
            let reserved = f.reserved_rule.map(|r| ReservedRule {
                rule: r.rule,
                // A manifest row with no `cc_ref` is ruled by its own CC 3.1
                // catalogue row; cite THAT rather than leave the field an
                // empty string a reader would take for a missing citation.
                cc_ref: r.cc_ref.unwrap_or_else(|| format!("CC {}", f.cc_section)),
            });
            let class = class_for(&match_prefix, reserved.as_ref().map(|r| r.rule.as_str()));
            NamespaceEntry {
                prefix: f.prefix,
                match_prefix,
                owning_component: f.owning_component,
                owning_repo: f.owning_repo,
                cc_section: f.cc_section,
                description: f.description,
                authority: Authority { class, reserved },
            }
        })
        .collect();
    // Longest match_prefix first so `authority_for`'s first hit is the most
    // specific (e.g. `provenance:build_manifest:` beats a hypothetical
    // `provenance:` before it).
    entries.sort_by(|a, b| {
        b.match_prefix
            .len()
            .cmp(&a.match_prefix.len())
            .then_with(|| a.prefix.cmp(&b.prefix))
    });
    entries
}

fn registry() -> &'static [NamespaceEntry] {
    static REGISTRY: OnceLock<Vec<NamespaceEntry>> = OnceLock::new();
    REGISTRY.get_or_init(parse_manifest)
}

/// The full vendored namespace registry (every CC 3.1 prefix family), sorted
/// most-specific-`match_prefix`-first. Edge enumerates this to build its
/// dimension→policy table once at boot.
pub fn entries() -> &'static [NamespaceEntry] {
    registry()
}

/// The **Private Use range**, read from the vendored manifest's `_meta` rather
/// than transcribed from CC prose. `None` on a cut generated before CC shipped
/// the field.
///
/// See [`RawMeta::private_use_prefix`] — including what this deliberately does
/// not change about enforcement.
#[must_use]
pub fn vendored_private_use_prefix() -> Option<&'static str> {
    static P: OnceLock<Option<String>> = OnceLock::new();
    P.get_or_init(|| {
        let raw: RawManifest =
            serde_json::from_str(REGISTRY_JSON).expect("vendored namespace_registry.json is valid");
        raw.meta.private_use_prefix
    })
    .as_deref()
}

/// The [`NamespaceEntry`] whose `match_prefix` is the **longest prefix** of
/// `dimension`, or `None` if `dimension` is outside the CC namespace. The
/// registry is pre-sorted longest-first, so this returns the most specific
/// match.
pub fn lookup(dimension: &str) -> Option<&'static NamespaceEntry> {
    registry()
        .iter()
        .find(|e| dimension.starts_with(&e.match_prefix))
}

/// **`authority_for(dimension)`** — the emit authority the `dimension`'s
/// reserved-prefix rule (CC 3.4) demands, resolved from the vendored CC-3.1
/// registry. A `dimension` outside the namespace defaults to
/// [`ProducerSteward`](AuthorityClass::ProducerSteward) with no reserved rule (a
/// signed producer claim; the write-path reserved-prefix admission gate is the
/// enforcement point, not this classifier). Infra prefixes
/// (`provenance:build_manifest:*`) resolve to
/// [`AccordCoScrub`](AuthorityClass::AccordCoScrub) — identical to a canonical
/// record, closing the chicken/egg.
pub fn authority_for(dimension: &str) -> Authority {
    lookup(dimension)
        .map(|e| e.authority.clone())
        .unwrap_or(Authority {
            class: AuthorityClass::ProducerSteward,
            reserved: None,
        })
}

// ── (CIRISPersist#590, CC 3.1.7 R2) — family-STEM registration ──

/// The **family stem** of a dimension or `attestation_type` — everything up to
/// and including its first `:` (`"objection:raised:v1"` → `"objection:"`), or
/// the whole token when it carries no `:`.
///
/// This is the granularity CC 3.1.7 R2 speaks at. R2 refuses "a family with no
/// registry row"; a *family* is `objection:{state}`, not the leaf
/// `objection:raised:v1`, and CC explicitly preserves "the open-vocabulary space
/// this Part deliberately leaves open" — the `{param}` slots WITHIN a registered
/// family. Enforcing at leaf granularity would refuse exactly that open
/// vocabulary (`credits:{domain}:{language}:{subject}` admits any domain), which
/// is the "refuse conformant traffic" failure CIRISPersist#590 was opened to
/// prevent.
#[must_use]
pub fn family_stem(dimension: &str) -> &str {
    match dimension.find(':') {
        Some(i) => &dimension[..=i],
        None => dimension,
    }
}

/// Every **family stem** the vendored manifest registers, sorted and deduped.
/// The R2 registration test: a stem in this set has at least one catalogue row,
/// so a dimension under it is emitted on a *registered* family.
pub fn registered_family_stems() -> &'static [&'static str] {
    static STEMS: OnceLock<Vec<&'static str>> = OnceLock::new();
    STEMS.get_or_init(|| {
        let mut v: Vec<&'static str> = registry().iter().map(|e| family_stem(&e.prefix)).collect();
        v.sort_unstable();
        v.dedup();
        v
    })
}

/// **CC 3.1.7 R2 registration predicate** — does `dimension` sit on a family the
/// vendored manifest registers? Consumes the MANIFEST, never a section-walk
/// heuristic (R2's normative enforcement surface: "a walker that reads only
/// `### 3.1.N` refuses traffic this Part reserves").
///
/// Stem-granular by [`family_stem`]. `""` is not a family and answers `false`.
#[must_use]
pub fn is_family_registered(dimension: &str) -> bool {
    let stem = family_stem(dimension);
    !stem.is_empty() && registered_family_stems().binary_search(&stem).is_ok()
}

/// **The removal gate** (CIRISPersist#590 item 4). Every family prefix the
/// vendored cut carries, pinned in source so a re-vendor that DROPS one fails
/// the build instead of moving a count.
///
/// Direction matters and is asymmetric on purpose:
///
/// - **Additions are cheap.** A new CC family appears in the manifest, this list
///   does not mention it, and nothing fails. Bump it when convenient.
/// - **Removals are the incident.** CC's first R2 regeneration silently lost
///   four families to a prose paragraph inserted mid-markdown-table; 106 + 3 − 4
///   = 105 and the only signal was an arithmetic discrepancy. A prefix that
///   disappears from the manifest fails
///   [`tests::no_vendored_family_silently_disappears`] BY NAME, and clearing it
///   means moving the line to [`RETIRED_FAMILIES`] with a reason.
///
/// Yes, this is a second list beside the manifest — deliberately. The
/// disagreement between them IS the alarm; that is the opposite of the
/// two-lists-that-quietly-disagree class (#541, #532, #588), where neither list
/// could see the other.
pub const VENDORED_FAMILY_PREFIXES: &[&str] = &[
    "accord:*",
    "activity_tier:{period}",
    "age_assurance:{level}:{band}:{version}",
    "age_self_declared:{band}:{version}",
    "agent_files:{kind}:{platform_or_target}",
    "approach:{goal_id}",
    "attestation:agent_integrity",
    "attestation:hardware_rooted",
    "attestation:license_validity",
    "attestation:registry_consensus",
    "attestation:self_verify",
    "audit_chain:hash_continuity",
    "autonomy:{aspect}",
    "benchmark:he300:{category}:{version}",
    "beneficence:{aspect}",
    "bond_posted:{currency}",
    "build:registered:{target}",
    "capacity:composite",
    "capacity:core_identity",
    "capacity:incompleteness_awareness",
    "capacity:integrity",
    "capacity:resilience",
    "capacity:sustained_coherence",
    "capacity_assurance:{level}:{domain}:{band}:{version}",
    "cert_validity:{authority}",
    "coherence_standing:{cohort}",
    "commitment_fulfillment:{prior_contribution_id}",
    "config:{scope}",
    "conscience:coherence",
    "conscience:entropy",
    "conscience:epistemic_humility",
    "conscience:optimization_veto",
    "consent:{kind}",
    "content_class:{class}",
    "content_rating:{scheme}:{rating}",
    "corpus_health:n_eff_measurable",
    "credits:{domain}:{language}:substrate_building",
    "credits:{domain}:{language}:{subject}",
    "cw_class:{class}",
    "delivery:{class}",
    "delivery_receipt:{stream_id}",
    "detection:conscience_override_rate",
    "detection:correlated_action:{axis}",
    "detection:cross_agent_divergence",
    "detection:distributive:access:{resource_type}",
    "detection:hash_chain_integrity",
    "detection:intra_agent_consistency",
    "detection:temporal_drift",
    "dma:csdma:*",
    "dma:dsdma:{domain}:*",
    "dma:idma:*",
    "dma:pdma:*",
    "duty:{kind}",
    "expertise:{domain}:{language}",
    "federation_directory:replication_lag",
    "fidelity:explainability_sla:{tier}",
    "fidelity:{aspect}",
    "goal:{scale}",
    "hard_case:{kind}",
    "hardware_custody:{platform}",
    "health:liveness:{version}",
    "holds_bytes:sha256:{prefix}",
    "identity_continuity:relational_anchor",
    "integrity:{aspect}",
    "judge_model:verdict:{model_id}",
    "justice:{aspect}",
    "key_boundary:{scope}",
    "licensure:{authority_id}",
    "locality:decision:{scale}",
    "manifold_conformity:{cohort}",
    "mesh_config:{key}",
    "method:{approach_id}:{substrate_rung}",
    "moderation:{allegation_type}",
    "moderation_track_record:{community_key_id}",
    "multilateral_participation:{forum}:{kind}",
    "need:{domain}:{kind}",
    "non_maleficence:{aspect}",
    "objection:{state}",
    "ownership:{relation}:{target_kind}:{version}",
    "partner_role:{role}",
    "peer_reachability:{network}",
    "progress_measure:{method_id}",
    "prohibited:{category}",
    "provenance:build_manifest:{target}",
    "provenance:build_manifest:{target}:locale:{lang_code}",
    "provenance:skill_import:{source}",
    "provenance:slsa:{level}",
    "quarantine:{state}",
    "ratchet:flag:coordinated_voting_cluster",
    "ratchet:flag:counter_rii:{layer}",
    "ratchet:flag:density_anomaly",
    "ratchet:flag:expertise_attestation_anomaly",
    "ratchet:flag:harassment_pattern",
    "ratchet:flag:out_of_distribution_voting",
    "reconsideration:{grounds}",
    "regime:{artifact}:{version}",
    "revocation:{entity_type}:{reason}",
    "rollback_detected:{revision_field}",
    "seed_holder_voting_alignment:{cell}",
    "session:{kind}",
    "slashing:{outcome}",
    "system:*",
    "testimonial_witness:{kind}",
    "trace:{form}:{version}",
    "trace_summary:{kind}",
    "transparency_log:consistency",
    "transparency_log:cosigned:{tree_size}",
    "transparency_log:inclusion",
    "transport:{kind}",
    "trust:{job}:{version}",
    "truth_grounding:{subject}",
    "vote:{contribution_id}",
    "wa_adjudication:{state}",
    "watchlist:{id}",
    "weighted_aggregate:{contribution_id}",
    "witness_diversity:{contribution_id}",
];

/// Families CC has **deliberately retired** — present in an earlier vendored cut,
/// intentionally absent from this one. Empty as of the rc3 vendor: no CC family
/// has ever been retired, and every disappearance so far has been a generator
/// accident.
///
/// The escape hatch for [`VENDORED_FAMILY_PREFIXES`]: moving a line here is how
/// a reviewer says "this removal is intended", in a diff someone must read.
pub const RETIRED_FAMILIES: &[&str] = &[];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vendored_manifest_matches_the_pinned_cc_cut() {
        // Drift gate: the compiled-in manifest must be the exact cut the consts
        // pin. Re-vendoring after a CC change forces a deliberate const bump.
        let raw: RawManifest = serde_json::from_str(REGISTRY_JSON).unwrap();
        assert_eq!(raw.meta.cc_version, VENDORED_CC_VERSION, "cc_version drift");
        assert_eq!(
            raw.meta.source_sha256, VENDORED_SOURCE_SHA256,
            "source hash drift — CC part_3 changed; regenerate + re-vendor"
        );
        assert_eq!(
            raw.meta.n_families, VENDORED_N_FAMILIES,
            "family count drift"
        );
        assert_eq!(
            raw.families.len(),
            VENDORED_N_FAMILIES,
            "families[] length != _meta.n_families"
        );
    }

    #[test]
    fn registry_parses_and_is_nonempty() {
        let reg = entries();
        assert_eq!(reg.len(), VENDORED_N_FAMILIES);
        // sorted longest-match_prefix-first
        for w in reg.windows(2) {
            assert!(w[0].match_prefix.len() >= w[1].match_prefix.len());
        }
    }

    // ── (CIRISPersist#590) — the vendor-drift witnesses ──────────

    /// **The equality that caught CC's own incident.** `_meta.n_families` is a
    /// number the generator writes; `families[]` is what it actually emitted.
    /// The four-family drop showed up as nothing else — the two disagreeing is
    /// the whole signal, and it was nearly reconciled away by hand. Assert it,
    /// and assert no prefix appears twice (a duplicate would let the count
    /// match while a distinct family was lost).
    #[test]
    fn manifest_row_count_equals_meta_and_carries_no_duplicates() {
        use std::collections::BTreeSet;
        let raw: RawManifest = serde_json::from_str(REGISTRY_JSON).unwrap();
        assert_eq!(
            raw.families.len(),
            raw.meta.n_families,
            "MANIFEST SELF-CONTRADICTION (CIRISPersist#590): families[] has {} rows but \
             _meta.n_families says {}. This exact discrepancy — and nothing else — was the only \
             signal when CC's generator silently dropped four families to a prose paragraph \
             inserted mid-table. Do not reconcile the number; find the missing rows.",
            raw.families.len(),
            raw.meta.n_families
        );
        let mut seen: BTreeSet<&str> = BTreeSet::new();
        for f in &raw.families {
            assert!(
                seen.insert(f.prefix.as_str()),
                "duplicate family prefix {:?} — a duplicate lets _meta.n_families balance while a \
                 distinct family is missing",
                f.prefix
            );
        }
    }

    /// **The removal direction.** Every prefix the pinned
    /// [`VENDORED_FAMILY_PREFIXES`] list carries must still be in the manifest.
    /// Additions are free; a disappearance fails BY NAME and is cleared only by
    /// moving the line to [`RETIRED_FAMILIES`] — a diff a reviewer has to read.
    #[test]
    fn no_vendored_family_silently_disappears() {
        use std::collections::BTreeSet;
        let raw: RawManifest = serde_json::from_str(REGISTRY_JSON).unwrap();
        let live: BTreeSet<&str> = raw.families.iter().map(|f| f.prefix.as_str()).collect();
        let retired: BTreeSet<&str> = RETIRED_FAMILIES.iter().copied().collect();
        let missing: Vec<&&str> = VENDORED_FAMILY_PREFIXES
            .iter()
            .filter(|p| !live.contains(*p) && !retired.contains(*p))
            .collect();
        assert!(
            missing.is_empty(),
            "VENDOR DRIFT — REMOVAL (CIRISPersist#590): {} pinned famil(ies) vanished from the \
             re-vendored manifest: {missing:?}. A family that disappears takes its reserved rule \
             with it, so CC-reserved traffic starts admitting under the ProducerSteward fallback \
             (CC 3.1.7 R2) and R2(b) starts refusing rows it should not. If the removal is \
             INTENDED, move each line from VENDORED_FAMILY_PREFIXES to RETIRED_FAMILIES with a CC \
             reference. If it is not, the generator lost them — CC's first R2 regeneration lost \
             four to a prose paragraph inserted mid-markdown-table.",
            missing.len()
        );
        // The pin must not itself rot: a family in BOTH lists is a
        // contradiction ("retired" and "still expected" at once).
        for p in RETIRED_FAMILIES {
            assert!(
                !VENDORED_FAMILY_PREFIXES.contains(p),
                "{p:?} is in RETIRED_FAMILIES and VENDORED_FAMILY_PREFIXES at once"
            );
            assert!(
                !live.contains(p),
                "{p:?} is listed RETIRED but the manifest still carries it — un-retire it"
            );
        }
    }

    /// The pinned list is a list of REAL prefixes and is kept in sync in the
    /// cheap direction too: it should describe the cut it ships with, so an
    /// out-of-date pin (many additions un-recorded) is visible at a glance
    /// rather than accumulating until the removal gate is meaningless.
    #[test]
    fn pinned_family_list_matches_this_vendored_cut() {
        use std::collections::BTreeSet;
        let raw: RawManifest = serde_json::from_str(REGISTRY_JSON).unwrap();
        let live: BTreeSet<&str> = raw.families.iter().map(|f| f.prefix.as_str()).collect();
        let pinned: BTreeSet<&str> = VENDORED_FAMILY_PREFIXES.iter().copied().collect();
        assert_eq!(
            pinned.len(),
            VENDORED_FAMILY_PREFIXES.len(),
            "VENDORED_FAMILY_PREFIXES contains a duplicate"
        );
        let unpinned: Vec<&&str> = live.difference(&pinned).collect();
        assert!(
            unpinned.is_empty(),
            "the vendored manifest carries famil(ies) the pin does not list: {unpinned:?} — add \
             them to VENDORED_FAMILY_PREFIXES so the removal gate keeps covering them"
        );
    }

    /// **A transcription that was uncheckable is now checked, and it checks.**
    ///
    /// [`PRIVATE_USE_FAMILY_STEM`](crate::federation::admission::PRIVATE_USE_FAMILY_STEM)
    /// shipped as a hand-transcription of CC 3.1.7 R2's Private Use prose, with
    /// its own doc naming the remedy: a `_meta` key in the generated manifest.
    /// The rc3 cut carries that key. So the const and the artifact are bound
    /// here, in the direction that matters — if CC moves the range, this fails
    /// rather than persist quietly refusing federation traffic on a stem CC no
    /// longer reserves, or quietly admitting on one it newly does.
    ///
    /// Same shape as `family_rules::RULES_NOT_ON_THE_ROW` and
    /// `quarantine::NAMESPACE_FAMILY`'s measured count: a claim persist repeats
    /// about CC should be one CC's own artifact can contradict.
    #[test]
    fn the_private_use_range_is_machine_readable_now() {
        let from_manifest = vendored_private_use_prefix().expect(
            "the rc3 cut carries `_meta.private_use_prefix`. `None` here means the manifest was \
             re-vendored BACKWARDS to a cut generated before CC shipped the field — check the \
             source hash before assuming CC removed it.",
        );
        assert_eq!(
            from_manifest,
            crate::federation::admission::PRIVATE_USE_FAMILY_STEM,
            "the hand-transcribed Private Use stem and CC's own machine-readable range disagree. \
             CC is the source of truth: update PRIVATE_USE_FAMILY_STEM, and re-read every \
             `x_private:` site with it — the federation-tier ban, the promotion gate, and \
             `regime.rs`'s reasoning about why the range was rejected as a home for `regime:*`."
        );
    }

    /// `family_stem` is the R2 granularity: up to and including the first `:`.
    #[test]
    fn family_stem_cuts_at_the_first_colon() {
        assert_eq!(family_stem("objection:raised:v1"), "objection:");
        assert_eq!(family_stem("objection:{state}"), "objection:");
        assert_eq!(family_stem("accord:*"), "accord:");
        assert_eq!(family_stem("scores"), "scores");
        assert_eq!(family_stem(""), "");
        assert_eq!(
            family_stem("detection:distributive:access:x:v1"),
            "detection:"
        );
    }

    /// R2's registration predicate over the real manifest — including the three
    /// families persist itself minted, which is the whole reason #590 exists.
    #[test]
    fn is_family_registered_answers_from_the_manifest() {
        for dim in [
            "objection:raised:v1",
            "quarantine:withheld:v1",
            "wa_adjudication:petition:v1",
            "accord:invoke:halt",
            "capacity:core_identity:v1",
            // open vocabulary WITHIN a registered family stays registered —
            // this is the traffic R2 explicitly preserves.
            "credits:rust:en:someone",
            "detection:emergent_pattern:novel_signal:v1",
        ] {
            assert!(is_family_registered(dim), "{dim} must be registered");
        }
        for dim in ["totally:made:up:v1", "", "scores"] {
            assert!(!is_family_registered(dim), "{dim} must NOT be registered");
        }
    }

    /// **The redundancy `RawFamily` bets on.** Its comment says the manifest's
    /// `reserved` bool "is redundant with `reserved_rule` presence", and on that
    /// basis serde **ignores `reserved` entirely**. If CC ever ships
    /// `reserved: true` with no `reserved_rule`, persist reads that family as
    /// OPEN while the manifest asserts it is reserved — a reservation dropped on
    /// the floor by a parser doing what its comment promised.
    ///
    /// Perfectly correlated on this cut, zero rows in either direction. The bet
    /// is sound; this is what makes it a checked bet rather than an assumption.
    #[test]
    fn reserved_bool_and_reserved_rule_presence_are_redundant() {
        let raw: RawManifest = serde_json::from_str(REGISTRY_JSON).unwrap();
        let root: serde_json::Value = serde_json::from_str(REGISTRY_JSON).unwrap();
        let rows = root["families"].as_array().expect("families array");
        assert_eq!(rows.len(), raw.families.len());
        let mut asserted_but_unruled: Vec<&str> = Vec::new();
        let mut ruled_but_unasserted: Vec<&str> = Vec::new();
        for row in rows {
            let prefix = row["prefix"].as_str().expect("prefix");
            let flag = row
                .get("reserved")
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            let has_rule = row.get("reserved_rule").is_some_and(|v| !v.is_null());
            if flag && !has_rule {
                asserted_but_unruled.push(prefix);
            }
            if has_rule && !flag {
                ruled_but_unasserted.push(prefix);
            }
        }
        assert!(
            asserted_but_unruled.is_empty(),
            "{asserted_but_unruled:?} carry `reserved: true` with NO `reserved_rule`. serde \
             ignores the bool, so `authority_for` reports these families OPEN while the manifest \
             says they are reserved — a reservation silently dropped at the parser. Either CC \
             must land the rule, or RawFamily must stop ignoring the bool."
        );
        assert!(
            ruled_but_unasserted.is_empty(),
            "{ruled_but_unasserted:?} carry a `reserved_rule` but `reserved: false` — the \
             manifest contradicts itself about whether the family is reserved"
        );
    }

    /// **The prose-only emitter rules, MEASURED** (CIRISPersist#571).
    ///
    /// Several rc3 rows state an emitter restriction in `description` while
    /// generating no `reserved_rule`, so `authority_for` reports the family
    /// open and no substrate can enforce what CC wrote. `quarantine.rs` used to
    /// call itself *"the only one of 109"*; the re-vendor made that four of 114
    /// while the sentence still read as freshly checked — a claim rotting in the
    /// direction that looks verified, which is the class
    /// `manifest_absence_claims_still_hold` exists for.
    ///
    /// Both numbers are recomputed from the vendored bytes here, so the doc
    /// comments that cite them cannot drift without failing the build.
    ///
    /// The finding is NOT "four unlucky rows": every one of them is in CC
    /// 3.1.9.2, and **no** family in that section carries a rule. CC's generator
    /// sources reserved rules from CC 3.4 plus a `Reserved?` table column, and
    /// 3.1.9.2's table has neither — so the governance-steering tier is
    /// structurally unable to carry an enforceable emitter rule. That is the CC
    /// ask, and this test states it as a measurement rather than a belief.
    ///
    /// Deliberately a keyword scan over prose — which persist must NEVER do for
    /// enforcement (CC 3.1.7 R2 forbids exactly that, and nothing on any
    /// admission path reads `description`). Here it is pointed at persist's own
    /// documentation, and the assertion is only ever "re-read the rows", never
    /// "admit or refuse this traffic".
    #[test]
    fn the_prose_only_emitter_rules_are_still_confined_to_cc_3_1_9_2() {
        let prose_only: Vec<&NamespaceEntry> = entries()
            .iter()
            .filter(|e| e.authority.reserved.is_none())
            .filter(|e| {
                let d = e.description.to_lowercase();
                d.contains("-emitted") || d.contains("emitter") || d.contains("-only")
            })
            .collect();

        let names: Vec<&str> = prose_only.iter().map(|e| e.prefix.as_str()).collect();
        assert_eq!(
            prose_only.len(),
            4,
            "the prose-only emitter-rule population moved (now {}): {names:?}. If CC has landed a \
             rule, the count DROPS — delete the corresponding pin and write the gate. If a new row \
             arrived stating a rule nothing can parse, it joins the CC ask. Either way the doc \
             comments in quarantine.rs and regime.rs that cite this number must be re-read.",
            prose_only.len()
        );
        for e in &prose_only {
            assert_eq!(
                e.cc_section, "3.1.9.2",
                "{} states an unenforceable emitter rule from OUTSIDE CC 3.1.9.2 — the CC ask is \
                 currently scoped to that section's table shape, and this widens it",
                e.prefix
            );
        }

        // The structural claim the ask rests on: it is the SECTION, not the rows.
        let section: Vec<&NamespaceEntry> = entries()
            .iter()
            .filter(|e| e.cc_section == "3.1.9.2")
            .collect();
        assert_eq!(
            section.len(),
            12,
            "CC 3.1.9.2's family count moved — re-check the generator ask"
        );
        assert!(
            section.iter().all(|e| e.authority.reserved.is_none()),
            "a CC 3.1.9.2 family now carries a machine-readable rule — the section's table has \
             gained a `Reserved?` column or the generator a predicate. That is the fix this ask \
             wanted: re-check every prose-only pin."
        );
    }

    /// A `reserved_rule` with a null `cc_ref` (rc3's `trust:{job}:{version}`)
    /// parses, and resolves to the family's own catalogue section rather than
    /// an empty string that reads like a present-but-blank citation.
    #[test]
    fn null_cc_ref_resolves_to_the_catalogue_section() {
        let a = authority_for("trust:charter:v1");
        let r = a.reserved.expect("trust:{job} carries a reserved rule");
        assert!(!r.cc_ref.is_empty(), "cc_ref must never be an empty string");
        assert_eq!(r.cc_ref, "CC 3.1.1");
    }

    #[test]
    fn build_manifest_is_accord_co_scrub_like_canonical() {
        // The chicken/egg closer: an infra build-manifest dimension resolves to
        // the SAME accord-co-scrub authority as a canonical record.
        let a = authority_for("provenance:build_manifest:agent-3.2.1");
        assert_eq!(a.class, AuthorityClass::AccordCoScrub);
        assert!(a.class.is_trust_root());
    }

    #[test]
    fn substrate_self_report_prefixes_resolve_substrate_self() {
        for dim in [
            "audit_chain:hash_continuity",
            "corpus_health:n_eff_measurable",
            "federation_directory:replication_lag",
            "transport:ip",
            "delivery:mandatory",
        ] {
            let a = authority_for(dim);
            assert_eq!(
                a.class,
                AuthorityClass::SubstrateSelf,
                "{dim} must be substrate-self"
            );
            assert_eq!(a.reserved.as_ref().unwrap().cc_ref, "CC 3.4.3");
        }
    }

    #[test]
    fn accord_prefix_is_reserved_producer() {
        let a = authority_for("accord:invoke:halt");
        assert_eq!(a.class, AuthorityClass::ProducerSteward);
        let r = a.reserved.expect("accord:* carries a reserved rule");
        assert_eq!(r.cc_ref, "CC 3.4.1");
        assert_eq!(r.rule, "accord_holder-only");
    }

    #[test]
    fn longest_prefix_wins() {
        // `provenance:build_manifest:` must beat a shorter `provenance:` match
        // if both are present — the sort guarantees the specific hit.
        let e = lookup("provenance:build_manifest:x").unwrap();
        assert!(e.match_prefix.starts_with("provenance:build_manifest"));
    }

    #[test]
    fn unknown_dimension_defaults_to_producer_no_reserved() {
        let a = authority_for("totally:made:up:dimension");
        assert_eq!(a.class, AuthorityClass::ProducerSteward);
        assert!(a.reserved.is_none());
        assert!(lookup("totally:made:up:dimension").is_none());
    }

    /// v38.0.0 (CIRISPersist#724) — **nothing could notice an unread
    /// manifest column.** The `polarity` column shipped in the vendored
    /// registry and sat unread for five weeks across three vendorings,
    /// because `RawFamily` deserializes a SUBSET of the row and serde
    /// silently drops the rest (deliberately — `deny_unknown_fields` would
    /// make every future CC column addition a hard break, and the
    /// optional-column-over-panic rationale above stands). This closes the
    /// noticing gap without closing the compatibility door: every column
    /// the artifact actually carries must be deserialized by [`RawFamily`],
    /// read elsewhere (named below with its reader), or deliberately inert
    /// (named below with WHY). A new CC column reds this test until a human
    /// decides which it is — which is the entire ask of #724.
    #[test]
    fn every_manifest_family_column_has_a_reader_724() {
        // Columns RawFamily deserializes — a hand pin; if RawFamily gains a
        // field this list is one line away and the test names the file.
        const DESERIALIZED: &[&str] = &[
            "prefix",
            "owning_component",
            "owning_repo",
            "cc_section",
            "description",
            "reserved_rule",
        ];
        // Columns read OUTSIDE the shared type, each naming its reader.
        const READ_ELSEWHERE: &[(&str, &str)] = &[(
            "polarity",
            "scores_read_audit.rs#vendored_family_polarities (local parse, documented \
             at that site) + the #724 cross-manifest agreement gate",
        )];
        // Columns deliberately inert, each naming WHY — the subtractive
        // manifest: a rationale under 40 chars is a shrug, not a reason.
        const DELIBERATELY_UNREAD: &[(&str, &str)] = &[(
            "reserved",
            "redundant with reserved_rule presence by construction; the redundancy itself \
             is what RawFamily's field comment pins, and reading both would mint a second \
             spelling of one fact",
        )];

        for (_, why) in DELIBERATELY_UNREAD {
            assert!(
                why.len() > 40,
                "a rationale under 40 chars is a shrug: {why:?}"
            );
        }

        let manifest: serde_json::Value = serde_json::from_str(REGISTRY_JSON).unwrap();
        let mut carried: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
        for fam in manifest["families"].as_array().unwrap() {
            for k in fam.as_object().unwrap().keys() {
                carried.insert(k.as_str());
            }
        }
        assert!(carried.len() >= 6, "vacuous gate: {carried:?}");

        let accounted: std::collections::BTreeSet<&str> = DESERIALIZED
            .iter()
            .copied()
            .chain(READ_ELSEWHERE.iter().map(|(c, _)| *c))
            .chain(DELIBERATELY_UNREAD.iter().map(|(c, _)| *c))
            .collect();
        let unaccounted: Vec<&&str> = carried
            .iter()
            .filter(|c| !accounted.contains(**c))
            .collect();
        assert!(
            unaccounted.is_empty(),
            "the vendored registry carries column(s) nothing reads and nobody has declared \
             inert: {unaccounted:?}. Read it, name its reader, or record why it is inert — \
             an unread manifest column is a claim the substrate silently ignores (#724)."
        );
        // Both directions: an accounted column the artifact no longer
        // carries is a stale pin.
        let stale: Vec<&&str> = accounted
            .iter()
            .filter(|c| !carried.contains(**c))
            .collect();
        assert!(stale.is_empty(), "stale column pin(s): {stale:?}");
    }
}
