//! **CIRISPersist#425 — the vendored CC-3.1 namespace registry + `authority_for`.**
//!
//! The dimension-namespace catalog (CC 3.1 `part_3_the_namespace.md`) rendered
//! machine-readable and vendored as [`namespace_registry.json`]. **CC is the
//! single source of truth**: the file is GENERATED by the Constitution's
//! `tools/build_cc_namespace.py`, never hand-authored here. Persist is a
//! distribution channel so downstream (CIRISEdge#425 replication engine, the
//! manifest verifier) resolves `authority_for(dimension)` from data rather than
//! re-deriving it from CC prose.
//!
//! **Drift control.** [`VENDORED_CC_VERSION`] / [`VENDORED_SOURCE_SHA256`] /
//! [`VENDORED_N_FAMILIES`] pin the exact CC cut this copy was generated from; a
//! test asserts the vendored file's `_meta` matches. Re-vendoring after a CC
//! change is therefore a deliberate, reviewable bump of all three consts — the
//! copy can never silently drift from the Constitution it mirrors.
//!
//! [`namespace_registry.json`]: <the vendored file in this directory>

use super::{Authority, AuthorityClass, ReservedRule};
use std::sync::OnceLock;

/// The vendored copy of the Constitution manifest, compiled in.
const REGISTRY_JSON: &str = include_str!("namespace_registry.json");

/// The CC version [`REGISTRY_JSON`] was generated from. Bump in lockstep when
/// re-vendoring (the drift gate asserts the file's `_meta.cc_version` matches).
pub const VENDORED_CC_VERSION: &str = "1.0-rc2";
/// SHA-256 of the CC `part_3_the_namespace.md` bytes the manifest was generated
/// from (the manifest's `_meta.source_sha256`). Pins the exact source cut.
pub const VENDORED_SOURCE_SHA256: &str =
    "ade64edccce493e99f2617d236b1dffd6b99e2dfae91a9a4c012c9f4dfd6c64b";
/// The number of prefix families in this vendored cut (the enumerated leaf
/// count; CC 3.1's "83" summary is stale — see CIRISConstitution#30).
pub const VENDORED_N_FAMILIES: usize = 95;

/// One resolved namespace family — a CC 3.1 prefix, its owning component, and
/// the [`Authority`] its reserved-prefix rule (CC 3.4) demands.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NamespaceEntry {
    /// The catalogued family prefix, verbatim from CC 3.1 (e.g.
    /// `"provenance:build_manifest:{target}"`, `"accord:*"`,
    /// `"audit_chain:hash_continuity"`).
    pub prefix: String,
    /// The literal prefix a concrete `dimension` is matched against — `prefix`
    /// truncated at its first `{` parameter or `*` wildcard (e.g.
    /// `"provenance:build_manifest:"`, `"accord:"`). Longest match wins in
    /// [`authority_for`].
    pub match_prefix: String,
    /// The owning component slug (CC 3.1.N heading), e.g. `"persist"`,
    /// `"attestation"`, `"registry"`.
    pub owning_component: String,
    /// The steward repo, when the manifest records one.
    pub owning_repo: Option<String>,
    /// The CC section the family is catalogued in (e.g. `"3.1.2"`).
    pub cc_section: String,
    /// The resolved emit authority (class + any CC 3.4 reserved rule).
    pub authority: Authority,
}

// ── raw serde shapes matching the generated manifest ────────────────────

#[derive(serde::Deserialize)]
struct RawManifest {
    #[serde(rename = "_meta")]
    meta: RawMeta,
    families: Vec<RawFamily>,
}

#[derive(serde::Deserialize)]
struct RawMeta {
    cc_version: String,
    source_sha256: String,
    n_families: usize,
}

#[derive(serde::Deserialize)]
struct RawFamily {
    prefix: String,
    owning_component: String,
    #[serde(default)]
    owning_repo: Option<String>,
    cc_section: String,
    // NOTE: the manifest's `reserved` bool is redundant with `reserved_rule`
    // presence (which carries the CC 3.4 specifics) — serde ignores it.
    #[serde(default)]
    reserved_rule: Option<RawReservedRule>,
}

#[derive(serde::Deserialize)]
struct RawReservedRule {
    rule: String,
    cc_ref: String,
}

/// The literal stem of a family prefix — everything before the first `{`
/// parameter or `*` wildcard. `"accord:*"` → `"accord:"`;
/// `"provenance:build_manifest:{target}"` → `"provenance:build_manifest:"`;
/// `"audit_chain:hash_continuity"` → itself.
fn match_prefix_of(prefix: &str) -> String {
    let cut = prefix.find(['{', '*']).unwrap_or(prefix.len());
    prefix[..cut].to_string()
}

/// Derive the emit [`AuthorityClass`] for a family from its catalogued
/// reserved-emit rule, layering persist's own trust-root knowledge on top.
///
/// - `provenance:build_manifest:*` → [`AccordCoScrub`](AuthorityClass::AccordCoScrub):
///   a build manifest is accord-co-scrubbed (the `infra:attest` gate), identical
///   authority to a canonical seed — the property that closes the chicken/egg.
/// - `substrate-self-report` (CC 3.4.3) → [`SubstrateSelf`](AuthorityClass::SubstrateSelf).
/// - any other reserved rule (accord_holder-only, detector-only, witness-emitter,
///   co-stewarded, no-self-emit) or an unreserved dimension →
///   [`ProducerSteward`](AuthorityClass::ProducerSteward); the CC 3.4 specifics
///   ride in [`Authority::reserved`].
///
/// NOTE: no CC 3.1 *dimension* prefix resolves to
/// [`SelfIdentity`](AuthorityClass::SelfIdentity) — that authority governs the
/// CC 3.3 *subject-kind* objects (key records, identity occurrences, transport
/// bindings), which the edge engine authorizes structurally (via the object
/// kind), not through this dimension registry.
fn class_for(match_prefix: &str, rule: Option<&str>) -> AuthorityClass {
    if match_prefix.starts_with("provenance:build_manifest") {
        return AuthorityClass::AccordCoScrub;
    }
    match rule {
        Some("substrate-self-report") => AuthorityClass::SubstrateSelf,
        _ => AuthorityClass::ProducerSteward,
    }
}

fn parse_manifest() -> Vec<NamespaceEntry> {
    let raw: RawManifest =
        serde_json::from_str(REGISTRY_JSON).expect("vendored namespace_registry.json is valid");
    // Drift invariants (also enforced as a hard test in this module): the
    // vendored cut must be the one the consts pin, and be self-consistent.
    debug_assert_eq!(raw.meta.cc_version, VENDORED_CC_VERSION, "cc_version drift");
    debug_assert_eq!(
        raw.meta.source_sha256, VENDORED_SOURCE_SHA256,
        "CC part_3 source hash drift — regenerate + re-vendor"
    );
    assert_eq!(
        raw.families.len(),
        raw.meta.n_families,
        "manifest self-consistency: families[] != _meta.n_families"
    );
    let mut entries: Vec<NamespaceEntry> = raw
        .families
        .into_iter()
        .map(|f| {
            let match_prefix = match_prefix_of(&f.prefix);
            let reserved = f.reserved_rule.map(|r| ReservedRule {
                rule: r.rule,
                cc_ref: r.cc_ref,
            });
            let class = class_for(&match_prefix, reserved.as_ref().map(|r| r.rule.as_str()));
            NamespaceEntry {
                prefix: f.prefix,
                match_prefix,
                owning_component: f.owning_component,
                owning_repo: f.owning_repo,
                cc_section: f.cc_section,
                authority: Authority { class, reserved },
            }
        })
        .collect();
    // Longest match_prefix first so `authority_for`'s first hit is the most
    // specific (e.g. `provenance:build_manifest:` beats a hypothetical
    // `provenance:` before it).
    entries.sort_by(|a, b| {
        b.match_prefix
            .len()
            .cmp(&a.match_prefix.len())
            .then_with(|| a.prefix.cmp(&b.prefix))
    });
    entries
}

fn registry() -> &'static [NamespaceEntry] {
    static REGISTRY: OnceLock<Vec<NamespaceEntry>> = OnceLock::new();
    REGISTRY.get_or_init(parse_manifest)
}

/// The full vendored namespace registry (every CC 3.1 prefix family), sorted
/// most-specific-`match_prefix`-first. Edge enumerates this to build its
/// dimension→policy table once at boot.
pub fn entries() -> &'static [NamespaceEntry] {
    registry()
}

/// The [`NamespaceEntry`] whose `match_prefix` is the **longest prefix** of
/// `dimension`, or `None` if `dimension` is outside the CC namespace. The
/// registry is pre-sorted longest-first, so this returns the most specific
/// match.
pub fn lookup(dimension: &str) -> Option<&'static NamespaceEntry> {
    registry()
        .iter()
        .find(|e| dimension.starts_with(&e.match_prefix))
}

/// **`authority_for(dimension)`** — the emit authority the `dimension`'s
/// reserved-prefix rule (CC 3.4) demands, resolved from the vendored CC-3.1
/// registry. A `dimension` outside the namespace defaults to
/// [`ProducerSteward`](AuthorityClass::ProducerSteward) with no reserved rule (a
/// signed producer claim; the write-path reserved-prefix admission gate is the
/// enforcement point, not this classifier). Infra prefixes
/// (`provenance:build_manifest:*`) resolve to
/// [`AccordCoScrub`](AuthorityClass::AccordCoScrub) — identical to a canonical
/// record, closing the chicken/egg.
pub fn authority_for(dimension: &str) -> Authority {
    lookup(dimension)
        .map(|e| e.authority.clone())
        .unwrap_or(Authority {
            class: AuthorityClass::ProducerSteward,
            reserved: None,
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vendored_manifest_matches_the_pinned_cc_cut() {
        // Drift gate: the compiled-in manifest must be the exact cut the consts
        // pin. Re-vendoring after a CC change forces a deliberate const bump.
        let raw: RawManifest = serde_json::from_str(REGISTRY_JSON).unwrap();
        assert_eq!(raw.meta.cc_version, VENDORED_CC_VERSION, "cc_version drift");
        assert_eq!(
            raw.meta.source_sha256, VENDORED_SOURCE_SHA256,
            "source hash drift — CC part_3 changed; regenerate + re-vendor"
        );
        assert_eq!(
            raw.meta.n_families, VENDORED_N_FAMILIES,
            "family count drift"
        );
        assert_eq!(
            raw.families.len(),
            VENDORED_N_FAMILIES,
            "families[] length != _meta.n_families"
        );
    }

    #[test]
    fn registry_parses_and_is_nonempty() {
        let reg = entries();
        assert_eq!(reg.len(), VENDORED_N_FAMILIES);
        // sorted longest-match_prefix-first
        for w in reg.windows(2) {
            assert!(w[0].match_prefix.len() >= w[1].match_prefix.len());
        }
    }

    #[test]
    fn build_manifest_is_accord_co_scrub_like_canonical() {
        // The chicken/egg closer: an infra build-manifest dimension resolves to
        // the SAME accord-co-scrub authority as a canonical record.
        let a = authority_for("provenance:build_manifest:agent-3.2.1");
        assert_eq!(a.class, AuthorityClass::AccordCoScrub);
        assert!(a.class.is_trust_root());
    }

    #[test]
    fn substrate_self_report_prefixes_resolve_substrate_self() {
        for dim in [
            "audit_chain:hash_continuity",
            "corpus_health:n_eff_measurable",
            "federation_directory:replication_lag",
            "transport:ip",
            "delivery:mandatory",
        ] {
            let a = authority_for(dim);
            assert_eq!(
                a.class,
                AuthorityClass::SubstrateSelf,
                "{dim} must be substrate-self"
            );
            assert_eq!(a.reserved.as_ref().unwrap().cc_ref, "CC 3.4.3");
        }
    }

    #[test]
    fn accord_prefix_is_reserved_producer() {
        let a = authority_for("accord:invoke:halt");
        assert_eq!(a.class, AuthorityClass::ProducerSteward);
        let r = a.reserved.expect("accord:* carries a reserved rule");
        assert_eq!(r.cc_ref, "CC 3.4.1");
        assert_eq!(r.rule, "accord_holder-only");
    }

    #[test]
    fn longest_prefix_wins() {
        // `provenance:build_manifest:` must beat a shorter `provenance:` match
        // if both are present — the sort guarantees the specific hit.
        let e = lookup("provenance:build_manifest:x").unwrap();
        assert!(e.match_prefix.starts_with("provenance:build_manifest"));
    }

    #[test]
    fn unknown_dimension_defaults_to_producer_no_reserved() {
        let a = authority_for("totally:made:up:dimension");
        assert_eq!(a.class, AuthorityClass::ProducerSteward);
        assert!(a.reserved.is_none());
        assert!(lookup("totally:made:up:dimension").is_none());
    }
}
