//! **CIRISPersist#425 — the vendored CC-3.1 namespace registry + `authority_for`.**
//!
//! The dimension-namespace catalog (CC 3.1 `part_3_the_namespace.md`) rendered
//! machine-readable and vendored as [`namespace_registry.json`]. **CC is the
//! single source of truth**: the file is GENERATED by the Constitution's
//! `tools/build_cc_namespace.py`, never hand-authored here. Persist is a
//! distribution channel so downstream (CIRISEdge#425 replication engine, the
//! manifest verifier) resolves `authority_for(dimension)` from data rather than
//! re-deriving it from CC prose.
//!
//! **Drift control.** [`VENDORED_CC_VERSION`] / [`VENDORED_SOURCE_SHA256`] /
//! [`VENDORED_N_FAMILIES`] pin the exact CC cut this copy was generated from; a
//! test asserts the vendored file's `_meta` matches. Re-vendoring after a CC
//! change is therefore a deliberate, reviewable bump of all three consts — the
//! copy can never silently drift from the Constitution it mirrors.
//!
//! **The removal direction is the dangerous one** (CIRISPersist#590).
//! A count bump plus a source-hash bump is the signature of *any* re-vendor —
//! including one that silently DROPS families. CC's own first CC-3.1.7-R2
//! regeneration lost four (`judge_model:verdict`, `health:liveness`,
//! `seed_holder_voting_alignment`, `watchlist`) to a prose paragraph inserted
//! mid-table (a blank line plus prose terminates a markdown table), and the
//! only signal was a count discrepancy that was very nearly reconciled away.
//! So the drift control is not only the three consts: [`VENDORED_FAMILY_PREFIXES`]
//! pins every family this cut carries and
//! [`tests::no_vendored_family_silently_disappears`] fails on any prefix that
//! vanishes. Additions are cheap and pass; a removal must be moved to
//! [`RETIRED_FAMILIES`] by hand, with a reason — which is exactly the review a
//! silent drop never gets.
//!
//! [`namespace_registry.json`]: <the vendored file in this directory>

use super::{Authority, AuthorityClass, ReservedRule};
use std::sync::OnceLock;

/// The vendored copy of the Constitution manifest, compiled in.
pub(super) const REGISTRY_JSON: &str = include_str!("namespace_registry.json");

/// The CC version [`REGISTRY_JSON`] was generated from. Bump in lockstep when
/// re-vendoring (the drift gate asserts the file's `_meta.cc_version` matches).
pub const VENDORED_CC_VERSION: &str = "1.0-rc6";
/// SHA-256 of the CC `part_3_the_namespace.md` bytes the manifest was generated
/// from (the manifest's `_meta.source_sha256`). Pins the exact source cut.
pub const VENDORED_SOURCE_SHA256: &str =
    "459d3ef52bc6d021d8bed58af908f75c11fdaf83b5cb841e100040fbe6437ea9";
/// The number of prefix families in this vendored cut (the enumerated leaf
/// count; CC 3.1's "83" summary is stale — see CIRISConstitution#30).
pub const VENDORED_N_FAMILIES: usize = 158;

/// v50.0.0 (CIRISPersist#924, CIRISConstitution#112) — the manifest's
/// `_meta.registry_sha256`: the hash of the GRAMMAR (families + `_meta` minus
/// the two hashes), so a wording edit elsewhere in CC Part 3 does not move it
/// while `source_sha256` does. This is the pin CC asks every consumer to carry;
/// [`tests::vendored_registry_sha256_pins_the_cc_file`] recomputes it over the
/// vendored bytes the way `tools/build_cc_namespace.py` does.
///
/// Vendored byte-for-byte from CIRISConstitution commit [`VENDORED_CC_COMMIT`]
/// (CC 1.0-rc6, the `v1.0-rc6` tag's commit), together with
/// `namespace_match_vectors.json` from the same commit. JSON carries no
/// comments, so this doc is the vendored files' header.
pub const VENDORED_REGISTRY_SHA256: &str =
    "f666f334db6b5e82dd7f75e6cbe82c926d27dcd9bd81d208784527cbce651c37";

/// The CIRISConstitution commit both vendored manifests were copied from: the
/// commit the `v1.0-rc6` tag names (`3c3e63f`, annotated tag `b9d8cba`).
///
/// The files were first copied at `1f45ebe` "Cut 1.0-rc6, released as guidance"
/// on branch `rc6`, before the tag existed; both manifests carry the same blob
/// ids at `1f45ebe` and at the tag, so the bytes are unchanged and only this
/// record moved. The files are also pinned by their own SHA-256
/// ([`VENDORED_REGISTRY_FILE_SHA256`], [`VENDORED_VECTORS_FILE_SHA256`]), and
/// `scripts/check_vendored_cc.sh v1.0-rc6` byte-compares them against the tag
/// before a persist release that names rc6 is tagged.
pub const VENDORED_CC_COMMIT: &str = "3c3e63fdef844f2f849e43081a8242e31cfaf30d";

/// SHA-256 of the vendored `namespace_registry.json` FILE bytes (the whole file,
/// unlike [`VENDORED_REGISTRY_SHA256`], which is CC's hash of the grammar).
/// What `scripts/check_vendored_cc.sh` compares against the tag.
pub const VENDORED_REGISTRY_FILE_SHA256: &str =
    "5f53f9776604713cb84468811983e67804b9771d61882a6723be61000897056d";

/// SHA-256 of the vendored `namespace_match_vectors.json` FILE bytes.
pub const VENDORED_VECTORS_FILE_SHA256: &str =
    "c4226dfb769c8939b608398e9b6b4364dde62b8ac40b2cd25363af9bb4622810";

/// v42.0.0 (CC 3.1.7 R3, CIRISPersist#815) — the case class of one dimension
/// SEGMENT, read from the manifest rather than inferred from `{...}` in prose.
///
/// A dimension is a **case-sensitive byte string** compared byte-exactly
/// everywhere; nothing case-folds. Which rule a segment obeys is decided per
/// segment, and only [`Vocab`](SegmentClass::Vocab), [`Literal`] and
/// [`Hex`](SegmentClass::Hex) constrain case at all.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SegmentClass {
    /// A CC-fixed stem. Lowercase by construction — the CC generator refuses to
    /// build if a catalogued stem is not.
    Literal,
    /// CC-defined vocabulary. MUST match `_meta.case_rule.vocab_pattern`; any
    /// other byte is malformed, never folded.
    Vocab,
    /// Spelling fixed by an outside standard (ISO 4217 `USD`, BCP 47 `en-US`,
    /// `PG-13`) — verbatim canonical form, case untouched.
    External,
    /// Caller-supplied identity (`{authority_id}`, `{target}`) — verbatim,
    /// case PRESERVED. Constraining these would be a vocabulary change persist
    /// may not make.
    Value,
    /// A CC 2.6.3 digest — lowercase; uppercase is malformed.
    Hex,
    /// A `*` tail.
    Wildcard,
}

impl SegmentClass {
    fn parse(s: &str) -> Option<Self> {
        Some(match s {
            "literal" => SegmentClass::Literal,
            "vocab" => SegmentClass::Vocab,
            "external" => SegmentClass::External,
            "value" => SegmentClass::Value,
            "hex" => SegmentClass::Hex,
            "wildcard" => SegmentClass::Wildcard,
            _ => return None,
        })
    }
}

/// One resolved namespace family — a CC 3.1 prefix, its owning component, and
/// the [`Authority`] its reserved-prefix rule (CC 3.4) demands.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NamespaceEntry {
    /// The catalogued family prefix, verbatim from CC 3.1 (e.g.
    /// `"provenance:build_manifest:{target}"`, `"accord:*"`,
    /// `"audit_chain:hash_continuity"`).
    pub prefix: String,
    /// The family's literal stem — `prefix` truncated at its first `{`
    /// parameter or `*` wildcard (e.g. `"provenance:build_manifest:"`,
    /// `"accord:"`).
    ///
    /// v50.0.0 (CIRISPersist#924): DATA only. It no longer decides which
    /// family a dimension resolves to — [`lookup`] asks the one matcher
    /// ([`match_family`](super::matcher::match_family)) — and survives because
    /// the entries are still ordered by it and the co-scrub classifier reads
    /// it.
    pub match_prefix: String,
    /// The owning component slug (CC 3.1.N heading), e.g. `"persist"`,
    /// `"attestation"`, `"registry"`.
    pub owning_component: String,
    /// The steward repo, when the manifest records one.
    pub owning_repo: Option<String>,
    /// The CC section the family is catalogued in (e.g. `"3.1.2"`).
    pub cc_section: String,
    /// The row's catalogue PROSE, verbatim from the manifest (the generator's
    /// first-sentence extract of the CC 3.1 table cell).
    ///
    /// Carried since CIRISPersist#571 for one reason: several rc3 rows state an
    /// emitter rule in this field while generating `reserved: false` with no
    /// [`Authority::reserved`] — `regime:{artifact}:{version}` says *"reserved —
    /// substrate-steward-emitted"* and resolves `ProducerSteward`/`None`. Persist
    /// deliberately does **not** enforce anything read from here (that would be
    /// the section-walk heuristic CC 3.1.7 R2 forbids); it exists so a test can
    /// quote the row's own words back and FAIL when structure and prose
    /// disagree, instead of that disagreement living in a comment.
    pub description: String,
    /// The resolved emit authority (class + any CC 3.4 reserved rule).
    pub authority: Authority,
    /// v42.0.0 (CC 3.1.7 R3) — the family's per-segment case classes, in
    /// order. Read by
    /// [`check_dimension_case_rule`](crate::federation::admission::check_dimension_case_rule);
    /// an unclassified segment fails the CC build, so this is never partial for
    /// a catalogued family.
    pub segments: Vec<(String, SegmentClass)>,
}

// ── raw serde shapes matching the generated manifest ────────────────────

#[derive(serde::Deserialize)]
struct RawManifest {
    #[serde(rename = "_meta")]
    meta: RawMeta,
    families: Vec<RawFamily>,
}

#[derive(serde::Deserialize)]
struct RawMeta {
    cc_version: String,
    source_sha256: String,
    n_families: usize,
    /// **The `_meta` key the R2 Private Use ask asked for, and the rc3
    /// re-vendor delivered.** `x_private:` on this cut.
    ///
    /// [`PRIVATE_USE_FAMILY_STEM`](crate::federation::admission::PRIVATE_USE_FAMILY_STEM)
    /// says of itself that it is "a prose transcription", and names the remedy
    /// in its own doc: *"a machine-readable range field in the generated
    /// manifest (a `_meta` key, not a family row, since it is not a family)"*.
    /// That field now exists, so
    /// [`tests::the_private_use_range_is_machine_readable_now`] binds the
    /// transcription to it — the const stops being a claim about CC prose that
    /// nothing can contradict and becomes one the vendored artifact can.
    ///
    /// Worth noting what this is NOT: it does not make persist enforce the
    /// range from the manifest. The refusal
    /// ([`check_private_use_not_federatable`](crate::federation::admission::check_private_use_not_federatable))
    /// still matches on the const, because a range read from a mutable data
    /// file is a range an attacker who can influence the vendored bytes could
    /// move. What the field buys is that the const can no longer be silently
    /// WRONG.
    ///
    /// `Option` because a cut generated before CC shipped the field carries
    /// none, and the gate should say WHICH cut is stale rather than fail to
    /// parse.
    #[serde(default)]
    private_use_prefix: Option<String>,
    /// CC 2.4 "The row-type slot is closed" (rc6): the five structural row
    /// types and the registered carriers. `Option` for the same reason as
    /// `private_use_prefix`: a cut generated before rc6 carries none.
    #[serde(default)]
    row_types: Option<RowTypes>,
}

#[derive(serde::Deserialize)]
struct RawFamily {
    prefix: String,
    owning_component: String,
    #[serde(default)]
    owning_repo: Option<String>,
    cc_section: String,
    #[serde(default)]
    description: String,
    // NOTE: the manifest's `reserved` bool is redundant with `reserved_rule`
    // presence (which carries the CC 3.4 specifics) — serde ignores it.
    #[serde(default)]
    reserved_rule: Option<RawReservedRule>,
    /// v42.0.0 (CC 3.1.7 R3, CIRISPersist#815) — the per-segment case classes.
    #[serde(default)]
    segments: Vec<RawSegment>,
}

#[derive(serde::Deserialize)]
struct RawSegment {
    segment: String,
    class: String,
}

#[derive(serde::Deserialize)]
struct RawReservedRule {
    rule: String,
    /// **Optional in the manifest.** Most reserved families name the CC 3.4
    /// clause that rules them (`"CC 3.4.1"`); a family whose reservation is
    /// stated in its own CC 3.1 catalogue row rather than a separate clause
    /// carries `"cc_ref": null` (rc3: `trust:{job}:{version}`). Deserializing
    /// that into a `String` is what a `serde` `missing field`/`invalid type`
    /// panic at first `authority_for` call looks like, so it is typed
    /// `Option` and resolved to the family's own catalogue section in
    /// [`parse_manifest`] — never to an empty string, which would be a
    /// citation that reads as present and points nowhere.
    #[serde(default)]
    cc_ref: Option<String>,
}

/// The literal stem of a family prefix — everything before the first `{`
/// parameter or `*` wildcard. `"accord:*"` → `"accord:"`;
/// `"provenance:build_manifest:{target}"` → `"provenance:build_manifest:"`;
/// `"audit_chain:hash_continuity"` → itself.
fn match_prefix_of(prefix: &str) -> String {
    let cut = prefix.find(['{', '*']).unwrap_or(prefix.len());
    prefix[..cut].to_string()
}

/// **The one match_prefix this classifier answers from persist's own source
/// rather than from the manifest** (CIRISPersist#519).
///
/// A build manifest is accord-co-scrubbed — identical authority to a canonical
/// seed, which is what closes the chicken/egg at genesis. CC's
/// `provenance:build_manifest:{target}` row states no `reserved_rule`, so
/// [`authority_for`] returns an authority the Constitution's artifact never
/// carried, and nothing downstream can audit that answer against CC.
///
/// Named rather than inlined so [`crate::federation::family_rules`] can read
/// the assertion at its source and pin it as the gap it is
/// (`RowRuleGap::ClassAssertedByPersistNotTheRow`); the ask is to land the
/// rule on the row and delete the arm.
pub const ACCORD_CO_SCRUB_MATCH_PREFIX: &str = "provenance:build_manifest";

/// Derive the emit [`AuthorityClass`] for a family from its catalogued
/// reserved-emit rule, layering persist's own trust-root knowledge on top.
///
/// - `provenance:build_manifest:*` → [`AccordCoScrub`](AuthorityClass::AccordCoScrub):
///   a build manifest is accord-co-scrubbed (the `infra:attest` gate), identical
///   authority to a canonical seed — the property that closes the chicken/egg.
/// - `substrate-self-report` (CC 3.4.3) → [`SubstrateSelf`](AuthorityClass::SubstrateSelf).
/// - any other reserved rule (accord_holder-only, detector-only, witness-emitter,
///   co-stewarded, no-self-emit) or an unreserved dimension →
///   [`ProducerSteward`](AuthorityClass::ProducerSteward); the CC 3.4 specifics
///   ride in [`Authority::reserved`].
///
/// NOTE: no CC 3.1 *dimension* prefix resolves to
/// [`SelfIdentity`](AuthorityClass::SelfIdentity) — that authority governs the
/// CC 3.3 *subject-kind* objects (key records, identity occurrences, transport
/// bindings), which the edge engine authorizes structurally (via the object
/// kind), not through this dimension registry.
fn class_for(match_prefix: &str, rule: Option<&str>) -> AuthorityClass {
    if match_prefix.starts_with(ACCORD_CO_SCRUB_MATCH_PREFIX) {
        return AuthorityClass::AccordCoScrub;
    }
    match rule {
        Some("substrate-self-report") => AuthorityClass::SubstrateSelf,
        _ => AuthorityClass::ProducerSteward,
    }
}

fn parse_manifest() -> Vec<NamespaceEntry> {
    let raw: RawManifest =
        serde_json::from_str(REGISTRY_JSON).expect("vendored namespace_registry.json is valid");
    // Drift invariants (also enforced as a hard test in this module): the
    // vendored cut must be the one the consts pin, and be self-consistent.
    debug_assert_eq!(raw.meta.cc_version, VENDORED_CC_VERSION, "cc_version drift");
    debug_assert_eq!(
        raw.meta.source_sha256, VENDORED_SOURCE_SHA256,
        "CC part_3 source hash drift — regenerate + re-vendor"
    );
    assert_eq!(
        raw.families.len(),
        raw.meta.n_families,
        "manifest self-consistency: families[] != _meta.n_families"
    );
    let mut entries: Vec<NamespaceEntry> = raw
        .families
        .into_iter()
        .map(|f| {
            let match_prefix = match_prefix_of(&f.prefix);
            let reserved = f.reserved_rule.map(|r| ReservedRule {
                rule: r.rule,
                // A manifest row with no `cc_ref` is ruled by its own CC 3.1
                // catalogue row; cite THAT rather than leave the field an
                // empty string a reader would take for a missing citation.
                cc_ref: r.cc_ref.unwrap_or_else(|| format!("CC {}", f.cc_section)),
            });
            let class = class_for(&match_prefix, reserved.as_ref().map(|r| r.rule.as_str()));
            NamespaceEntry {
                prefix: f.prefix,
                match_prefix,
                owning_component: f.owning_component,
                owning_repo: f.owning_repo,
                cc_section: f.cc_section,
                description: f.description,
                authority: Authority { class, reserved },
                segments: f
                    .segments
                    .iter()
                    .filter_map(|sg| {
                        SegmentClass::parse(&sg.class).map(|c| (sg.segment.clone(), c))
                    })
                    .collect(),
            }
        })
        .collect();
    // Longest match_prefix first — a stable, documented order for consumers
    // that enumerate the registry (resolution is the matcher's, not this
    // order's, since v50.0.0).
    entries.sort_by(|a, b| {
        b.match_prefix
            .len()
            .cmp(&a.match_prefix.len())
            .then_with(|| a.prefix.cmp(&b.prefix))
    });
    entries
}

fn registry() -> &'static [NamespaceEntry] {
    static REGISTRY: OnceLock<Vec<NamespaceEntry>> = OnceLock::new();
    REGISTRY.get_or_init(parse_manifest)
}

/// One registered **carrier** row type (CC 2.4, rc6): a non-`scores` row type
/// that may occupy the attestation plane. `pattern` is CC's anchored regular
/// expression, compared byte-exact and whole-string.
#[derive(Debug, Clone, PartialEq, Eq, serde::Deserialize)]
pub struct CarrierRowType {
    /// The envelope `kind` a row of this type carries (`holds_bytes`, `key_grant`).
    pub kind: String,
    /// CC's anchored pattern for the whole `attestation_type` string.
    pub pattern: String,
    /// A sample value CC publishes for the pattern.
    pub sample: String,
    /// The token as CC's text spells it (`key_grant:{axis}:{version}`).
    pub token: String,
}

/// The vendored registry's `_meta.row_types` (CC 2.4, rc6): the closed set of
/// `attestation_type` values. Vendored and parsed here; the admission gate
/// that enforces it is CIRISPersist#975 and reads this, never constants.
#[derive(Debug, Clone, PartialEq, Eq, serde::Deserialize)]
pub struct RowTypes {
    /// The five structural row types.
    pub structural: Vec<String>,
    /// The registered carriers.
    pub carriers: Vec<CarrierRowType>,
    /// The refusal token for anything else (`attestation_type_unregistered`).
    pub refusal: String,
    /// CC's statement of the comparison rule.
    pub compare: String,
    /// The CC clause (`CC 2.4`).
    pub cc_ref: String,
}

/// The closed row-type set of the vendored cut, or `None` for a cut generated
/// before CC published it. Parsed once.
#[must_use]
pub fn row_types() -> Option<&'static RowTypes> {
    static R: OnceLock<Option<RowTypes>> = OnceLock::new();
    R.get_or_init(|| {
        let raw: RawManifest =
            serde_json::from_str(REGISTRY_JSON).expect("vendored namespace_registry.json is valid");
        raw.meta.row_types
    })
    .as_ref()
}

/// Is `attestation_type` one of the registered CARRIER row types (CC 2.4) —
/// a whole-string, byte-exact match for a carrier pattern in
/// `_meta.row_types`?
///
/// One caller: the type half of the CC 3.1.7 R2(b) check in
/// `admission`. A carrier token is a row type and never a dimension, and the
/// registry says so by gating its stem (`key_grant:` — "carrier row type,
/// never a dimension"), so the DIMENSION matcher refuses the token by design.
/// A row's type is not a dimension; this is what keeps the type slot of a
/// registered carrier out of the dimension matcher. It refuses nothing: the
/// allowlist over the whole slot is CIRISPersist#975.
#[must_use]
pub fn is_registered_carrier_row_type(attestation_type: &str) -> bool {
    static PATTERNS: OnceLock<Vec<regex::Regex>> = OnceLock::new();
    PATTERNS
        .get_or_init(|| {
            row_types()
                .map(|rt| {
                    rt.carriers
                        .iter()
                        .map(|c| {
                            // Full match whatever the row's own anchors say, and
                            // `\z` so a trailing newline is never admitted.
                            let body = c.pattern.trim_start_matches('^').trim_end_matches('$');
                            regex::Regex::new(&format!("\\A(?:{body})\\z"))
                                .expect("a vendored carrier pattern compiles")
                        })
                        .collect()
                })
                .unwrap_or_default()
        })
        .iter()
        .any(|re| re.is_match(attestation_type))
}

/// The full vendored namespace registry (every CC 3.1 prefix family), sorted
/// most-specific-`match_prefix`-first. Edge enumerates this to build its
/// dimension→policy table once at boot.
pub fn entries() -> &'static [NamespaceEntry] {
    registry()
}

/// The **Private Use range**, read from the vendored manifest's `_meta` rather
/// than transcribed from CC prose. `None` on a cut generated before CC shipped
/// the field.
///
/// See [`RawMeta::private_use_prefix`] — including what this deliberately does
/// not change about enforcement.
#[must_use]
pub fn vendored_private_use_prefix() -> Option<&'static str> {
    static P: OnceLock<Option<String>> = OnceLock::new();
    P.get_or_init(|| {
        let raw: RawManifest =
            serde_json::from_str(REGISTRY_JSON).expect("vendored namespace_registry.json is valid");
        raw.meta.private_use_prefix
    })
    .as_deref()
}

/// The [`NamespaceEntry`] `dimension` resolves to under the ONE matcher
/// ([`match_family`](super::matcher::match_family), CC 3.1.7 R3), or `None`
/// when no row claims it (open vocabulary, or a leaf under a reserved stem no
/// row names).
///
/// v50.0.0 (CIRISPersist#924) — used to be the longest LITERAL prefix
/// (`match_prefix`), which let `session:a:b:c:v1` resolve to `session:{kind}`
/// at the wrong arity and `accord:invoke:anything` resolve to `accord:*` as if
/// it were a leaf CC names. The family is returned even when the dimension is
/// REFUSED (a missing version, a closed-vocabulary value, an unlisted closed
/// leaf): the family the refusal was judged against is still the authority a
/// classifier must report — dropping a reservation because the row was also
/// malformed would be a fail-open.
pub fn lookup(dimension: &str) -> Option<&'static NamespaceEntry> {
    let family = super::matcher::match_family(dimension).family?;
    registry().iter().find(|e| e.prefix == family)
}

/// **`authority_for(dimension)`** — the emit authority the `dimension`'s
/// reserved-prefix rule (CC 3.4) demands, resolved from the vendored CC-3.1
/// registry. A `dimension` outside the namespace defaults to
/// [`ProducerSteward`](AuthorityClass::ProducerSteward) with no reserved rule (a
/// signed producer claim; the write-path reserved-prefix admission gate is the
/// enforcement point, not this classifier). Infra prefixes
/// (`provenance:build_manifest:*`) resolve to
/// [`AccordCoScrub`](AuthorityClass::AccordCoScrub) — identical to a canonical
/// record, closing the chicken/egg.
pub fn authority_for(dimension: &str) -> Authority {
    if let Some(e) = lookup(dimension) {
        return e.authority.clone();
    }
    // v50.0.0 (CIRISPersist#924) — a dimension under a stem CC 3.4 reserves
    // as a whole that no row claims (`capacity_assurance:reversible_imagined:
    // financial:v1`): the old longest-literal-prefix lookup attributed it to
    // the stem's row and so carried the reservation; the one matcher claims no
    // row for it, and reporting it OPEN would drop the reservation. The stem's
    // own `_meta.case_rule.reserved_stems` rule answers instead.
    if let Some((rule, cc_ref)) = super::matcher::reserved_stem_rule(dimension) {
        let reserved = ReservedRule {
            rule: rule.to_owned(),
            cc_ref: cc_ref.to_owned(),
        };
        return Authority {
            class: class_for(dimension, Some(rule)),
            reserved: Some(reserved),
        };
    }
    Authority {
        class: AuthorityClass::ProducerSteward,
        reserved: None,
    }
}

// ── (CIRISPersist#590, CC 3.1.7 R2) — family-STEM registration ──

/// The **family stem** of a dimension or `attestation_type` — everything up to
/// and including its first `:` (`"objection:raised:v1"` → `"objection:"`), or
/// the whole token when it carries no `:`.
///
/// This is the granularity CC 3.1.7 R2 speaks at. R2 refuses "a family with no
/// registry row"; a *family* is `objection:{state}`, not the leaf
/// `objection:raised:v1`, and CC explicitly preserves "the open-vocabulary space
/// this Part deliberately leaves open" — the `{param}` slots WITHIN a registered
/// family. Enforcing at leaf granularity would refuse exactly that open
/// vocabulary (`credits:{domain}:{language}:{subject}` admits any domain), which
/// is the "refuse conformant traffic" failure CIRISPersist#590 was opened to
/// prevent.
#[must_use]
pub fn family_stem(dimension: &str) -> &str {
    match dimension.find(':') {
        Some(i) => &dimension[..=i],
        None => dimension,
    }
}

/// Every **family stem** the vendored manifest registers, sorted and deduped.
/// The R2 registration test: a stem in this set has at least one catalogue row,
/// so a dimension under it is emitted on a *registered* family.
pub fn registered_family_stems() -> &'static [&'static str] {
    static STEMS: OnceLock<Vec<&'static str>> = OnceLock::new();
    STEMS.get_or_init(|| {
        let mut v: Vec<&'static str> = registry().iter().map(|e| family_stem(&e.prefix)).collect();
        v.sort_unstable();
        v.dedup();
        v
    })
}

/// **CC 3.1.7 R2 registration predicate** — does `dimension` resolve to a
/// family row? Answered by the ONE matcher
/// ([`match_family`](super::matcher::match_family)): a row claims it, and the
/// claim is not an unlisted leaf under a closed reserved family
/// (`namespace_family_unregistered`).
///
/// v50.0.0 (CIRISPersist#924) — this used to be stem-granular (the first `:`),
/// so `accord:invoke:anything:v1` read as registered because SOME `accord:`
/// row existed, while CC closes `accord:*` to its six named leaves. A dimension
/// that is well-registered but otherwise malformed (missing version, a closed
/// vocabulary value) still answers `true` here — registration is R2's
/// question; the grammar's other refusals are the case and version gates'.
/// Asking about a STEM (`"regime:"`) is [`is_stem_registered`].
#[must_use]
pub fn is_family_registered(dimension: &str) -> bool {
    let m = super::matcher::match_family(dimension);
    m.family.is_some() && m.refusal != Some(super::matcher::Refusal::FamilyUnregistered)
}

/// Does ANY vendored row sit on `stem` (`"regime:"`, or a bare `"scores"`)? A
/// set-membership question over the manifest's rows, not a dimension match —
/// the R2(a) build gates ask it of the stems persist governs.
#[must_use]
pub fn is_stem_registered(stem: &str) -> bool {
    !stem.is_empty() && registered_family_stems().binary_search(&stem).is_ok()
}

/// **The removal gate** (CIRISPersist#590 item 4). Every family prefix the
/// vendored cut carries, pinned in source so a re-vendor that DROPS one fails
/// the build instead of moving a count.
///
/// Direction matters and is asymmetric on purpose:
///
/// - **Additions are cheap.** A new CC family appears in the manifest, this list
///   does not mention it, and nothing fails. Bump it when convenient.
/// - **Removals are the incident.** CC's first R2 regeneration silently lost
///   four families to a prose paragraph inserted mid-markdown-table; 106 + 3 − 4
///   = 105 and the only signal was an arithmetic discrepancy. A prefix that
///   disappears from the manifest fails
///   [`tests::no_vendored_family_silently_disappears`] BY NAME, and clearing it
///   means moving the line to [`RETIRED_FAMILIES`] with a reason.
///
/// Yes, this is a second list beside the manifest — deliberately. The
/// disagreement between them IS the alarm; that is the opposite of the
/// two-lists-that-quietly-disagree class (#541, #532, #588), where neither list
/// could see the other.
pub const VENDORED_FAMILY_PREFIXES: &[&str] = &[
    "accord:*",
    "accord:human_dignity",
    "accord:invoke:constitutional:{halt_id}",
    "accord:invoke:drill:{drill_id}",
    "accord:invoke:notify:{notify_id}",
    "accord:lifecycle",
    "accord:lifecycle:active",
    "activity_tier:{period}",
    "age_assurance:{level}:{band}:{version}",
    "age_self_declared:band:{band}:{version}",
    "agent_files:{kind}:{platform_or_target}",
    "approach:{goal_id}",
    "attestation:agent_integrity",
    "attestation:hardware_rooted",
    "attestation:license_validity",
    "attestation:registry_consensus",
    "attestation:self_verify",
    "audio:*",
    "audit_chain:hash_continuity",
    "autonomy:{aspect}",
    "benchmark:he300:{category}:{version}",
    "beneficence:{aspect}",
    "blog:*",
    "bond_posted:{currency}",
    "build:registered:{target}",
    "capacity:composite",
    "capacity:core_identity",
    "capacity:incompleteness_awareness",
    "capacity:integrity",
    "capacity:relay_delivery",
    "capacity:resilience",
    "capacity:sustained_coherence",
    "capacity_assurance:reversible_excluded:{domain}:{version}",
    "capacity_assurance:reversible_pending:{domain}:{version}",
    "capacity_assurance:{level}:{domain}:{band}:{version}",
    "cert_validity:{authority}",
    "chat:*",
    "coherence_standing:{cohort}",
    "commitment_fulfillment:{prior_contribution_id}",
    "config:{scope}",
    "conscience:coherence",
    "conscience:entropy",
    "conscience:epistemic_humility",
    "conscience:optimization_veto",
    "consent:decay:{stage}",
    "consent:community_trust",
    "consent:deletion_complete",
    "consent:deletion_sla:{days}",
    "consent:partnership_accept",
    "consent:partnership_grant",
    "consent:replication:{version}",
    "consent:scope:{kind}",
    "consent:state:{stance}",
    "consent:stream:{kind}",
    "consent:{kind}",
    "content_class:{class}",
    "content_rating:{scheme}:{rating}",
    "corpus_health:n_eff_measurable",
    "credits:{domain}:{language}:substrate_building",
    "credits:{domain}:{language}:{subject}",
    "cw_class:{class}",
    "delivery:{class}",
    "delivery_receipt:{stream_id}",
    "detection:conscience_override_rate",
    "detection:correlated_action:{axis}",
    "detection:cross_agent_divergence",
    "detection:distributive:access:{resource_type}",
    "detection:hash_chain_integrity",
    "detection:intra_agent_consistency",
    "detection:temporal_drift",
    "dma:csdma:*",
    "dma:dsdma:{domain}:*",
    "dma:idma:*",
    "dma:pdma:*",
    "duty:{kind}",
    "encyclopedia:*",
    "event:attendance",
    "event:lifecycle:{state}",
    "event:rsvp_count",
    "expertise:{domain}:{language}",
    "federation_directory:replication_lag",
    "fidelity:explainability_sla:{tier}",
    "fidelity:{aspect}",
    "film:*",
    "goal:{scale}",
    "hard_case:{kind}",
    "hardware_custody:{platform}",
    "health:liveness:{version}",
    "holds_bytes:sha256:{prefix}",
    "identity:canonical_binding:{canonical_hash}",
    "identity_continuity:relational_anchor",
    "image:*",
    "integrity:{aspect}",
    "judge_model:verdict:{model_id}",
    "justice:{aspect}",
    "key_boundary:{scope}",
    "licensure:{authority_id}",
    "locality:decision:{scale}",
    "manifold_conformity:{cohort}",
    "mesh_config:{key}",
    "method:{approach_id}:{substrate_rung}",
    "model_3d:*",
    "moderation:{allegation_type}",
    "moderation_track_record:{community_key_id}",
    "multilateral_participation:{forum}:{kind}",
    "need:{domain}:{kind}",
    "news:*",
    "non_maleficence:{aspect}",
    "objection:{state}",
    "ownership:{relation}:{target_kind}:{version}",
    "partner_role:{role}",
    "peer_reachability:{network}",
    "progress_measure:{method_id}",
    "prohibited:{category}",
    "provenance:build_manifest:{target}",
    "provenance:build_manifest:{target}:locale:{lang_code}",
    "provenance:skill_import:{source}",
    "provenance:slsa:{level}",
    "quarantine:{state}",
    "ratchet:flag:coordinated_voting_cluster",
    "ratchet:flag:counter_rii:{layer}",
    "ratchet:flag:density_anomaly",
    "ratchet:flag:expertise_attestation_anomaly",
    "ratchet:flag:harassment_pattern",
    "ratchet:flag:out_of_distribution_voting",
    "reconsideration:{grounds}",
    "regime:{artifact}:{version}",
    "revocation:{entity_type}:{reason}",
    "rollback_detected:{revision_field}",
    "seed_holder_voting_alignment:{cell}",
    "session:{kind}",
    "slashing:{outcome}",
    "system:*",
    "testimonial_witness:{kind}",
    "topical_relation:{kind}",
    "trace:{form}:{version}",
    "trace_summary:{kind}",
    "transparency_log:consistency",
    "transparency_log:cosigned:{tree_size}",
    "transparency_log:inclusion",
    "transport:{kind}",
    "trust:{job}:{version}",
    "truth_grounding:{subject}",
    "video:*",
    "vote:{contribution_id}",
    "wa_adjudication:{state}",
    "watchlist:{id}",
    "weighted_aggregate:{contribution_id}",
    "witness_diversity:{contribution_id}",
    "collection:{kind}",
    "custody:{kind}",
    "device:label",
    "file:{version}",
    "lineage_witness:{stage}",
    "membership:{stage}",
    "observation:reachability",
    "self:delegates_to",
    "self:delegates_to:agent_occurrence",
];

/// Families CC has **deliberately retired** — present in an earlier vendored cut,
/// intentionally absent from this one. The first real retirement landed with
/// the v50.0.0 (rc5 @ 4b624513) vendor; every earlier disappearance was a
/// generator accident.
///
/// The escape hatch for [`VENDORED_FAMILY_PREFIXES`]: moving a line here is how
/// a reviewer says "this removal is intended", in a diff someone must read.
pub const RETIRED_FAMILIES: &[&str] = &[
    // CIRISConstitution#113 review (rc5 @ 4b624513): the two-segment arity no
    // producer emitted, re-registered at the wire's arity as
    // `age_self_declared:band:{band}:{version}` (CC 3.1.2). CC's own
    // generator lists it in its `RETIRED_FAMILIES`.
    "age_self_declared:{band}:{version}",
];

#[cfg(test)]
mod tests {

    /// v42.0.0 (CC 3.1.7 R3, CIRISPersist#815) — the manifest's `segments[]`
    /// ALIGN POSITIONALLY with their family's `prefix`.
    ///
    /// `check_dimension_case_rule` zips a concrete dimension's `:`-split
    /// segments against this list by POSITION, so a manifest whose segment list
    /// did not correspond to the prefix's own structure would silently mis-class
    /// — judging a `value` segment by the `vocab` rule, or worse, letting a
    /// `vocab` segment through under `value`. That would be invisible: the gate
    /// would still pass its own table.
    #[test]
    fn manifest_segments_align_with_their_prefix_815() {
        for e in entries() {
            let parts: Vec<&str> = e.prefix.split(':').collect();
            assert_eq!(
                e.segments.len(),
                parts.len(),
                "{:?} has {} prefix segments but {} classified — a positional zip \
                 would mis-class",
                e.prefix,
                parts.len(),
                e.segments.len()
            );
            for (i, (name, _)) in e.segments.iter().enumerate() {
                assert_eq!(
                    name, parts[i],
                    "{:?} segment {i} is {:?} in the prefix but {name:?} in \
                     segments[] — the lists have drifted apart",
                    e.prefix, parts[i]
                );
            }
        }
    }
    use super::*;

    #[test]
    fn vendored_manifest_matches_the_pinned_cc_cut() {
        // Drift gate: the compiled-in manifest must be the exact cut the consts
        // pin. Re-vendoring after a CC change forces a deliberate const bump.
        let raw: RawManifest = serde_json::from_str(REGISTRY_JSON).unwrap();
        assert_eq!(raw.meta.cc_version, VENDORED_CC_VERSION, "cc_version drift");
        assert_eq!(
            raw.meta.source_sha256, VENDORED_SOURCE_SHA256,
            "source hash drift — CC part_3 changed; regenerate + re-vendor"
        );
        assert_eq!(
            raw.meta.n_families, VENDORED_N_FAMILIES,
            "family count drift"
        );
        assert_eq!(
            raw.families.len(),
            VENDORED_N_FAMILIES,
            "families[] length != _meta.n_families"
        );
        // CIRISConstitution#116 — the released rc5 declares full-match
        // semantics for every segment pattern; `matcher::compile` implements it.
        let root: serde_json::Value = serde_json::from_str(REGISTRY_JSON).unwrap();
        assert!(
            root["_meta"]["case_rule"]["match_semantics"]
                .as_str()
                .is_some_and(|m| m.starts_with("full-match")),
            "_meta.case_rule.match_semantics is missing or no longer full-match"
        );
    }

    /// Python's `json.dumps(v, sort_keys=True, separators=(",", ":"))` with its
    /// default `ensure_ascii=True` — the preimage `tools/build_cc_namespace.py`
    /// hashes for `_meta.registry_sha256`. The manifest carries no floats (a
    /// float's repr is the one place the two serializers would disagree), and
    /// this refuses one rather than guessing.
    fn python_canonical_json(v: &serde_json::Value, out: &mut String) {
        use serde_json::Value as V;
        fn string(s: &str, out: &mut String) {
            out.push('"');
            for c in s.chars() {
                match c {
                    '"' => out.push_str("\\\""),
                    '\\' => out.push_str("\\\\"),
                    '\n' => out.push_str("\\n"),
                    '\r' => out.push_str("\\r"),
                    '\t' => out.push_str("\\t"),
                    '\u{08}' => out.push_str("\\b"),
                    '\u{0c}' => out.push_str("\\f"),
                    c if (c as u32) < 0x20 || (c as u32) > 0x7e && (c as u32) != 0x7f => {
                        let mut buf = [0u16; 2];
                        for unit in c.encode_utf16(&mut buf) {
                            out.push_str(&format!("\\u{unit:04x}"));
                        }
                    }
                    c => out.push(c),
                }
            }
            out.push('"');
        }
        match v {
            V::Null => out.push_str("null"),
            V::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
            V::Number(n) => {
                let t = n.to_string();
                assert!(
                    !t.contains(['.', 'e', 'E']),
                    "a float in the manifest: {t} — Python's repr and serde's may differ"
                );
                out.push_str(&t);
            }
            V::String(s) => string(s, out),
            V::Array(a) => {
                out.push('[');
                for (i, x) in a.iter().enumerate() {
                    if i > 0 {
                        out.push(',');
                    }
                    python_canonical_json(x, out);
                }
                out.push(']');
            }
            V::Object(o) => {
                let mut keys: Vec<&String> = o.keys().collect();
                keys.sort();
                out.push('{');
                for (i, k) in keys.iter().enumerate() {
                    if i > 0 {
                        out.push(',');
                    }
                    string(k, out);
                    out.push(':');
                    python_canonical_json(&o[k.as_str()], out);
                }
                out.push('}');
            }
        }
    }

    /// The two vendored files are pinned by their own bytes: this is what
    /// `scripts/check_vendored_cc.sh <tag>` compares against the CC release tag,
    /// and what makes a hand edit to either file fail here.
    #[test]
    fn the_vendored_files_are_pinned_by_their_bytes() {
        use sha2::{Digest, Sha256};
        assert_eq!(
            hex::encode(Sha256::digest(REGISTRY_JSON.as_bytes())),
            VENDORED_REGISTRY_FILE_SHA256,
            "namespace_registry.json bytes moved without VENDORED_REGISTRY_FILE_SHA256"
        );
        assert_eq!(
            hex::encode(Sha256::digest(
                super::super::matcher::VECTORS_JSON.as_bytes()
            )),
            VENDORED_VECTORS_FILE_SHA256,
            "namespace_match_vectors.json bytes moved without VENDORED_VECTORS_FILE_SHA256"
        );
        assert_eq!(
            VENDORED_CC_COMMIT.len(),
            40,
            "a full commit id, never a branch name"
        );
    }

    /// CC 2.4 (rc6) — the closed row-type set is vendored and parses: the five
    /// and the two carriers, each carrier's own sample matching its pattern.
    /// Vendored only; enforcement is CIRISPersist#975.
    #[test]
    fn the_row_type_set_is_vendored_and_parses() {
        let rt = row_types().expect("rc6 carries _meta.row_types");
        assert_eq!(
            rt.structural,
            [
                "scores",
                "delegates_to",
                "supersedes",
                "withdraws",
                "recants"
            ]
        );
        assert_eq!(rt.refusal, "attestation_type_unregistered");
        let patterns: Vec<&str> = rt.carriers.iter().map(|c| c.pattern.as_str()).collect();
        assert_eq!(
            patterns,
            [
                "^holds_bytes:sha256:[0-9a-f]{8}$",
                "^key_grant:(content|epoch|stream):v1$"
            ]
        );
        for c in &rt.carriers {
            let re = regex::Regex::new(&c.pattern).expect("a carrier pattern compiles");
            assert!(
                re.is_match(&c.sample),
                "{} must match {}",
                c.sample,
                c.pattern
            );
            assert!(c.sample.starts_with(&format!("{}:", c.kind)), "{c:?}");
        }
        // The vectors file carries CC's row-type vectors beside the dimension
        // ones. Present and counted here; REPLAYED by the classifier that
        // enforces the slot (CIRISPersist#975), which this cut does not add.
        let vectors: serde_json::Value =
            serde_json::from_str(super::super::matcher::VECTORS_JSON).unwrap();
        let rtv = vectors["row_type_vectors"]
            .as_array()
            .expect("row_type_vectors");
        assert_eq!(rtv.len(), 39);
        // The carrier half of those vectors IS replayed, against the one reader
        // this cut adds: a vector CC classes `carrier` is a registered carrier,
        // and nothing else is.
        for v in rtv {
            let t = v["attestation_type"].as_str().unwrap();
            assert_eq!(
                is_registered_carrier_row_type(t),
                v["class"] == "carrier",
                "{t:?}"
            );
        }
        assert!(rtv
            .iter()
            .all(|v| v["refusal"].is_null() || v["refusal"] == rt.refusal));
    }

    /// v50.0.0 (CIRISPersist#924, CIRISConstitution#112) — the grammar pin.
    ///
    /// Recomputes `_meta.registry_sha256` over the VENDORED bytes exactly as
    /// `tools/build_cc_namespace.py` does (`sha256(json.dumps({"_meta": meta
    /// minus source_sha256/registry_sha256, "families": families},
    /// sort_keys=True, separators=(",",":")))`) and requires it to equal both
    /// the file's own claim and [`VENDORED_REGISTRY_SHA256`]. A hand edit to
    /// the vendored grammar — or a re-vendor that moved the bytes without the
    /// pin — fails here, while a CC wording edit (which moves only
    /// `source_sha256`) does not.
    #[test]
    fn vendored_registry_sha256_pins_the_cc_file() {
        use sha2::{Digest, Sha256};
        let root: serde_json::Value = serde_json::from_str(REGISTRY_JSON).unwrap();
        let meta = root["_meta"].as_object().expect("_meta object");
        let claimed = meta["registry_sha256"]
            .as_str()
            .expect("rc5 carries _meta.registry_sha256");
        let mut grammar_meta = meta.clone();
        grammar_meta.remove("source_sha256");
        grammar_meta.remove("registry_sha256");
        // v51.0.0 — CC's recipe since 651140a (`tools/build_cc_namespace.py`,
        // rc6) also excludes `cc_version`: a version bump is not a grammar
        // change. The recipe moves with the bytes it hashes.
        grammar_meta.remove("cc_version");
        let grammar = serde_json::json!({
            "_meta": serde_json::Value::Object(grammar_meta),
            "families": root["families"].clone(),
        });
        let mut preimage = String::new();
        python_canonical_json(&grammar, &mut preimage);
        let recomputed = hex::encode(Sha256::digest(preimage.as_bytes()));
        assert_eq!(
            recomputed, claimed,
            "the vendored grammar does not hash to its own _meta.registry_sha256 — the file \
             was edited after CC generated it"
        );
        assert_eq!(
            claimed, VENDORED_REGISTRY_SHA256,
            "re-vendored without moving VENDORED_REGISTRY_SHA256 (the bytes and the pin move \
             together)"
        );
        // The vectors file is generated from the same grammar and says so.
        let vectors: serde_json::Value = serde_json::from_str(super::super::matcher::VECTORS_JSON)
            .expect("vendored vectors parse");
        assert_eq!(
            vectors["_meta"]["registry_sha256"],
            VENDORED_REGISTRY_SHA256
        );
    }

    #[test]
    fn registry_parses_and_is_nonempty() {
        let reg = entries();
        assert_eq!(reg.len(), VENDORED_N_FAMILIES);
        // sorted longest-match_prefix-first
        for w in reg.windows(2) {
            assert!(w[0].match_prefix.len() >= w[1].match_prefix.len());
        }
    }

    // ── (CIRISPersist#590) — the vendor-drift witnesses ──────────

    /// **The equality that caught CC's own incident.** `_meta.n_families` is a
    /// number the generator writes; `families[]` is what it actually emitted.
    /// The four-family drop showed up as nothing else — the two disagreeing is
    /// the whole signal, and it was nearly reconciled away by hand. Assert it,
    /// and assert no prefix appears twice (a duplicate would let the count
    /// match while a distinct family was lost).
    #[test]
    fn manifest_row_count_equals_meta_and_carries_no_duplicates() {
        use std::collections::BTreeSet;
        let raw: RawManifest = serde_json::from_str(REGISTRY_JSON).unwrap();
        assert_eq!(
            raw.families.len(),
            raw.meta.n_families,
            "MANIFEST SELF-CONTRADICTION (CIRISPersist#590): families[] has {} rows but \
             _meta.n_families says {}. This exact discrepancy — and nothing else — was the only \
             signal when CC's generator silently dropped four families to a prose paragraph \
             inserted mid-table. Do not reconcile the number; find the missing rows.",
            raw.families.len(),
            raw.meta.n_families
        );
        let mut seen: BTreeSet<&str> = BTreeSet::new();
        for f in &raw.families {
            assert!(
                seen.insert(f.prefix.as_str()),
                "duplicate family prefix {:?} — a duplicate lets _meta.n_families balance while a \
                 distinct family is missing",
                f.prefix
            );
        }
    }

    /// **The removal direction.** Every prefix the pinned
    /// [`VENDORED_FAMILY_PREFIXES`] list carries must still be in the manifest.
    /// Additions are free; a disappearance fails BY NAME and is cleared only by
    /// moving the line to [`RETIRED_FAMILIES`] — a diff a reviewer has to read.
    #[test]
    fn no_vendored_family_silently_disappears() {
        use std::collections::BTreeSet;
        let raw: RawManifest = serde_json::from_str(REGISTRY_JSON).unwrap();
        let live: BTreeSet<&str> = raw.families.iter().map(|f| f.prefix.as_str()).collect();
        let retired: BTreeSet<&str> = RETIRED_FAMILIES.iter().copied().collect();
        let missing: Vec<&&str> = VENDORED_FAMILY_PREFIXES
            .iter()
            .filter(|p| !live.contains(*p) && !retired.contains(*p))
            .collect();
        assert!(
            missing.is_empty(),
            "VENDOR DRIFT — REMOVAL (CIRISPersist#590): {} pinned famil(ies) vanished from the \
             re-vendored manifest: {missing:?}. A family that disappears takes its reserved rule \
             with it, so CC-reserved traffic starts admitting under the ProducerSteward fallback \
             (CC 3.1.7 R2) and R2(b) starts refusing rows it should not. If the removal is \
             INTENDED, move each line from VENDORED_FAMILY_PREFIXES to RETIRED_FAMILIES with a CC \
             reference. If it is not, the generator lost them — CC's first R2 regeneration lost \
             four to a prose paragraph inserted mid-markdown-table.",
            missing.len()
        );
        // The pin must not itself rot: a family in BOTH lists is a
        // contradiction ("retired" and "still expected" at once).
        for p in RETIRED_FAMILIES {
            assert!(
                !VENDORED_FAMILY_PREFIXES.contains(p),
                "{p:?} is in RETIRED_FAMILIES and VENDORED_FAMILY_PREFIXES at once"
            );
            assert!(
                !live.contains(p),
                "{p:?} is listed RETIRED but the manifest still carries it — un-retire it"
            );
        }
    }

    /// The pinned list is a list of REAL prefixes and is kept in sync in the
    /// cheap direction too: it should describe the cut it ships with, so an
    /// out-of-date pin (many additions un-recorded) is visible at a glance
    /// rather than accumulating until the removal gate is meaningless.
    #[test]
    fn pinned_family_list_matches_this_vendored_cut() {
        use std::collections::BTreeSet;
        let raw: RawManifest = serde_json::from_str(REGISTRY_JSON).unwrap();
        let live: BTreeSet<&str> = raw.families.iter().map(|f| f.prefix.as_str()).collect();
        let pinned: BTreeSet<&str> = VENDORED_FAMILY_PREFIXES.iter().copied().collect();
        assert_eq!(
            pinned.len(),
            VENDORED_FAMILY_PREFIXES.len(),
            "VENDORED_FAMILY_PREFIXES contains a duplicate"
        );
        let unpinned: Vec<&&str> = live.difference(&pinned).collect();
        assert!(
            unpinned.is_empty(),
            "the vendored manifest carries famil(ies) the pin does not list: {unpinned:?} — add \
             them to VENDORED_FAMILY_PREFIXES so the removal gate keeps covering them"
        );
    }

    /// **A transcription that was uncheckable is now checked, and it checks.**
    ///
    /// [`PRIVATE_USE_FAMILY_STEM`](crate::federation::admission::PRIVATE_USE_FAMILY_STEM)
    /// shipped as a hand-transcription of CC 3.1.7 R2's Private Use prose, with
    /// its own doc naming the remedy: a `_meta` key in the generated manifest.
    /// The rc3 cut carries that key. So the const and the artifact are bound
    /// here, in the direction that matters — if CC moves the range, this fails
    /// rather than persist quietly refusing federation traffic on a stem CC no
    /// longer reserves, or quietly admitting on one it newly does.
    ///
    /// Same shape as `family_rules::RULES_NOT_ON_THE_ROW` and
    /// `quarantine::NAMESPACE_FAMILY`'s measured count: a claim persist repeats
    /// about CC should be one CC's own artifact can contradict.
    #[test]
    fn the_private_use_range_is_machine_readable_now() {
        let from_manifest = vendored_private_use_prefix().expect(
            "the rc3 cut carries `_meta.private_use_prefix`. `None` here means the manifest was \
             re-vendored BACKWARDS to a cut generated before CC shipped the field — check the \
             source hash before assuming CC removed it.",
        );
        assert_eq!(
            from_manifest,
            crate::federation::admission::PRIVATE_USE_FAMILY_STEM,
            "the hand-transcribed Private Use stem and CC's own machine-readable range disagree. \
             CC is the source of truth: update PRIVATE_USE_FAMILY_STEM, and re-read every \
             `x_private:` site with it — the federation-tier ban, the promotion gate, and \
             `regime.rs`'s reasoning about why the range was rejected as a home for `regime:*`."
        );
    }

    /// `family_stem` is the R2 granularity: up to and including the first `:`.
    #[test]
    fn family_stem_cuts_at_the_first_colon() {
        assert_eq!(family_stem("objection:raised:v1"), "objection:");
        assert_eq!(family_stem("objection:{state}"), "objection:");
        assert_eq!(family_stem("accord:*"), "accord:");
        assert_eq!(family_stem("scores"), "scores");
        assert_eq!(family_stem(""), "");
        assert_eq!(
            family_stem("detection:distributive:access:x:v1"),
            "detection:"
        );
    }

    /// R2's registration predicate over the real manifest — including the three
    /// families persist itself minted, which is the whole reason #590 exists.
    ///
    /// v50.0.0 (CIRISPersist#924): answered by the one matcher, so it is no
    /// longer first-colon-stem granular. A leaf CC does not name under the
    /// CLOSED `accord:*`, or an unclaimed leaf under a stem CC 3.4 reserves as
    /// a whole, is NOT registered (CC 3.1.7 R2(b)/R3) — the two lines that
    /// used to assert the opposite now sit in the negative list.
    #[test]
    fn is_family_registered_answers_from_the_manifest() {
        for dim in [
            "objection:raised:v1",
            "quarantine:withheld:v1",
            "wa_adjudication:petition:v1",
            "accord:lifecycle:v1",
            "accord:invoke:notify:n42:v1",
            "capacity:core_identity:v1",
            // open vocabulary WITHIN a registered family stays registered —
            // this is the traffic R2 explicitly preserves (and a missing
            // version is the T3 gate's refusal, not R2's).
            "credits:rust:en:someone",
            "credits:rust:en:someone:v1",
        ] {
            assert!(is_family_registered(dim), "{dim} must be registered");
        }
        for dim in [
            "totally:made:up:v1",
            "",
            "scores",
            "accord:invoke:halt",
            "detection:emergent_pattern:novel_signal:v1",
        ] {
            assert!(!is_family_registered(dim), "{dim} must NOT be registered");
        }
        assert!(is_stem_registered("objection:"));
        assert!(!is_stem_registered("scores:"));
        assert!(!is_stem_registered(""));
    }

    /// **The redundancy `RawFamily` bets on.** Its comment says the manifest's
    /// `reserved` bool "is redundant with `reserved_rule` presence", and on that
    /// basis serde **ignores `reserved` entirely**. If CC ever ships
    /// `reserved: true` with no `reserved_rule`, persist reads that family as
    /// OPEN while the manifest asserts it is reserved — a reservation dropped on
    /// the floor by a parser doing what its comment promised.
    ///
    /// Perfectly correlated on this cut, zero rows in either direction. The bet
    /// is sound; this is what makes it a checked bet rather than an assumption.
    #[test]
    fn reserved_bool_and_reserved_rule_presence_are_redundant() {
        let raw: RawManifest = serde_json::from_str(REGISTRY_JSON).unwrap();
        let root: serde_json::Value = serde_json::from_str(REGISTRY_JSON).unwrap();
        let rows = root["families"].as_array().expect("families array");
        assert_eq!(rows.len(), raw.families.len());
        let mut asserted_but_unruled: Vec<&str> = Vec::new();
        let mut ruled_but_unasserted: Vec<&str> = Vec::new();
        for row in rows {
            let prefix = row["prefix"].as_str().expect("prefix");
            let flag = row
                .get("reserved")
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            let has_rule = row.get("reserved_rule").is_some_and(|v| !v.is_null());
            if flag && !has_rule {
                asserted_but_unruled.push(prefix);
            }
            if has_rule && !flag {
                ruled_but_unasserted.push(prefix);
            }
        }
        assert!(
            asserted_but_unruled.is_empty(),
            "{asserted_but_unruled:?} carry `reserved: true` with NO `reserved_rule`. serde \
             ignores the bool, so `authority_for` reports these families OPEN while the manifest \
             says they are reserved — a reservation silently dropped at the parser. Either CC \
             must land the rule, or RawFamily must stop ignoring the bool."
        );
        assert!(
            ruled_but_unasserted.is_empty(),
            "{ruled_but_unasserted:?} carry a `reserved_rule` but `reserved: false` — the \
             manifest contradicts itself about whether the family is reserved"
        );
    }

    /// **The prose-only emitter rules, MEASURED** (CIRISPersist#571).
    ///
    /// Several rc3 rows state an emitter restriction in `description` while
    /// generating no `reserved_rule`, so `authority_for` reports the family
    /// open and no substrate can enforce what CC wrote. `quarantine.rs` used to
    /// call itself *"the only one of 109"*; the re-vendor made that four of 114
    /// while the sentence still read as freshly checked — a claim rotting in the
    /// direction that looks verified, which is the class
    /// `manifest_absence_claims_still_hold` exists for.
    ///
    /// Both numbers are recomputed from the vendored bytes here, so the doc
    /// comments that cite them cannot drift without failing the build.
    ///
    /// The finding is NOT "four unlucky rows": every one of them is in CC
    /// 3.1.9.2, and **no** family in that section carries a rule. CC's generator
    /// sources reserved rules from CC 3.4 plus a `Reserved?` table column, and
    /// 3.1.9.2's table has neither — so the governance-steering tier is
    /// structurally unable to carry an enforceable emitter rule. That is the CC
    /// ask, and this test states it as a measurement rather than a belief.
    ///
    /// Deliberately a keyword scan over prose — which persist must NEVER do for
    /// enforcement (CC 3.1.7 R2 forbids exactly that, and nothing on any
    /// admission path reads `description`). Here it is pointed at persist's own
    /// documentation, and the assertion is only ever "re-read the rows", never
    /// "admit or refuse this traffic".
    #[test]
    fn the_prose_only_emitter_rules_are_still_confined_to_cc_3_1_9_2() {
        let prose_only: Vec<&NamespaceEntry> = entries()
            .iter()
            .filter(|e| e.authority.reserved.is_none())
            .filter(|e| {
                let d = e.description.to_lowercase();
                d.contains("-emitted") || d.contains("emitter") || d.contains("-only")
            })
            .collect();

        let names: Vec<&str> = prose_only.iter().map(|e| e.prefix.as_str()).collect();
        assert_eq!(
            prose_only.len(),
            4,
            "the prose-only emitter-rule population moved (now {}): {names:?}. If CC has landed a \
             rule, the count DROPS — delete the corresponding pin and write the gate. If a new row \
             arrived stating a rule nothing can parse, it joins the CC ask. Either way the doc \
             comments in quarantine.rs and regime.rs that cite this number must be re-read.",
            prose_only.len()
        );
        for e in &prose_only {
            assert_eq!(
                e.cc_section, "3.1.9.2",
                "{} states an unenforceable emitter rule from OUTSIDE CC 3.1.9.2 — the CC ask is \
                 currently scoped to that section's table shape, and this widens it",
                e.prefix
            );
        }

        // The structural claim the ask rests on: it is the SECTION, not the rows.
        let section: Vec<&NamespaceEntry> = entries()
            .iter()
            .filter(|e| e.cc_section == "3.1.9.2")
            .collect();
        assert_eq!(
            section.len(),
            12,
            "CC 3.1.9.2's family count moved — re-check the generator ask"
        );
        assert!(
            section.iter().all(|e| e.authority.reserved.is_none()),
            "a CC 3.1.9.2 family now carries a machine-readable rule — the section's table has \
             gained a `Reserved?` column or the generator a predicate. That is the fix this ask \
             wanted: re-check every prose-only pin."
        );
    }

    /// A `reserved_rule` with a null `cc_ref` (rc3's `trust:{job}:{version}`)
    /// parses, and resolves to the family's own catalogue section rather than
    /// an empty string that reads like a present-but-blank citation.
    #[test]
    fn null_cc_ref_resolves_to_the_catalogue_section() {
        let a = authority_for("trust:charter:v1");
        let r = a.reserved.expect("trust:{job} carries a reserved rule");
        assert!(!r.cc_ref.is_empty(), "cc_ref must never be an empty string");
        assert_eq!(r.cc_ref, "CC 3.1.1");
    }

    #[test]
    fn build_manifest_is_accord_co_scrub_like_canonical() {
        // The chicken/egg closer: an infra build-manifest dimension resolves to
        // the SAME accord-co-scrub authority as a canonical record.
        let a = authority_for("provenance:build_manifest:agent-3.2.1");
        assert_eq!(a.class, AuthorityClass::AccordCoScrub);
        assert!(a.class.is_trust_root());
    }

    #[test]
    fn substrate_self_report_prefixes_resolve_substrate_self() {
        for dim in [
            "audit_chain:hash_continuity",
            "corpus_health:n_eff_measurable",
            "federation_directory:replication_lag",
            "transport:ip",
            "delivery:mandatory",
        ] {
            let a = authority_for(dim);
            assert_eq!(
                a.class,
                AuthorityClass::SubstrateSelf,
                "{dim} must be substrate-self"
            );
            assert_eq!(a.reserved.as_ref().unwrap().cc_ref, "CC 3.4.3");
        }
    }

    #[test]
    fn accord_prefix_is_reserved_producer() {
        let a = authority_for("accord:invoke:halt");
        assert_eq!(a.class, AuthorityClass::ProducerSteward);
        let r = a.reserved.expect("accord:* carries a reserved rule");
        assert_eq!(r.cc_ref, "CC 3.4.1");
        assert_eq!(r.rule, "accord_holder-only");
    }

    #[test]
    fn longest_prefix_wins() {
        // `provenance:build_manifest:` must beat a shorter `provenance:` match
        // if both are present — the sort guarantees the specific hit.
        let e = lookup("provenance:build_manifest:x").unwrap();
        assert!(e.match_prefix.starts_with("provenance:build_manifest"));
    }

    /// v50.0.0 (CIRISPersist#924) — `lookup` resolves through the ONE
    /// matcher, and the cases where the old longest-literal-prefix lookup
    /// answered differently are pinned (mutation M7 of the #924 round
    /// survived without this): two families sharing a literal stem
    /// (`credits:`, `provenance:build_manifest:`) used to resolve to whichever
    /// sorted first; a dimension off every row's arity used to inherit the
    /// stem's row; an unclaimed leaf under a reserved stem keeps its
    /// reservation through `authority_for`'s stem fallback.
    #[test]
    fn lookup_resolves_through_the_one_matcher_924() {
        let prefix = |d: &str| lookup(d).map(|e| e.prefix.as_str());
        assert_eq!(
            prefix("credits:rust:en:substrate_building:v1"),
            Some("credits:{domain}:{language}:substrate_building"),
            "the most literal family wins, not the alphabetically first"
        );
        assert_eq!(
            prefix("credits:rust:en:alice:v1"),
            Some("credits:{domain}:{language}:{subject}")
        );
        assert_eq!(
            prefix("provenance:build_manifest:agent-3.2.1:locale:en-US:v1"),
            Some("provenance:build_manifest:{target}:locale:{lang_code}")
        );
        assert_eq!(
            prefix("session:a:b:c:v1"),
            None,
            "off every row's arity is open vocabulary, not session:{{kind}}"
        );
        // An unclaimed leaf under a reserved stem: no row, so the stem's own
        // rule answers and the reservation is not dropped.
        let dim = "capacity_assurance:reversible_imagined:financial:v1";
        assert_eq!(prefix(dim), None, "no row claims an unminted leaf");
        let a = authority_for(dim);
        assert!(
            a.reserved.is_some_and(|r| r.cc_ref == "CC 3.4.12"),
            "the reserved stem's own rule answers, so the reservation is not dropped"
        );
        // The released rc5 registers the CC 3.4.12 companions: the row answers.
        let companion = "capacity_assurance:reversible_excluded:financial:v1";
        assert_eq!(
            prefix(companion),
            Some("capacity_assurance:reversible_excluded:{domain}:{version}")
        );
        assert!(authority_for(companion)
            .reserved
            .is_some_and(|r| r.cc_ref == "CC 3.4.12"));
    }

    #[test]
    fn unknown_dimension_defaults_to_producer_no_reserved() {
        let a = authority_for("totally:made:up:dimension");
        assert_eq!(a.class, AuthorityClass::ProducerSteward);
        assert!(a.reserved.is_none());
        assert!(lookup("totally:made:up:dimension").is_none());
    }

    /// v38.0.0 (CIRISPersist#724) — **nothing could notice an unread
    /// manifest column.** The `polarity` column shipped in the vendored
    /// registry and sat unread for five weeks across three vendorings,
    /// because `RawFamily` deserializes a SUBSET of the row and serde
    /// silently drops the rest (deliberately — `deny_unknown_fields` would
    /// make every future CC column addition a hard break, and the
    /// optional-column-over-panic rationale above stands). This closes the
    /// noticing gap without closing the compatibility door: every column
    /// the artifact actually carries must be deserialized by [`RawFamily`],
    /// read elsewhere (named below with its reader), or deliberately inert
    /// (named below with WHY). A new CC column reds this test until a human
    /// decides which it is — which is the entire ask of #724.
    #[test]
    fn every_manifest_family_column_has_a_reader_724() {
        // Columns RawFamily deserializes — a hand pin; if RawFamily gains a
        // field this list is one line away and the test names the file.
        const DESERIALIZED: &[&str] = &[
            "prefix",
            "owning_component",
            "owning_repo",
            "cc_section",
            "description",
            "reserved_rule",
            // v42.0.0 (CC 3.1.7 R3, CIRISPersist#815) — the per-segment case
            // classes, deserialized into `NamespaceEntry::segments` and read by
            // `admission::check_dimension_case_rule`.
            "segments",
        ];
        // Columns read OUTSIDE the shared type, each naming its reader.
        const READ_ELSEWHERE: &[(&str, &str)] = &[
            (
                "polarity",
                "scores_read_audit.rs#vendored_family_polarities (local parse, documented \
                 at that site) + the #724 cross-manifest agreement gate",
            ),
            // v50.0.0 (CIRISPersist#924, CC 3.1.7 R2(b)/R3) — a reserved
            // wildcard family's published leaves and whether they are closed.
            (
                "leaves",
                "namespace/matcher.rs#parse_rules -> Fam::leaves (match_family)",
            ),
            (
                "leaves_closed",
                "namespace/matcher.rs#parse_rules -> Fam::leaves_closed (match_family)",
            ),
        ];
        // Columns deliberately inert, each naming WHY — the subtractive
        // manifest: a rationale under 40 chars is a shrug, not a reason.
        const DELIBERATELY_UNREAD: &[(&str, &str)] = &[(
            "reserved",
            "redundant with reserved_rule presence by construction; the redundancy itself \
             is what RawFamily's field comment pins, and reading both would mint a second \
             spelling of one fact",
        )];

        for (_, why) in DELIBERATELY_UNREAD {
            assert!(
                why.len() > 40,
                "a rationale under 40 chars is a shrug: {why:?}"
            );
        }

        let manifest: serde_json::Value = serde_json::from_str(REGISTRY_JSON).unwrap();
        let mut carried: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
        for fam in manifest["families"].as_array().unwrap() {
            for k in fam.as_object().unwrap().keys() {
                carried.insert(k.as_str());
            }
        }
        assert!(carried.len() >= 6, "vacuous gate: {carried:?}");

        let accounted: std::collections::BTreeSet<&str> = DESERIALIZED
            .iter()
            .copied()
            .chain(READ_ELSEWHERE.iter().map(|(c, _)| *c))
            .chain(DELIBERATELY_UNREAD.iter().map(|(c, _)| *c))
            .collect();
        let unaccounted: Vec<&&str> = carried
            .iter()
            .filter(|c| !accounted.contains(**c))
            .collect();
        assert!(
            unaccounted.is_empty(),
            "the vendored registry carries column(s) nothing reads and nobody has declared \
             inert: {unaccounted:?}. Read it, name its reader, or record why it is inert — \
             an unread manifest column is a claim the substrate silently ignores (#724)."
        );
        // Both directions: an accounted column the artifact no longer
        // carries is a stale pin.
        let stale: Vec<&&str> = accounted
            .iter()
            .filter(|c| !carried.contains(**c))
            .collect();
        assert!(stale.is_empty(), "stale column pin(s): {stale:?}");

        // v50.0.0 (CIRISPersist#924, CIRISConstitution#112 ask 2) — the same
        // accounting over `_meta`, `_meta.case_rule`, its `version_segment`,
        // and the per-segment keys. rc5 moved the GRAMMAR into these; an
        // unread key there is a rule the substrate silently ignores.
        let meta = &manifest["_meta"];
        let cr = &meta["case_rule"];
        account(
            "_meta",
            meta,
            &[
                (
                    "cc_version",
                    "RawMeta::cc_version (VENDORED_CC_VERSION drift gate)",
                ),
                (
                    "source_sha256",
                    "RawMeta::source_sha256 (VENDORED_SOURCE_SHA256)",
                ),
                (
                    "n_families",
                    "RawMeta::n_families (the #590 self-consistency gate)",
                ),
                (
                    "private_use_prefix",
                    "RawMeta::private_use_prefix + matcher::parse_rules",
                ),
                (
                    "row_types",
                    "RawMeta::row_types -> registry::row_types() (CC 2.4: vendored and \
                     parsed; the allowlist is not enforced here — CIRISPersist#975)",
                ),
                (
                    "case_rule",
                    "matcher::parse_rules (the grammar) — accounted key by key below",
                ),
                (
                    "registry_sha256",
                    "tests::vendored_registry_sha256_pins_the_cc_file (VENDORED_REGISTRY_SHA256)",
                ),
            ],
            &[
                (
                    "generator",
                    "provenance of the CC build tool; the bytes it produced are pinned by \
                     registry_sha256, so naming the tool adds nothing enforceable",
                ),
                (
                    "source",
                    "the CC source path the rows were generated from; the source bytes are \
                     pinned by source_sha256 and the grammar by registry_sha256",
                ),
                (
                    "n_components",
                    "a count of owning_component slugs — a CC-side summary with no rule \
                     attached; persist keys nothing on component counts",
                ),
                (
                    "n_components_normative",
                    "the normative subset of n_components — a CC-side summary persist does not \
                     key on; normativity of a FAMILY rides its rows, not this count",
                ),
                (
                    "per_component",
                    "per-component family counts — CC's own bookkeeping; the family set itself \
                     is pinned row by row in VENDORED_FAMILY_PREFIXES",
                ),
                (
                    "components_outside_normative",
                    "which owning components are non-normative (cirisbench) — informational; \
                     no admission rule reads a component's normativity",
                ),
            ],
        );
        account(
            "_meta.case_rule",
            cr,
            &[
                ("vocab_pattern", "matcher::parse_rules -> Rules::vocab"),
                (
                    "refusal_tokens",
                    "matcher::parse_rules -> Rules::tokens (Refusal::as_str)",
                ),
                (
                    "reserved_stems",
                    "matcher::parse_rules -> reserved_stems / reserved_stem_rules",
                ),
                (
                    "version_segment",
                    "matcher::parse_rules -> version / exempt / version_required",
                ),
                (
                    "external_standards",
                    "matcher::parse_rules -> Rules::external",
                ),
                (
                    "literal_pattern",
                    "tests::every_literal_segment_matches_the_literal_pattern (a CC build gate, \
                     re-checked here; literals themselves compare by byte equality)",
                ),
                (
                    "refusal_token",
                    "tests::the_singular_refusal_token_is_the_case_malformed_token (the pre-rc5 \
                     key, pinned equal to refusal_tokens.case_malformed)",
                ),
                (
                    "wildcard_rule",
                    "tests::the_wildcard_rule_is_the_variadic_one_the_matcher_implements",
                ),
                (
                    "match_semantics",
                    "matcher::compile (every pattern wrapped `^(?:p)$`) + \
                     matcher::tests::the_manifest_declares_full_match_semantics",
                ),
            ],
            &[
                (
                    "cc_ref",
                    "the CC clause citation for the rule block (CC 3.1.7 R3) — a citation, not \
                     a rule; the FSD and evidence rows cite it",
                ),
                (
                    "classes",
                    "prose glosses of the six segment classes; the classes themselves are read \
                     per segment from families[].segments[].class",
                ),
                (
                    "compare",
                    "prose (\"byte-exact; consumers MUST NOT case-fold\") — the matcher's \
                     byte-exact compare IS this rule, replayed by the 968 vectors",
                ),
                (
                    "placeholder_classes",
                    "the generator's INPUT table; its output is copied onto every segment's \
                     class, which is what the matcher reads — reading both would be two \
                     spellings of one fact",
                ),
                (
                    "policy",
                    "a one-line prose summary of the case policy; every clause of it is a key \
                     the matcher reads",
                ),
            ],
        );
        account(
            "_meta.case_rule.version_segment",
            &cr["version_segment"],
            &[
                (
                    "pattern",
                    "matcher::parse_rules -> Rules::version (is_version_segment)",
                ),
                (
                    "exempt",
                    "matcher::parse_rules -> Rules::exempt (is_version_exempt)",
                ),
                (
                    "required",
                    "matcher::parse_rules -> Rules::version_required",
                ),
                (
                    "position",
                    "tests::the_wildcard_rule_is_the_variadic_one_the_matcher_implements pins \
                     it `trailing` (matcher::trailing_version)",
                ),
            ],
            &[(
                "note",
                "the prose statement of the rule the other four keys carry as data",
            )],
        );
        let mut seg_keys = serde_json::Map::new();
        for fam in manifest["families"].as_array().unwrap() {
            for seg in fam["segments"].as_array().unwrap() {
                for (k, v) in seg.as_object().unwrap() {
                    seg_keys.insert(k.clone(), v.clone());
                }
            }
        }
        account(
            "families[].segments[]",
            &serde_json::Value::Object(seg_keys),
            &[
                ("segment", "RawSegment::segment + matcher::parse_rules"),
                ("class", "RawSegment::class + matcher::parse_rules"),
                ("pattern", "matcher::parse_rules -> Seg::pattern"),
                (
                    "values",
                    "matcher::parse_rules -> Seg::values (closed enumerations)",
                ),
                ("open", "matcher::parse_rules -> Seg::open"),
                ("multi", "matcher::parse_rules -> Seg::multi"),
                (
                    "variadic",
                    "tests::the_wildcard_rule_is_the_variadic_one_the_matcher_implements (every \
                     wildcard segment carries variadic: true)",
                ),
            ],
            &[(
                "standard",
                "the NAME of the outside standard an external segment follows (ISO 4217) — \
                 prose; the enforceable part is its pattern, which the matcher reads",
            )],
        );

        fn account(
            what: &str,
            obj: &serde_json::Value,
            read: &[(&str, &str)],
            inert: &[(&str, &str)],
        ) {
            for (_, why) in inert {
                assert!(
                    why.len() > 40,
                    "a rationale under 40 chars is a shrug: {why:?}"
                );
            }
            let carried: std::collections::BTreeSet<&str> = obj
                .as_object()
                .unwrap_or_else(|| panic!("{what} is not an object"))
                .keys()
                .map(String::as_str)
                .collect();
            let accounted: std::collections::BTreeSet<&str> =
                read.iter().chain(inert).map(|(k, _)| *k).collect();
            let unaccounted: Vec<&&str> = carried.difference(&accounted).collect();
            assert!(
                unaccounted.is_empty(),
                "{what} carries key(s) nothing reads and nobody has declared inert: \
                 {unaccounted:?} (#724 / #924)"
            );
            let stale: Vec<&&str> = accounted.difference(&carried).collect();
            assert!(stale.is_empty(), "{what}: stale key pin(s) {stale:?}");
        }
    }

    /// v50.0.0 (CIRISPersist#924) — CC build-gates every literal stem against
    /// `_meta.case_rule.literal_pattern`; persist re-checks it on the vendored
    /// bytes, because the matcher compares literals by equality and would
    /// silently carry a miscased stem.
    #[test]
    fn every_literal_segment_matches_the_literal_pattern() {
        let root: serde_json::Value = serde_json::from_str(REGISTRY_JSON).unwrap();
        let pat = regex::Regex::new(
            root["_meta"]["case_rule"]["literal_pattern"]
                .as_str()
                .unwrap(),
        )
        .unwrap();
        for e in entries() {
            for (seg, class) in &e.segments {
                if *class == SegmentClass::Literal {
                    assert!(pat.is_match(seg), "{}: literal {seg:?}", e.prefix);
                }
            }
        }
    }

    /// The pre-rc5 singular `refusal_token` must still name the case token.
    #[test]
    fn the_singular_refusal_token_is_the_case_malformed_token() {
        let root: serde_json::Value = serde_json::from_str(REGISTRY_JSON).unwrap();
        let cr = &root["_meta"]["case_rule"];
        assert_eq!(cr["refusal_token"], cr["refusal_tokens"]["case_malformed"]);
    }

    /// The matcher implements a VARIADIC trailing `*` and a TRAILING version
    /// segment; the manifest says so in data, and this pins the two together.
    #[test]
    fn the_wildcard_rule_is_the_variadic_one_the_matcher_implements() {
        let root: serde_json::Value = serde_json::from_str(REGISTRY_JSON).unwrap();
        let cr = &root["_meta"]["case_rule"];
        assert_eq!(cr["wildcard_rule"]["match"], "one_or_more_segments");
        assert_eq!(cr["version_segment"]["position"], "trailing");
        let mut wildcards = 0;
        for fam in root["families"].as_array().unwrap() {
            for seg in fam["segments"].as_array().unwrap() {
                if seg["class"] == "wildcard" {
                    wildcards += 1;
                    assert_eq!(seg["variadic"], true, "{}", fam["prefix"]);
                    assert_eq!(seg["segment"], "*");
                }
            }
        }
        assert!(wildcards >= 10, "vacuous: {wildcards}");
    }
}
