//! v21.5.0 (CIRISPersist#519) — the per-family **placement + invariant**
//! manifest (`namespace_supersets.json`), vendored as Registry-of-Record.
//!
//! Where [`super::registry`] (`namespace_registry.json`) says WHICH claim
//! families exist, this manifest says — per family — WHERE each
//! contextual-integrity field is placed (the `field_processor_matrix`), WHAT
//! constitutional invariants a primitive must honor (the `invariant_registry`),
//! and which placement-touching primitives are currently INCOMPLETE (the
//! `primitive_gap_report`). It is generated by a constitution-grounded semantic
//! walk (CI six-axis rubric + per-family invariants); **CC + the constitution
//! are the source of truth**, this file is vendored + drift-witnessed, and —
//! per #519 governance — **the list lives in persist**: changes to any family's
//! placement/invariants arrive as CIRISPersist issues, land as a
//! [`VENDORED_MANIFEST_VERSION`] bump, and downstream (server / edge / agent /
//! client) repins. The server-side FSD copy is a downstream render, not a source.
//!
//! # Drift control
//!
//! [`VENDORED_MANIFEST_VERSION`] / [`VENDORED_CONSTITUTION_REV`] /
//! [`VENDORED_SEED_REGISTRY_SHA256`] pin the exact cut. The gate test
//! [`tests::vendored_supersets_manifest_is_pinned`] fails the build when the
//! compiled-in manifest moves without a deliberate const bump — the same
//! discipline [`super::registry`] runs. [`VENDORED_SEED_REGISTRY_SHA256`]
//! MUST equal [`super::registry::VENDORED_SOURCE_SHA256`]: the supersets walk
//! is seeded FROM the namespace registry, so a supersets cut that names a
//! different registry source is incoherent by construction.
//!
//! # What persist consumes today (and what it does not)
//!
//! This cut vendors the WHOLE manifest + wires the pieces persist can act on
//! now: the `field_processor_matrix` (drives the promotion-primitive
//! completeness gate — [`persist_placement_fields`]) and the recorded gap
//! inventory (`primitive_gap_report`, the single `deletion_window` `UNASSIGNED`
//! row). The larger asks the manifest also carries — hoisting `delivery_mode` /
//! `deletion_window` into typed `EnvelopeCore` fields (#519 item 2), the total
//! transform algebra (2a-ii), the signed `fresh_as_of` floor (2a-iii), the
//! evidence-registry loop (item 6), and the 7-family CC amendment (coverage
//! gap) — are wire-affecting and/or cross-repo and are tracked as follow-ups,
//! not built here.

use serde::Deserialize;
use std::sync::OnceLock;

const SUPERSETS_JSON: &str = include_str!("namespace_supersets.json");

/// The vendored manifest version (`_meta.manifest_version`). Bump DELIBERATELY
/// when re-vendoring a new walk.
pub const VENDORED_MANIFEST_VERSION: &str = "0.3.0";

/// The constitution revision the walk was grounded in (`_meta.sources.constitution_rev`).
pub const VENDORED_CONSTITUTION_REV: &str = "d192341";

/// The `namespace_registry.json` `source_sha256` the supersets walk was seeded
/// from — MUST equal [`super::registry::VENDORED_SOURCE_SHA256`] (a supersets
/// cut seeded from a different registry cut is incoherent).
pub const VENDORED_SEED_REGISTRY_SHA256: &str =
    "ade64edccce493e99f2617d236b1dffd6b99e2dfae91a9a4c012c9f4dfd6c64b";

/// The KNOWN, TRACKED placement fields the manifest itself records as
/// `UNASSIGNED` (no typed field, no processor) — deferred to #519 item 2 /
/// 2a-iii (wire-affecting hoist, needs edge/server lockstep). Pinned so a
/// REGRESSION (a NEW unassigned field) fails the completeness gate, while these
/// declared gaps stay visible-not-silent.
pub const KNOWN_UNASSIGNED_FIELDS: &[&str] = &["deletion_window"];

#[derive(Debug, Deserialize)]
struct Meta {
    manifest_version: String,
    sources: MetaSources,
}

#[derive(Debug, Deserialize)]
struct MetaSources {
    /// A free-text provenance string of the form
    /// `"CIRISPersist vX (source_sha256 <hex>, CC ...)"` — we assert it names
    /// the registry cut persist vendors.
    namespace_registry: String,
    constitution_rev: String,
}

/// One `field_processor_matrix` row: a contextual-integrity placement field,
/// the component(s) that own it, and the named primitive/gate that processes it
/// (`path#symbol`, the evidence-registry pointer form).
#[derive(Debug, Clone, Deserialize)]
pub struct FieldProcessorRow {
    /// The placement field name (e.g. `cohort_scope`, `dimension`).
    pub field: String,
    /// `envelope_core_typed` | `untyped_extra` — whether the field is a typed
    /// `EnvelopeCore` field or lives in the signature-locked `extra` map.
    #[serde(default)]
    pub typing: String,
    /// The owning component(s), slash-joined (`edge/persist/server`), or
    /// `UNASSIGNED` for a field with no processor anywhere (a #519 item-2b
    /// release blocker).
    #[serde(default)]
    pub owner_component: String,
    /// The named processor (`path#symbol`) or `UNASSIGNED`.
    #[serde(default)]
    pub processor: String,
}

impl FieldProcessorRow {
    /// True iff `persist` is among this field's owning components.
    pub fn persist_owns(&self) -> bool {
        self.owner_component.split('/').any(|c| c == "persist")
    }
    /// True iff this row has no processor assigned anywhere.
    pub fn is_unassigned(&self) -> bool {
        self.owner_component == "UNASSIGNED" || self.processor == "UNASSIGNED"
    }
}

#[derive(Debug, Deserialize)]
struct RawManifest {
    #[serde(rename = "_meta")]
    meta: Meta,
    field_processor_matrix: Vec<FieldProcessorRow>,
}

fn parsed() -> &'static RawManifest {
    static PARSED: OnceLock<RawManifest> = OnceLock::new();
    PARSED.get_or_init(|| {
        serde_json::from_str(SUPERSETS_JSON)
            .expect("vendored namespace_supersets.json is valid RawManifest")
    })
}

/// The vendored manifest version string (`_meta.manifest_version`) — the
/// provenance a downstream consumer pins against [`VENDORED_MANIFEST_VERSION`].
pub fn manifest_version() -> &'static str {
    &parsed().meta.manifest_version
}

/// The constitution revision the walk was grounded in
/// (`_meta.sources.constitution_rev`).
pub fn constitution_rev() -> &'static str {
    &parsed().meta.sources.constitution_rev
}

/// The free-text provenance of the `namespace_registry` cut the supersets walk
/// was seeded from (`_meta.sources.namespace_registry`).
pub fn seed_registry_source() -> &'static str {
    &parsed().meta.sources.namespace_registry
}

/// The full `field_processor_matrix` — every placement field × owning
/// component × processor.
pub fn field_processor_matrix() -> &'static [FieldProcessorRow] {
    &parsed().field_processor_matrix
}

/// The distinct placement fields persist owns a processor for — the universe a
/// persist placement-touching primitive is measured "complete" against
/// ([`tests::promotion_primitive_carries_every_typed_persist_placement_field`]).
pub fn persist_placement_fields() -> Vec<&'static str> {
    let mut v: Vec<&str> = field_processor_matrix()
        .iter()
        .filter(|r| r.persist_owns() && !r.is_unassigned())
        .map(|r| r.field.as_str())
        .collect();
    v.sort_unstable();
    v.dedup();
    v
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Drift gate: the compiled-in manifest is the exact cut the consts pin,
    /// and it is coherently seeded from the registry cut persist vendors.
    #[test]
    fn vendored_supersets_manifest_is_pinned() {
        assert_eq!(
            manifest_version(),
            VENDORED_MANIFEST_VERSION,
            "manifest_version drift — re-vendor deliberately + bump the const"
        );
        assert_eq!(
            constitution_rev(),
            VENDORED_CONSTITUTION_REV,
            "constitution_rev drift"
        );
        assert!(
            seed_registry_source().contains(VENDORED_SEED_REGISTRY_SHA256),
            "supersets seed registry sha does not name the vendored namespace_registry cut: {}",
            seed_registry_source()
        );
        // Cross-manifest coherence: the supersets walk is seeded from EXACTLY
        // the namespace registry cut persist vendors.
        assert_eq!(
            VENDORED_SEED_REGISTRY_SHA256,
            super::super::registry::VENDORED_SOURCE_SHA256,
            "supersets seed sha != registry source sha — the two vendored manifests \
             disagree on the CC cut"
        );
    }

    /// #519 item 2b — no placement field is silently unprocessed BEYOND the
    /// declared, tracked gap set. A NEW `UNASSIGNED` field (a regression) fails
    /// the build; the known `deletion_window` gap (deferred to the item-2 hoist)
    /// stays visible, not silent.
    #[test]
    fn unassigned_fields_match_the_known_tracked_gap_set() {
        let mut unassigned: Vec<&str> = field_processor_matrix()
            .iter()
            .filter(|r| r.is_unassigned())
            .map(|r| r.field.as_str())
            .collect();
        unassigned.sort_unstable();
        unassigned.dedup();
        let mut known = KNOWN_UNASSIGNED_FIELDS.to_vec();
        known.sort_unstable();
        assert_eq!(
            unassigned, known,
            "the manifest's UNASSIGNED placement fields changed. A NEW unassigned field is a \
             #519 item-2b release blocker — assign a processor or record it deliberately in \
             KNOWN_UNASSIGNED_FIELDS with a tracking issue."
        );
    }

    /// The completeness universe is non-empty and includes `cohort_scope` — the
    /// placement field the #315 / #519 promotion fix carries. Guards the
    /// promotion-primitive completeness gate against an empty/incoherent matrix.
    #[test]
    fn persist_owns_cohort_scope_placement() {
        let fields = persist_placement_fields();
        assert!(
            !fields.is_empty(),
            "persist owns at least one placement field"
        );
        assert!(
            fields.contains(&"cohort_scope"),
            "cohort_scope must be a persist-owned placement field (the promotion carries it): {fields:?}"
        );
    }
}
