//! v21.5.0 (CIRISPersist#519) — the per-family **placement + invariant**
//! manifest (`namespace_supersets.json`), vendored as Registry-of-Record.
//!
//! Where [`super::registry`] (`namespace_registry.json`) says WHICH claim
//! families exist, this manifest says — per family — WHERE each
//! contextual-integrity field is placed (the `field_processor_matrix`), WHAT
//! constitutional invariants a primitive must honor (the `invariant_registry`),
//! and which placement-touching primitives are currently INCOMPLETE (the
//! `primitive_gap_report`). It is generated by a constitution-grounded semantic
//! walk (CI six-axis rubric + per-family invariants); **CC + the constitution
//! are the source of truth**, this file is vendored + drift-witnessed, and —
//! per #519 governance — **the list lives in persist**: changes to any family's
//! placement/invariants arrive as CIRISPersist issues, land as a
//! [`VENDORED_MANIFEST_VERSION`] bump, and downstream (server / edge / agent /
//! client) repins. The server-side FSD copy is a downstream render, not a source.
//!
//! # Drift control
//!
//! [`VENDORED_MANIFEST_VERSION`] / [`VENDORED_CONSTITUTION_REV`] /
//! [`VENDORED_SEED_REGISTRY_SHA256`] pin the exact cut. The gate test
//! [`tests::vendored_supersets_manifest_is_pinned`] fails the build when the
//! compiled-in manifest moves without a deliberate const bump — the same
//! discipline [`super::registry`] runs. [`VENDORED_SEED_REGISTRY_SHA256`]
//! MUST equal [`super::registry::VENDORED_SOURCE_SHA256`]: the supersets walk
//! is seeded FROM the namespace registry, so a supersets cut that names a
//! different registry source is incoherent by construction.
//!
//! # What persist consumes today (and what it does not)
//!
//! This cut vendors the WHOLE manifest + wires the pieces persist can act on
//! now: the `field_processor_matrix` (drives the promotion-primitive
//! completeness gate — [`persist_placement_fields`]) and the recorded gap
//! inventory (`primitive_gap_report`, the single `deletion_window` `UNASSIGNED`
//! row). The larger asks the manifest also carries — hoisting `delivery_mode` /
//! `deletion_window` into typed `EnvelopeCore` fields (#519 item 2), the total
//! transform algebra (2a-ii), the signed `fresh_as_of` floor (2a-iii), the
//! evidence-registry loop (item 6), and the 7-family CC amendment (coverage
//! gap) — are wire-affecting and/or cross-repo and are tracked as follow-ups,
//! not built here.

use serde::Deserialize;
use std::sync::OnceLock;

const SUPERSETS_JSON: &str = include_str!("namespace_supersets.json");

/// The vendored manifest version (`_meta.manifest_version`). Bump DELIBERATELY
/// when re-vendoring a new walk.
pub const VENDORED_MANIFEST_VERSION: &str = "0.3.0";

/// The constitution revision the walk was grounded in (`_meta.sources.constitution_rev`).
pub const VENDORED_CONSTITUTION_REV: &str = "d192341";

/// The `namespace_registry.json` `source_sha256` the supersets walk was seeded
/// from — MUST equal [`super::registry::VENDORED_SOURCE_SHA256`] (a supersets
/// cut seeded from a different registry cut is incoherent).
pub const VENDORED_SEED_REGISTRY_SHA256: &str =
    "ade64edccce493e99f2617d236b1dffd6b99e2dfae91a9a4c012c9f4dfd6c64b";

/// The placement fields the vendored manifest (v0.3.0) records as `UNASSIGNED`.
/// Pinned so a REGRESSION (a NEW unassigned field) fails the completeness gate,
/// while the declared gap stays visible-not-silent.
///
/// NOTE (v21.9.0, #519 c1): `deletion_window` was hoisted to a typed
/// `EnvelopeCore` field AND given a persist-owned lifecycle processor
/// ([`crate::federation::deletion_window`]) — so it is no longer a real gap in
/// CODE. It stays listed here only because the vendored manifest's
/// `field_processor_matrix` still records the row as `UNASSIGNED`; the row
/// graduates to persist-owned at the next manifest RE-VENDOR (tracked #520,
/// bundled with the CC#43 re-vendor). Removing it from this list before the
/// re-vendor would fail `unassigned_fields_match_the_known_tracked_gap_set`
/// (the manifest and the const would disagree).
pub const KNOWN_UNASSIGNED_FIELDS: &[&str] = &["deletion_window"];

#[derive(Debug, Deserialize)]
struct Meta {
    manifest_version: String,
    sources: MetaSources,
}

#[derive(Debug, Deserialize)]
struct MetaSources {
    /// A free-text provenance string of the form
    /// `"CIRISPersist vX (source_sha256 <hex>, CC ...)"` — we assert it names
    /// the registry cut persist vendors.
    namespace_registry: String,
    constitution_rev: String,
}

/// One `field_processor_matrix` row: a contextual-integrity placement field,
/// the component(s) that own it, and the named primitive/gate that processes it
/// (`path#symbol`, the evidence-registry pointer form).
#[derive(Debug, Clone, Deserialize)]
pub struct FieldProcessorRow {
    /// The placement field name (e.g. `cohort_scope`, `dimension`).
    pub field: String,
    /// The value-space typing: `envelope_core_typed` (a typed `EnvelopeCore`
    /// field), `attestation_base_typed` (a typed `AttestationBase` column), or
    /// `untyped_extra` (the signature-locked `extra` map). Closed set gated by
    /// [`tests::typing_value_space_is_closed`].
    #[serde(default)]
    pub typing: String,
    /// The owning component(s), slash-joined (`edge/persist/server`), or
    /// `UNASSIGNED` for a field with no processor anywhere (a #519 item-2b
    /// release blocker).
    #[serde(default)]
    pub owner_component: String,
    /// The named processor (`path#symbol`) or `UNASSIGNED`.
    #[serde(default)]
    pub processor: String,
    /// v21.13.0 (CIRISPersist#532) — every named processor/gate that touches
    /// this field, NOT de-duplicated to the primary [`Self::processor`]. This
    /// is the multi-processor signal the axis-fusion class needs: a field
    /// whose distinct real processors span more than one CI axis is the
    /// `list_attestations`-shape overload (advertise-listing vs holdings-listing,
    /// CIRISEdge#416). Entries prefixed `proposed:` or containing `NOT LANDED`
    /// are design notes, not live processors — [`Self::distinct_real_processors`]
    /// filters them.
    #[serde(default)]
    pub processors_all: Vec<String>,
    /// v21.13.0 (CIRISPersist#532) — the manifest walk's fusion classification
    /// for this field's cross-axis reuse: `logical_defect` (a real overload — a
    /// processor answers two CI questions and one answer is wrong),
    /// `axiomatic_intent` (a deliberate, reviewed multi-role), `n/a` (benign
    /// co-occurrence), or empty (the walk left it unclassified — persist fills
    /// these via [`PERSIST_AUTHORED_AXIS_CLASSIFICATIONS`] pending CC ratification).
    #[serde(default)]
    pub asymmetry_kind: String,
    /// The rationale prose for [`Self::asymmetry_kind`] (the "reviewed exemption
    /// with a rationale" the fusion gate demands — CIRISPersist#532 gate 1).
    #[serde(default)]
    pub asymmetry_note: String,
}

impl FieldProcessorRow {
    /// True iff `persist` is among this field's owning components.
    pub fn persist_owns(&self) -> bool {
        self.owner_component.split('/').any(|c| c == "persist")
    }
    /// True iff this row has no processor assigned anywhere.
    pub fn is_unassigned(&self) -> bool {
        self.owner_component == "UNASSIGNED" || self.processor == "UNASSIGNED"
    }
    /// v21.13.0 (CIRISPersist#532) — the distinct LIVE processors touching this
    /// field. Un-de-dupes [`Self::processors_all`] (the raw list carries repo-
    /// prefixed and annotated variants of the same symbol), drops `proposed:` /
    /// `NOT LANDED` design notes and `UNASSIGNED`, normalizes a leading
    /// `CIRISPersist/` path prefix, and returns the distinct set. `>1` here is
    /// the multi-processor signal the pre-#532 `processors_all` accessor hid by
    /// collapsing to the single primary [`Self::processor`].
    pub fn distinct_real_processors(&self) -> Vec<String> {
        let mut all: Vec<String> = if self.processors_all.is_empty() {
            vec![self.processor.clone()]
        } else {
            self.processors_all.clone()
        };
        all.retain(|p| {
            let p = p.trim();
            !p.is_empty()
                && p != "UNASSIGNED"
                && !p.starts_with("proposed:")
                && !p.contains("NOT LANDED")
        });
        let mut norm: Vec<String> = all
            .iter()
            .map(|p| {
                p.trim()
                    .strip_prefix("CIRISPersist/")
                    .unwrap_or(p.trim())
                    .to_string()
            })
            .collect();
        norm.sort();
        norm.dedup();
        norm
    }
}

/// v21.6.0 (CIRISPersist#519 item 2a-iii) — the manifest's
/// `freshness_floor` section: the governance record for the signed
/// `fresh_as_of` freshness floor this cut builds the persist half of (the
/// `SignedTouchClaim` storage + monotonic-max merge live in
/// [`crate::federation::freshness`] / [`crate::federation::types`] /
/// [`crate::federation::admission`]). Kept deliberately lean — just the
/// fields the drift gate below cross-checks against the actual
/// implementation, not the full `demanded_by` / `decomposition` prose.
#[derive(Debug, Clone, Deserialize)]
pub struct FreshnessFloorSpec {
    /// The wire field name (`"fresh_as_of"`).
    pub canonical_field: String,
    /// The merge semantics (`"monotonic_max"`).
    pub merge_rule: String,
    /// The closed set of signer relationships (`self_touch` /
    /// `witness_touch` / `n_of_m_cosigned`) — mirrors
    /// [`crate::federation::types::SignerForm`]'s variants.
    #[serde(default)]
    pub signer_forms: Vec<String>,
    /// The admission-time future-skew rule, free text (e.g. `"reject >
    /// now+skew"`) — enforced by
    /// [`crate::federation::admission::verify_touch_claim_admission`].
    #[serde(default)]
    pub admission_guard: String,
    /// The wire-coalescing intent, free text — see
    /// [`crate::federation::freshness::coalesce_touch_ts`].
    #[serde(default)]
    pub coalescing: String,
}

#[derive(Debug, Deserialize)]
struct RawManifest {
    #[serde(rename = "_meta")]
    meta: Meta,
    field_processor_matrix: Vec<FieldProcessorRow>,
    freshness_floor: FreshnessFloorSpec,
}

fn parsed() -> &'static RawManifest {
    static PARSED: OnceLock<RawManifest> = OnceLock::new();
    PARSED.get_or_init(|| {
        serde_json::from_str(SUPERSETS_JSON)
            .expect("vendored namespace_supersets.json is valid RawManifest")
    })
}

/// The vendored manifest version string (`_meta.manifest_version`) — the
/// provenance a downstream consumer pins against [`VENDORED_MANIFEST_VERSION`].
pub fn manifest_version() -> &'static str {
    &parsed().meta.manifest_version
}

/// The constitution revision the walk was grounded in
/// (`_meta.sources.constitution_rev`).
pub fn constitution_rev() -> &'static str {
    &parsed().meta.sources.constitution_rev
}

/// The free-text provenance of the `namespace_registry` cut the supersets walk
/// was seeded from (`_meta.sources.namespace_registry`).
pub fn seed_registry_source() -> &'static str {
    &parsed().meta.sources.namespace_registry
}

/// The full `field_processor_matrix` — every placement field × owning
/// component × processor.
pub fn field_processor_matrix() -> &'static [FieldProcessorRow] {
    &parsed().field_processor_matrix
}

/// v21.6.0 (CIRISPersist#519 item 2a-iii) — the manifest's `freshness_floor`
/// governance record (`_meta` sibling `freshness_floor`), the ONE additive
/// accessor this cut adds to the vendored-manifest surface. Lets the
/// [`crate::federation::freshness`] / [`crate::federation::types::SignerForm`]
/// / [`crate::federation::admission::verify_touch_claim_admission`]
/// implementation cross-check itself against the governance source of
/// truth (see [`tests::freshness_floor_implementation_matches_manifest`])
/// instead of drifting from it silently.
pub fn freshness_floor_spec() -> &'static FreshnessFloorSpec {
    &parsed().freshness_floor
}

/// The distinct placement fields persist owns a processor for — the universe a
/// persist placement-touching primitive is measured "complete" against
/// ([`tests::promotion_primitive_carries_every_typed_persist_placement_field`]).
pub fn persist_placement_fields() -> Vec<&'static str> {
    let mut v: Vec<&str> = field_processor_matrix()
        .iter()
        .filter(|r| r.persist_owns() && !r.is_unassigned())
        .map(|r| r.field.as_str())
        .collect();
    v.sort_unstable();
    v.dedup();
    v
}

/// v21.6.0 (CIRISPersist#519 item 2a-ii) — the `field_transforms`
/// sub-manifest: the closed, total transform-opcode algebra plus the
/// per-family rows declaring which placement field undergoes which
/// transform on which egress path. Returned as the raw vendored
/// [`serde_json::Value`] — this module stays the single vendoring/parsing
/// point for `namespace_supersets.json`; the typed opcode algebra and the
/// per-family-row validator both live in [`crate::federation::transform`]
/// ([`crate::federation::transform::TransformOp`] /
/// [`crate::federation::transform::validate_family_transform_rows`]), the
/// ONE consumer of this accessor.
pub fn field_transforms() -> &'static serde_json::Value {
    static FIELD_TRANSFORMS: OnceLock<serde_json::Value> = OnceLock::new();
    FIELD_TRANSFORMS.get_or_init(|| {
        let root: serde_json::Value = serde_json::from_str(SUPERSETS_JSON)
            .expect("vendored namespace_supersets.json is valid JSON");
        root.get("field_transforms")
            .cloned()
            .expect("namespace_supersets.json carries a top-level field_transforms section")
    })
}

/// (CIRISPersist#519 item 3) — the `invariant_registry` section: a dict
/// keyed by CC 3.1 family prefix (`"accord:*"`, `"capacity:composite"`, …) →
/// an array of `{rule, cc_ref, quote, primitive_constraint}` constitutional
/// invariants for that family (104 families, 571 invariants in the v0.3.0
/// cut). Returned as the raw vendored [`serde_json::Value`] — this module
/// stays the single vendoring/parsing point for `namespace_supersets.json`;
/// the typed per-family reader and the admission-enforceable classifier both
/// live in [`crate::federation::invariant`]
/// ([`crate::federation::invariant::invariants_for`] /
/// [`crate::federation::invariant::admission_enforceable`]), the ONE
/// consumer of this accessor.
pub fn invariant_registry() -> &'static serde_json::Value {
    static INVARIANT_REGISTRY: OnceLock<serde_json::Value> = OnceLock::new();
    INVARIANT_REGISTRY.get_or_init(|| {
        let root: serde_json::Value = serde_json::from_str(SUPERSETS_JSON)
            .expect("vendored namespace_supersets.json is valid JSON");
        root.get("invariant_registry")
            .cloned()
            .expect("namespace_supersets.json carries a top-level invariant_registry section")
    })
}

// ─────────────────────────────────────────────────────────────────────────
// v21.13.0 (CIRISPersist#532) — the axis-fusion detector: "one name, two
// axes." The CI six-axis rubric that generated this manifest ALREADY records,
// per family, which wire field serves which axis
// (`families.*.round2.ci_axes.<axis>.wire_fields`). What the manifest did NOT
// do was JOIN that axis assignment onto the `field_processor_matrix` or GATE
// on it — so a field answering two different CI questions (one wrongly) was
// inexpressible on the matrix and invisible to CI. This section derives the
// join IN CODE from the single existing source (rule #9: the axis truth lives
// in exactly one place; a copied `ci_axis` column would drift) and the gate
// tests below make cross-axis reuse a build-visible, classified fact.
// ─────────────────────────────────────────────────────────────────────────

/// The closed CI rubric axis set. `sender` / `data_subject` / `recipient_see`
/// / `recipient_revoke` / `recipient_receive` / `information_type` /
/// `transmission_principle` / `temporal_lifecycle` are Nissenbaum's contextual-
/// integrity axes as the manifest's `ci_axes` keys them; `content` is the
/// non-CI payload catch-all (a field that serves no CI axis). The vocabulary is
/// gated closed by [`tests::ci_axis_vocabulary_is_closed`].
pub const CI_AXES: &[&str] = &[
    "sender",
    "data_subject",
    "recipient_see",
    "recipient_revoke",
    "recipient_receive",
    "information_type",
    "transmission_principle",
    "temporal_lifecycle",
    "content",
];

/// The closed fusion-classification vocabulary (`asymmetry_kind`).
/// `logical_defect` — a real overload a processor gets wrong (must split or be
/// tracked/fixed); `axiomatic_intent` — a deliberate, reviewed multi-role;
/// `n/a` — benign co-occurrence (a field supplies context to several axes, no
/// processor fuses them into a decision). Gated by
/// [`tests::asymmetry_kind_vocabulary_is_closed`].
pub const ASYMMETRY_KINDS: &[&str] = &["logical_defect", "axiomatic_intent", "n/a"];

/// v21.13.0 (CIRISPersist#532) — persist-authored fusion classifications for
/// the multi-axis `field_processor_matrix` fields the vendored v0.3.0 walk left
/// with an EMPTY `asymmetry_kind`. These are **PROPOSED, pending
/// CIRISConstitution ratification** — the CI rubric is the authority and these
/// fold into the next manifest walk (tracked #520 + CIRISConstitution#44).
/// Recorded here (not edited into the vendored Registry-of-Record) so the
/// fusion gate is complete NOW without a unilateral edit of the constitution's
/// artifact. `(field, kind, rationale)`; every entry is cross-checked to be a
/// real multi-axis matrix field the manifest left unclassified
/// ([`tests::persist_authored_classifications_cover_exactly_the_manifest_gaps`]).
/// Ratification is tracked at CIRISConstitution#44 (fold into the #520 re-vendor).
pub const PERSIST_AUTHORED_AXIS_CLASSIFICATIONS: &[(&str, &str, &str)] = &[
    // ── benign co-occurrence: value/timestamp/identifier fields that supply
    //    context to several axes, but no ONE processor decides an axis wrongly.
    ("achieved_tier", "n/a",
     "a tier value IS information_type; its progression over time IS temporal_lifecycle — the two roles co-occur on one immutable datum, no processor conflates them into a decision"),
    ("committed_tier", "n/a",
     "as achieved_tier: the committed tier is information_type content whose advance is temporal_lifecycle; benign co-occurrence"),
    ("asserted_at", "n/a",
     "a timestamp anchors both the temporal_lifecycle (when asserted) and the transmission context; a clock is not an authority — no processor spends it as one"),
    ("validity_window", "n/a",
     "a window is temporal_lifecycle data expressed as information_type; no processor reads it as anything but a time bound"),
    ("community_key_id", "n/a",
     "naming a community both identifies the content context (information_type) and selects that community's transmission norm — both are lookups of one identity, no wrong axis decision"),
    ("confidence", "n/a",
     "a confidence score is information_type the sender asserts; the sender/transmission co-occurrence is descriptive, never spent as authority"),
    ("context", "n/a",
     "free-form context supplies supporting information across data_subject/information_type/transmission; it is never the field a processor keys an axis decision on"),
    ("enabled", "n/a",
     "a boolean enable flag is temporal_lifecycle state read in a transmission decision; the flag is the state, not a second axis"),
    ("evidence_refs", "n/a",
     "an evidence pointer bundle legitimately touches every axis it cites (subject, info, sender, time, transmission); it is a reference list, not a decision field — no processor treats a ref as authority"),
    ("scope", "n/a",
     "here `scope` is the claim's coverage (information_type) with a downstream visibility implication; distinct from cohort_scope (which IS the logical_defect) — no persist processor fuses claim-scope with see-scope"),
    ("tenant_id", "n/a",
     "a tenant identifier names both the subject and the information context; one identity lookup serving two descriptive roles, not a fused decision"),
    ("withdrawal_reason", "n/a",
     "descriptive reason prose on a revoke; recipient_revoke + temporal_lifecycle co-occur because a withdrawal IS a timed revocation event — the reason text decides nothing"),
    // ── axiomatic_intent: the multi-role is deliberate and load-bearing; the
    //    action itself spans axes by definition, and each op uses the right one.
    ("withdraws", "axiomatic_intent",
     "a withdraws IS definitionally both a recipient_revoke action and a temporal_lifecycle transition — one coherent action, not two answers; the withdraws-authority arc (#517/#528) is the fusion to guard, and it is guarded on the SEPARATE subject_key_ids/attester axis, not here"),
    ("consent", "axiomatic_intent",
     "consent is definitionally a transmission_principle that also gates recipient_receive and carries a temporal_lifecycle — the spanning is the concept; the send-vs-receive fusion to watch is CIRISEdge#414's #396 gate, a DIRECTION overload downstream, not this substrate field"),
    ("references_attestation_id", "axiomatic_intent",
     "a pointer whose role is op-separated: withdraws/supersedes/recants read it as the recipient_revoke TARGET, structural composers as a temporal_lifecycle prior, subject-binding as data_subject — each op uses the correct axis; HIGHEST-risk benign member, the same pointer-decides-authority shape as #517/#528 — flagged for the CC rubric to confirm or split"),
];

/// v23.0.0 (CIRISPersist#551 item 2) — the manifest rows for the `trust:*`
/// dimension family: the three envelope dimensions that NAME which job a
/// `delegates_to` row does (charter / conferral / trust edge).
///
/// `trust:*` is a NEW family. It is **not** in the vendored CC 3.1 namespace
/// registry, and persist does not put it there: `namespace_registry.json` is
/// GENERATED by the Constitution's tooling (see [`super::registry`]), so
/// hand-adding a family would forge a constitutional record. The CC 3.1
/// registration is filed separately (#551 disposition item 2, batched with
/// CIRISConstitution#47); until it lands, the rows live HERE — the same
/// discipline [`PERSIST_AUTHORED_AXIS_CLASSIFICATIONS`] follows for the
/// classifications the vendored walk left blank: recorded in persist,
/// gate-tested, folded into the next re-vendor rather than edited into the
/// Registry-of-Record unilaterally.
///
/// `(dimension, direction, read_by, rationale)`. `direction` is the row shape
/// the dimension asserts, in `attesting → attested` terms — the thing that
/// used to be the ONLY discriminator and is now cross-checkable against the
/// label. [`tests::persist_authored_trust_dimensions_match_the_constants`]
/// binds every row to the live constant, so this table cannot drift from the
/// predicates that read it.
pub const PERSIST_AUTHORED_TRUST_JOB_DIMENSIONS: &[(&str, &str, &str, &str)] = &[
    (
        "trust:charter:v1",
        "R → R",
        "federation::trust_root::trust_root_valid#root_self_declares",
        "the root's self-declaration: a self-loop delegates_to carrying BOTH infra:serve and \
         infra:attest plus a pre-rotation commitment. The self-loop IS what makes a root a root, \
         so this row's direction and its authority are the same fact — which is exactly why an \
         unlabeled one was mistakable for the conferral pointing the other way",
    ),
    (
        "trust:confers:v1",
        "R → subject",
        "federation::trust_root::capability_roots_to_trusted_root_over_roster",
        "the capability grant: a scoped delegates_to from a root ONTO a subject. Points the \
         OPPOSITE way from the trust edge and is otherwise identical in shape — the pair #551 \
         reports as the costliest confusion (it produced the false claim that the canonical must \
         self-charter, made while reading the source)",
    ),
    (
        "trust:accepts:v1",
        "node → R",
        "federation::trust_root::trust_root_valid#edge_exists",
        "the user's own consensual trust edge — and the operator's un-trust lever: delete this \
         one row and the verdict collapses. A lever nobody can name is a lever nobody can find, \
         which is how #548's first proposed remedy came to delete it",
    ),
];

/// The `families` section (per-family CI-axis assignments live under
/// `families.<prefix>.round2.ci_axes.<axis>.wire_fields`). Raw
/// [`serde_json::Value`] — this module stays the single parse point for the
/// vendored manifest; [`field_ci_axes_map`] is the ONE consumer.
fn families() -> &'static serde_json::Value {
    static FAMILIES: OnceLock<serde_json::Value> = OnceLock::new();
    FAMILIES.get_or_init(|| {
        let root: serde_json::Value = serde_json::from_str(SUPERSETS_JSON)
            .expect("vendored namespace_supersets.json is valid JSON");
        root.get("families")
            .cloned()
            .expect("namespace_supersets.json carries a top-level families section")
    })
}

/// The bare wire-field name from an annotated `wire_fields` entry, e.g.
/// `"cohort_scope (Global/federation-wide only)"` → `"cohort_scope"`,
/// `"ThresholdSignature[]{member_id,...}"` → `"ThresholdSignature"`. Returns
/// `""` for an entry that does not start with an identifier.
fn bare_wire_field(s: &str) -> &str {
    let s = s.trim_start();
    let end = s
        .find(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
        .unwrap_or(s.len());
    &s[..end]
}

/// v21.13.0 (CIRISPersist#532) — the DERIVED join: `field name → the set of CI
/// axes it serves`, read out of every family's
/// `round2.ci_axes.<axis>.wire_fields`. A field mapping to more than one axis
/// is the fusion signal the gate classifies. Built once; the map borrows
/// `'static` axis names from [`CI_AXES`] so callers get cheap `&'static str`s.
fn field_ci_axes_map(
) -> &'static std::collections::BTreeMap<String, std::collections::BTreeSet<&'static str>> {
    static MAP: OnceLock<
        std::collections::BTreeMap<String, std::collections::BTreeSet<&'static str>>,
    > = OnceLock::new();
    MAP.get_or_init(|| {
        let mut map: std::collections::BTreeMap<String, std::collections::BTreeSet<&'static str>> =
            std::collections::BTreeMap::new();
        let fams = families();
        let Some(obj) = fams.as_object() else {
            return map;
        };
        for fam in obj.values() {
            let Some(ci_axes) = fam.get("round2").and_then(|r| r.get("ci_axes")) else {
                continue;
            };
            let Some(axes_obj) = ci_axes.as_object() else {
                continue;
            };
            for (axis_key, entry) in axes_obj {
                // Resolve the axis key to its `'static` spelling in CI_AXES so
                // the returned sets carry no owned strings.
                let Some(&axis) = CI_AXES.iter().find(|a| **a == axis_key.as_str()) else {
                    // An unknown axis key is caught by
                    // `ci_axis_vocabulary_is_closed`; skip it here.
                    continue;
                };
                let Some(wfs) = entry.get("wire_fields").and_then(|w| w.as_array()) else {
                    continue;
                };
                for wf in wfs {
                    let Some(wf) = wf.as_str() else { continue };
                    let name = bare_wire_field(wf);
                    if name.is_empty() {
                        continue;
                    }
                    map.entry(name.to_string()).or_default().insert(axis);
                }
            }
        }
        map
    })
}

/// The set of CI axes a placement `field` serves, derived from the manifest's
/// per-family `ci_axes.wire_fields` (CIRISPersist#532). Empty for a field that
/// names no CI axis (pure `content` payload). More than one axis is the
/// fusion signal [`tests::every_multi_axis_field_is_classified`] gates.
pub fn ci_axes_for_field(field: &str) -> std::collections::BTreeSet<&'static str> {
    field_ci_axes_map().get(field).cloned().unwrap_or_default()
}

/// The fusion classification for a placement `field`: the vendored manifest's
/// `asymmetry_kind`+note when the walk set one, else persist's proposed
/// [`PERSIST_AUTHORED_AXIS_CLASSIFICATIONS`] entry (pending CC ratification),
/// else `None` (an UNCLASSIFIED cross-axis field — a build failure under the
/// fusion gate). Returns `(kind, rationale)`.
pub fn fusion_classification(field: &str) -> Option<(&'static str, &'static str)> {
    // Manifest first (the authored Registry-of-Record wins over persist's proposal).
    if let Some(row) = field_processor_matrix().iter().find(|r| r.field == field) {
        if !row.asymmetry_kind.trim().is_empty() {
            // Return the `'static` spelling from ASYMMETRY_KINDS for the kind;
            // the note is borrowed from the parsed manifest ('static via OnceLock).
            let kind = ASYMMETRY_KINDS
                .iter()
                .find(|k| **k == row.asymmetry_kind.as_str())
                .copied()
                .unwrap_or("logical_defect");
            return Some((kind, row.asymmetry_note.as_str()));
        }
    }
    PERSIST_AUTHORED_AXIS_CLASSIFICATIONS
        .iter()
        .find(|(f, _, _)| *f == field)
        .map(|(_, kind, note)| (*kind, *note))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    /// v21.10.0 (CIRISPersist#519 b5 / item 6) — the evidence loop's persist
    /// half: every `path#symbol` in the materialized `evidence/cc_impl.tsv`
    /// that names a persist `src/…` path MUST resolve in the current source
    /// (the constitution's `check_evidence.py` enforces this cross-repo; this
    /// is the in-repo mirror that fails the build the moment a cited processor
    /// is renamed or deleted — the drift the a2 `promote_attestation_with_strips`
    /// rename would otherwise have left stale).
    #[test]
    fn evidence_cc_impl_pointers_resolve() {
        let tsv = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/evidence/cc_impl.tsv"));
        let mut rows = 0usize;
        for line in tsv.lines() {
            if line.starts_with('#') || line.starts_with("decimal_id") || line.trim().is_empty() {
                continue;
            }
            let cols: Vec<&str> = line.split('\t').collect();
            assert_eq!(
                cols.len(),
                5,
                "cc_impl.tsv row must have 5 columns: {line:?}"
            );
            rows += 1;
            let ps = cols[3];
            let Some((path, sym)) = ps.split_once('#') else {
                panic!("evidence pointer missing #symbol: {ps:?}");
            };
            // Only persist-owned `src/…` paths are resolvable here (external
            // crates like ciris-verify-core resolve at their own build).
            if !path.starts_with("src/") {
                continue;
            }
            let full = format!("{}/{}", env!("CARGO_MANIFEST_DIR"), path);
            let src = std::fs::read_to_string(&full)
                .unwrap_or_else(|e| panic!("evidence path {path} unreadable: {e}"));
            // Resolve the bare symbol (strip any `Type::` prefix) as a word.
            let bare = sym.rsplit("::").next().unwrap_or(sym);
            assert!(
                src.contains(sym) || src.contains(bare),
                "evidence pointer {ps} does not resolve in {path} — a cited processor was \
                 renamed/removed (re-materialize evidence/cc_impl.tsv)"
            );
        }
        assert!(
            rows >= 40,
            "expected persist's ~43 evidence rows, got {rows}"
        );
    }

    /// Citations the manifest makes that name a symbol which is NOT a function
    /// (a type, trait, const, enum variant, or an inherent method spelled
    /// `Type::method`). Liveness is a property of FUNCTIONS; a cited type is
    /// checked by the compiler instead (it cannot be referenced and absent).
    /// Pinned so the classification stays deliberate — a NEW non-function
    /// citation must be added here consciously, not silently skipped.
    const NON_FUNCTION_CITATIONS: &[&str] = &[
        "ConformityVariant",
        "DetectionEvent",
        "Engine::promote_attestation_with_strips",
        "ATTESTATION_LADDER_MECHANISMS",
        "BlobStorage",
        "RestrictionOp::StripField",
        "EnvelopeCore",
        "HardCaseEvent",
        "BlobBackedSchemaResolver",
        "Attestation",
        "LocalAttestationInput",
    ];

    /// Cited processors that are **exported API surface**: `pub` functions or
    /// `FederationDirectory` trait methods that downstream (server / edge /
    /// agent / the PyO3 wheel) calls, so persist's own non-test call count is
    /// legitimately zero. These are NOT dead — the caller is simply in another
    /// repo — but each is pinned here so the classification is a deliberate,
    /// reviewable claim rather than a silent skip. Adding a name here asserts:
    /// *this is a published surface with a real external caller.*
    ///
    /// (Contrast the #543 case: `check_capacity_not_self_attested` was NOT
    /// exported API — it was an internal guard nothing called, which is exactly
    /// the dead-citation shape this gate exists to reject.)
    /// Citations the vendored manifest still makes to symbols persist has
    /// DELETED — a correction owed at the next re-vendor (tracked #520), not a
    /// live hole. The manifest is the vendored Registry-of-Record and is not
    /// hand-edited (#519 governance), so the stale citation is recorded here
    /// with its reason and the gate treats it as known-and-tracked rather than
    /// failing the build on a data-file lag persist cannot unilaterally fix.
    ///
    /// Each entry must name a symbol that genuinely no longer exists — the gate
    /// asserts that too, so an entry cannot be used to hide a live dead
    /// citation (if the symbol is still present, it must satisfy the liveness
    /// bar like everything else).
    const DELETED_PENDING_REVENDOR: &[(&str, &str)] = &[(
        "duty_holders_from_signed_subjects",
        "deleted in v22.0.0 (#543): unioned caller-declared subject_key_ids into the authority \
         set — the #517 vulnerability. The manifest labels it \"the drift site\"; the row \
         graduates at the #520 re-vendor.",
    )];

    const EXPORTED_API_CITATIONS: &[&str] = &[
        // `FederationDirectory` trait method — the consent-SLA watcher a host
        // schedules (#146); persist ships it, the operator drives it.
        "run_consent_sla_watch",
        // `pub fn` — the namespace projection predicate consumed by the
        // conformance/render side (#519 manifest surface).
        "projection_for",
        // `pub fn` — the pinned extraction-manifest digest served by
        // CIRISServer's `/v1/health` (the contract's cross-repo pin).
        "extraction_manifest_sha256",
    ];

    /// v22.0.0 (CIRISPersist#543 finding 2b) — **THE EVIDENCE-REGISTRY
    /// SOUNDNESS GATE**: every `path#symbol` the manifest cites as a processor,
    /// where `path` is a repo-local file and `symbol` names a function, MUST
    /// resolve to a function with **at least one non-test caller**.
    ///
    /// #519's premise is that a mechanically-cited processor can be referenced
    /// from the constitution via the evidence registry — i.e. that a citation
    /// corresponds to code that RUNS. #543 found that premise violated:
    /// `check_capacity_not_self_attested` was cited as a live processor
    /// ("confirms scope-away") while having ZERO callers, so the manifest
    /// asserted an enforcement that did not exist and the underlying hole
    /// (capacity self-inflation) stayed open behind a citation that looked
    /// discharged. A dead citation is worse than a missing one: a missing
    /// processor is visible to the completeness gate, whereas a dead one reads
    /// as covered.
    ///
    /// The bar is deliberately "non-test caller", not merely "compiles":
    /// a function only ever called from tests enforces nothing on the live
    /// write path, which is exactly the failure mode here.
    ///
    /// Cross-repo citations (`src/…` paths belonging to verify / server / edge)
    /// are skipped — they resolve at THEIR build, and `evidence_cc_impl_pointers_resolve`
    /// already covers persist's own evidence rows for existence.
    #[test]
    fn every_cited_processor_has_a_non_test_caller() {
        use std::collections::BTreeSet;

        /// Brace-matched line ranges of `#[cfg(test)]` / `#[cfg(any(test…))]`
        /// modules. A line-number cutoff is NOT sufficient: several modules
        /// (e.g. `admission.rs`) carry test regions in the MIDDLE of the file,
        /// so everything after the first one would be wrongly treated as test.
        fn test_regions(lines: &[&str]) -> Vec<(usize, usize)> {
            let mut regions = Vec::new();
            let mut i = 0usize;
            while i < lines.len() {
                let s = lines[i].trim_start();
                if s.starts_with("#[cfg(test)]") || s.starts_with("#[cfg(any(test") {
                    let mut j = i;
                    while j < lines.len() && !lines[j].contains('{') {
                        j += 1;
                    }
                    if j < lines.len() {
                        let mut depth = 0i32;
                        let mut k = j;
                        while k < lines.len() {
                            depth += lines[k].matches('{').count() as i32;
                            depth -= lines[k].matches('}').count() as i32;
                            if depth <= 0 {
                                break;
                            }
                            k += 1;
                        }
                        regions.push((i + 1, k + 1));
                        i = k;
                    }
                }
                i += 1;
            }
            regions
        }

        // Collect repo-local `path#symbol` citations from the whole matrix
        // (`processor` + every `processors_all` entry), skipping design notes.
        let mut cites: BTreeSet<(String, String)> = BTreeSet::new();
        for row in field_processor_matrix() {
            let mut all: Vec<&str> = vec![row.processor.as_str()];
            all.extend(row.processors_all.iter().map(String::as_str));
            for v in all {
                let v = v.trim();
                if v.is_empty()
                    || v == "UNASSIGNED"
                    || v.starts_with("proposed:")
                    || v.contains("NOT LANDED")
                {
                    continue;
                }
                let v = v.strip_prefix("CIRISPersist/").unwrap_or(v);
                let Some((path, sym)) = v.split_once('#') else {
                    continue;
                };
                let path = path.trim();
                let full = format!("{}/{}", env!("CARGO_MANIFEST_DIR"), path);
                if !std::path::Path::new(&full).is_file() {
                    continue; // cross-repo citation — resolves at their build
                }
                let sym: String = sym
                    .trim()
                    .chars()
                    .take_while(|c| c.is_ascii_alphanumeric() || *c == '_' || *c == ':')
                    .collect();
                if !sym.is_empty() {
                    cites.insert((path.to_string(), sym));
                }
            }
        }
        assert!(
            cites.len() > 20,
            "citation harvest collapsed ({} found) — the gate would pass vacuously",
            cites.len()
        );

        // Index every persist source file once.
        let mut sources: Vec<(String, String)> = Vec::new();
        fn walk(dir: &std::path::Path, out: &mut Vec<(String, String)>) {
            let Ok(rd) = std::fs::read_dir(dir) else {
                return;
            };
            for e in rd.flatten() {
                let p = e.path();
                if p.is_dir() {
                    walk(&p, out);
                } else if p.extension().is_some_and(|x| x == "rs") {
                    if let Ok(t) = std::fs::read_to_string(&p) {
                        out.push((p.display().to_string(), t));
                    }
                }
            }
        }
        walk(
            &std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src"),
            &mut sources,
        );

        let non_fn: BTreeSet<&str> = NON_FUNCTION_CITATIONS.iter().copied().collect();
        let exported: BTreeSet<&str> = EXPORTED_API_CITATIONS.iter().copied().collect();
        let mut dead: Vec<String> = Vec::new();
        let mut test_only: Vec<String> = Vec::new();

        for (path, sym) in &cites {
            let bare = sym.rsplit("::").next().unwrap_or(sym);
            if non_fn.contains(sym.as_str()) || non_fn.contains(bare) {
                continue;
            }
            let def = format!("fn {bare}");
            let defined = sources
                .iter()
                .any(|(_, t)| t.lines().any(|l| l.contains(&def)));
            // A deliberately-deleted symbol awaiting the next re-vendor: allowed
            // ONLY while it is genuinely absent. If it comes back it must meet
            // the liveness bar like anything else (so this list can never hide a
            // live dead citation).
            if let Some((_, why)) = DELETED_PENDING_REVENDOR.iter().find(|(s, _)| *s == bare) {
                assert!(
                    !defined,
                    "{bare} is listed in DELETED_PENDING_REVENDOR ({why}) but a `fn {bare}` \
                     exists again — remove the entry and let the liveness bar apply"
                );
                continue;
            }
            if !defined {
                // Not a function anywhere: either a type (should be pinned in
                // NON_FUNCTION_CITATIONS) or a stale citation.
                dead.push(format!(
                    "{path}#{sym} — names no `fn` in persist (add to NON_FUNCTION_CITATIONS if it \
                     is a type/const, else the citation is stale)"
                ));
                continue;
            }
            let call = format!("{bare}(");
            let (mut non_test, mut total) = (0usize, 0usize);
            for (f, t) in &sources {
                let lines: Vec<&str> = t.lines().collect();
                let regions = test_regions(&lines);
                for (i, l) in lines.iter().enumerate() {
                    let ln = i + 1;
                    if l.contains(&call) && !l.contains(&def) {
                        total += 1;
                        if !regions.iter().any(|(a, b)| ln >= *a && ln <= *b) {
                            non_test += 1;
                        }
                    }
                }
                let _ = f;
            }
            if non_test == 0 && !exported.contains(bare) {
                if total > 0 {
                    test_only.push(format!("{path}#{bare} (called ONLY from tests)"));
                } else {
                    dead.push(format!("{path}#{bare} (ZERO callers — dead citation)"));
                }
            }
        }

        assert!(
            dead.is_empty() && test_only.is_empty(),
            "EVIDENCE-REGISTRY UNSOUNDNESS (CIRISPersist#543): the manifest cites processors that \
             do not run on any live path. A citation that names code which never executes asserts \
             an enforcement that does not exist — the #519 premise this gate protects.\n  \
             DEAD: {dead:?}\n  TEST-ONLY: {test_only:?}\n\
             Fix by WIRING the processor at its real chokepoint (preferred — that is what #543 did \
             for check_capacity_not_self_attested), or by correcting the manifest citation."
        );
    }

    /// Drift gate: the compiled-in manifest is the exact cut the consts pin,
    /// and it is coherently seeded from the registry cut persist vendors.
    #[test]
    fn vendored_supersets_manifest_is_pinned() {
        assert_eq!(
            manifest_version(),
            VENDORED_MANIFEST_VERSION,
            "manifest_version drift — re-vendor deliberately + bump the const"
        );
        assert_eq!(
            constitution_rev(),
            VENDORED_CONSTITUTION_REV,
            "constitution_rev drift"
        );
        assert!(
            seed_registry_source().contains(VENDORED_SEED_REGISTRY_SHA256),
            "supersets seed registry sha does not name the vendored namespace_registry cut: {}",
            seed_registry_source()
        );
        // Cross-manifest coherence: the supersets walk is seeded from EXACTLY
        // the namespace registry cut persist vendors.
        assert_eq!(
            VENDORED_SEED_REGISTRY_SHA256,
            super::super::registry::VENDORED_SOURCE_SHA256,
            "supersets seed sha != registry source sha — the two vendored manifests \
             disagree on the CC cut"
        );
    }

    /// #519 item 2b — no placement field is silently unprocessed BEYOND the
    /// declared, tracked gap set. A NEW `UNASSIGNED` field (a regression) fails
    /// the build; the known `deletion_window` gap (deferred to the item-2 hoist)
    /// stays visible, not silent.
    #[test]
    fn unassigned_fields_match_the_known_tracked_gap_set() {
        let mut unassigned: Vec<&str> = field_processor_matrix()
            .iter()
            .filter(|r| r.is_unassigned())
            .map(|r| r.field.as_str())
            .collect();
        unassigned.sort_unstable();
        unassigned.dedup();
        let mut known = KNOWN_UNASSIGNED_FIELDS.to_vec();
        known.sort_unstable();
        assert_eq!(
            unassigned, known,
            "the manifest's UNASSIGNED placement fields changed. A NEW unassigned field is a \
             #519 item-2b release blocker — assign a processor or record it deliberately in \
             KNOWN_UNASSIGNED_FIELDS with a tracking issue."
        );
    }

    /// The completeness universe is non-empty and includes `cohort_scope` — the
    /// placement field the #315 / #519 promotion fix carries. Guards the
    /// promotion-primitive completeness gate against an empty/incoherent matrix.
    #[test]
    fn persist_owns_cohort_scope_placement() {
        let fields = persist_placement_fields();
        assert!(
            !fields.is_empty(),
            "persist owns at least one placement field"
        );
        assert!(
            fields.contains(&"cohort_scope"),
            "cohort_scope must be a persist-owned placement field (the promotion carries it): {fields:?}"
        );
    }

    /// #519 item 2a-iii — the shipped `SignedTouchClaim` +
    /// `crate::federation::admission::verify_touch_claim_admission` +
    /// `crate::federation::types::SignerForm` implementation must not drift
    /// from the manifest's `freshness_floor` governance record: same
    /// canonical field name, same merge rule, and the same closed set of
    /// signer forms (`SignerForm`'s three variants, in the manifest's own
    /// declared order).
    #[test]
    fn freshness_floor_implementation_matches_manifest() {
        let spec = freshness_floor_spec();
        assert_eq!(spec.canonical_field, "fresh_as_of");
        assert_eq!(spec.merge_rule, "monotonic_max");
        assert_eq!(
            spec.signer_forms,
            vec!["self_touch", "witness_touch", "n_of_m_cosigned"],
            "SignerForm's variants must track the manifest's declared signer_forms: {:?}",
            spec.signer_forms
        );
    }

    // ── v21.13.0 (CIRISPersist#532) — the axis-fusion gate suite ──────────

    /// The KNOWN, tracked axis fusions (`asymmetry_kind = logical_defect`) —
    /// fields where a processor genuinely answers two CI questions and one
    /// answer is wrong. Pinned like [`KNOWN_UNASSIGNED_FIELDS`]: a NEW
    /// `logical_defect` (a newly-surfaced fusion, e.g. the #532 tenth) fails
    /// the build until recorded here with its tracking issue; a RESOLVED one
    /// (split into two axis-honest symbols) must be removed. This is the
    /// regression tripwire the whole class was missing.
    const KNOWN_AXIS_FUSIONS: &[&str] = &[
        "attestation_prefixes",
        "audience",
        "charter_witness_ref",
        "cohort_scope",
        "config_scope",
        "delegation_purpose",
        "manifest.content_hash",
        "registry_row",
        "restrictions[].op=recipient_capability",
        "tombstone_null_value",
        "wa_adjudication_ref",
        "weight",
        "witness_relation",
    ];

    /// Gate: every axis key the manifest uses is in the closed [`CI_AXES`]
    /// rubric set. A new axis token in a re-vendor must be added to the const
    /// deliberately — the vocabulary cannot silently widen.
    #[test]
    fn ci_axis_vocabulary_is_closed() {
        let closed: BTreeSet<&str> = CI_AXES.iter().copied().collect();
        let fams = families()
            .as_object()
            .expect("families is an object")
            .clone();
        for (prefix, fam) in &fams {
            let Some(axes) = fam
                .get("round2")
                .and_then(|r| r.get("ci_axes"))
                .and_then(|a| a.as_object())
            else {
                continue;
            };
            for axis_key in axes.keys() {
                assert!(
                    closed.contains(axis_key.as_str()),
                    "family {prefix} declares ci_axes key {axis_key:?} outside the closed CI \
                     rubric set {CI_AXES:?} — widen CI_AXES deliberately or fix the manifest"
                );
            }
        }
    }

    /// Gate: every fusion classification (manifest `asymmetry_kind` AND every
    /// persist-authored entry) is in the closed [`ASYMMETRY_KINDS`] set.
    #[test]
    fn asymmetry_kind_vocabulary_is_closed() {
        let closed: BTreeSet<&str> = ASYMMETRY_KINDS.iter().copied().collect();
        for r in field_processor_matrix() {
            let k = r.asymmetry_kind.trim();
            if k.is_empty() {
                continue;
            }
            assert!(
                closed.contains(k),
                "field {} has asymmetry_kind {k:?} outside {ASYMMETRY_KINDS:?}",
                r.field
            );
        }
        for (f, k, _) in PERSIST_AUTHORED_AXIS_CLASSIFICATIONS {
            assert!(
                closed.contains(k),
                "persist-authored classification for {f} uses kind {k:?} outside {ASYMMETRY_KINDS:?}"
            );
        }
    }

    /// The derivation catches the ARC's confirmed fusions — a guard that
    /// `ci_axes_for_field` actually joins (an empty/broken join would make the
    /// whole gate vacuously pass). `subject_key_ids` (#528: data-subject naming
    /// vs revocation authority) and `cohort_scope` (#527: read vs write default
    /// / recipient_see vs receive) MUST each derive more than one axis.
    #[test]
    fn ci_axes_derivation_catches_the_known_fusions() {
        for f in ["subject_key_ids", "cohort_scope"] {
            let axes = ci_axes_for_field(f);
            assert!(
                axes.len() > 1,
                "{f} must derive >1 CI axis (the fusion signal); got {axes:?} — the \
                 families.ci_axes join is broken"
            );
        }
    }

    /// THE fusion gate (CIRISPersist#532 gate 1): every placement field that
    /// serves MORE THAN ONE CI axis must carry a fusion classification — the
    /// manifest's own `asymmetry_kind`, or persist's proposed classification.
    /// An UNCLASSIFIED cross-axis field is exactly the "one name, two axes"
    /// defect the arc kept finding by hand; here it is a build failure. This
    /// converts axis fusion from latent-in-code to visible-in-artifact.
    #[test]
    fn every_multi_axis_field_is_classified() {
        let mut unclassified: Vec<String> = Vec::new();
        for r in field_processor_matrix() {
            let axes = ci_axes_for_field(&r.field);
            if axes.len() > 1 && fusion_classification(&r.field).is_none() {
                unclassified.push(format!("{} {:?}", r.field, axes));
            }
        }
        assert!(
            unclassified.is_empty(),
            "UNCLASSIFIED axis-fusion field(s) — a field serving >1 CI axis with no \
             asymmetry_kind (manifest) nor PERSIST_AUTHORED_AXIS_CLASSIFICATIONS entry. \
             Classify it (logical_defect + tracking issue, axiomatic_intent, or n/a) so the \
             fusion is visible: {unclassified:?}"
        );
    }

    /// The persist-authored classifications cover EXACTLY the manifest's
    /// multi-axis gaps — no more, no less. Prevents both drift directions: a
    /// stale authored entry for a field the manifest later classifies (or that
    /// stops being multi-axis), and a real gap left uncovered. When the CC
    /// ratification folds these into the next walk, the manifest's
    /// `asymmetry_kind` fills and the matching authored entries must be removed
    /// (this test names them).
    #[test]
    fn persist_authored_classifications_cover_exactly_the_manifest_gaps() {
        // The gaps: multi-axis matrix fields the manifest left unclassified.
        let mut manifest_gaps: BTreeSet<&str> = BTreeSet::new();
        for r in field_processor_matrix() {
            if r.asymmetry_kind.trim().is_empty() && ci_axes_for_field(&r.field).len() > 1 {
                manifest_gaps.insert(r.field.as_str());
            }
        }
        let authored: BTreeSet<&str> = PERSIST_AUTHORED_AXIS_CLASSIFICATIONS
            .iter()
            .map(|(f, _, _)| *f)
            .collect();
        assert_eq!(
            authored, manifest_gaps,
            "PERSIST_AUTHORED_AXIS_CLASSIFICATIONS must cover exactly the manifest's multi-axis \
             gaps. Left = authored, right = actual gaps. A field on the right-not-left is an \
             unclassified fusion; a field on the left-not-right is a stale authored entry (the \
             manifest now classifies it, or it is no longer multi-axis) — remove it."
        );
        // Every authored entry names a real, non-empty rationale (the gate
        // demands a reviewed exemption WITH a reason).
        for (f, _, note) in PERSIST_AUTHORED_AXIS_CLASSIFICATIONS {
            assert!(
                note.len() > 20,
                "persist-authored classification for {f} needs a substantive rationale"
            );
        }
    }

    /// v23.0.0 (CIRISPersist#551 item 2) — the `trust:*` manifest rows are
    /// bound to the LIVE constants the walk predicates read.
    ///
    /// A registry row that names a dimension no predicate uses (or misses one
    /// a predicate does) is the dead-citation shape
    /// [`every_cited_processor_has_a_non_test_caller`] exists to reject, one
    /// level up: it would assert a naming discipline the code does not
    /// actually run. Binding the table to the constants means the row set and
    /// the predicate set cannot disagree — the same one-list rule #541 turned
    /// into house policy.
    #[test]
    fn persist_authored_trust_dimensions_match_the_constants() {
        use crate::federation::trust_root::{
            TRUST_ACCEPTS_DIMENSION, TRUST_CHARTER_DIMENSION, TRUST_CONFERS_DIMENSION,
        };
        let live: BTreeSet<&str> = [
            TRUST_CHARTER_DIMENSION,
            TRUST_CONFERS_DIMENSION,
            TRUST_ACCEPTS_DIMENSION,
        ]
        .into_iter()
        .collect();
        let authored: BTreeSet<&str> = PERSIST_AUTHORED_TRUST_JOB_DIMENSIONS
            .iter()
            .map(|(d, _, _, _)| *d)
            .collect();
        assert_eq!(
            authored, live,
            "PERSIST_AUTHORED_TRUST_JOB_DIMENSIONS must name exactly the trust:* job dimensions \
             the trust_root predicates read. Left = manifest rows, right = live constants."
        );
        for (dim, direction, read_by, rationale) in PERSIST_AUTHORED_TRUST_JOB_DIMENSIONS {
            assert!(
                dim.starts_with("trust:") && dim.ends_with(":v1"),
                "{dim} must be a versioned trust:* token (the #102 four-test gate)"
            );
            assert!(
                direction.contains('→'),
                "{dim} must record the direction it asserts, got {direction:?}"
            );
            assert!(
                read_by.starts_with("federation::trust_root::"),
                "{dim} must cite the predicate that reads it, got {read_by:?}"
            );
            assert!(
                rationale.len() > 20,
                "{dim} needs a substantive rationale (the reviewed-with-a-reason bar)"
            );
        }
        // The family is NOT yet CC-registered — that is the whole reason these
        // rows live in persist. If this flips, the registration landed and the
        // table graduates into the re-vendor.
        assert!(
            super::super::registry::lookup(TRUST_CHARTER_DIMENSION).is_none(),
            "trust:* is now in the vendored CC registry — fold \
             PERSIST_AUTHORED_TRUST_JOB_DIMENSIONS into the re-vendor and delete it here"
        );
    }

    /// The tracked-fusion registry is pinned: the set of `logical_defect`
    /// fields (manifest + any persist-authored) equals [`KNOWN_AXIS_FUSIONS`].
    /// A NEW `logical_defect` (a fusion the manifest or persist newly marks a
    /// real bug — the #532 tenth) fails until pinned with its tracking issue; a
    /// RESOLVED one must be removed. Same discipline as
    /// [`unassigned_fields_match_the_known_tracked_gap_set`].
    #[test]
    fn known_axis_fusions_are_pinned() {
        let mut actual: BTreeSet<&str> = field_processor_matrix()
            .iter()
            .filter(|r| r.asymmetry_kind.trim() == "logical_defect")
            .map(|r| r.field.as_str())
            .collect();
        for (f, k, _) in PERSIST_AUTHORED_AXIS_CLASSIFICATIONS {
            if *k == "logical_defect" {
                actual.insert(f);
            }
        }
        let pinned: BTreeSet<&str> = KNOWN_AXIS_FUSIONS.iter().copied().collect();
        assert_eq!(
            actual, pinned,
            "the tracked axis-fusion set changed. A NEW logical_defect is the #532 defect class \
             re-appearing — pin it in KNOWN_AXIS_FUSIONS with a tracking issue, or if it was \
             split into axis-honest symbols, remove it. Left = actual, right = pinned."
        );
    }

    /// CIRISPersist#532 (the dedup fix / #416 signal): the multi-processor
    /// signal is SURFACED, not collapsed. The pre-#532 accessor reported `0`
    /// fields with more than one distinct processor (it deduped to the single
    /// primary `processor`); [`FieldProcessorRow::distinct_real_processors`]
    /// must surface the real fan-out. `dimension` / `cohort_scope` /
    /// `subject_key_ids` each have many distinct live processors — the exact
    /// fields where a `list_attestations`-shape advertise-vs-holdings overload
    /// (#416) would hide.
    #[test]
    fn multi_processor_fields_are_surfaced_not_deduped() {
        let multi = field_processor_matrix()
            .iter()
            .filter(|r| r.distinct_real_processors().len() > 1)
            .count();
        assert!(
            multi > 0,
            "distinct_real_processors collapsed to <=1 everywhere — the dedup bug that hid #416 \
             is back (the manifest has fields with many processors_all entries)"
        );
        for f in ["dimension", "cohort_scope", "subject_key_ids"] {
            let row = field_processor_matrix()
                .iter()
                .find(|r| r.field == f)
                .unwrap_or_else(|| panic!("{f} is a matrix field"));
            assert!(
                row.distinct_real_processors().len() > 1,
                "{f} must surface >1 distinct live processor (the multi-processor / #416 \
                 signal); got {:?}",
                row.distinct_real_processors()
            );
        }
    }

    /// The `typing` value space is closed (`envelope_core_typed` |
    /// `untyped_extra`), and — since the matrix carries one row per field —
    /// each field states exactly one typing. CIRISPersist#532 gate 2 (one
    /// field, one value space): the CROSS-REPO half (a field whose `typing`
    /// disagrees across repos — #2 goal_id, #3 reconsideration) is a conformance
    /// check the downstream renders run; persist enforces its own closed
    /// value space here.
    #[test]
    fn typing_value_space_is_closed() {
        // The three-value typing space: a typed EnvelopeCore field, a typed
        // AttestationBase column, or the signature-locked `extra` map.
        let closed: BTreeSet<&str> = [
            "envelope_core_typed",
            "attestation_base_typed",
            "untyped_extra",
        ]
        .into_iter()
        .collect();
        for r in field_processor_matrix() {
            let t = r.typing.trim();
            if t.is_empty() {
                continue;
            }
            assert!(
                closed.contains(t),
                "field {} has typing {t:?} outside the closed value space {closed:?}",
                r.field
            );
        }
    }

    /// CIRISPersist#532 gate 3 (read/write defaults are distinct axes): the
    /// manifest's `duality_audit` records `read<->write` as a closed duality —
    /// the recognition that a default governing the read path and one governing
    /// the write path are different axes, and one constant serving both is the
    /// #527 `cohort_scope` fail-open. This asserts the recognition is present
    /// (a re-vendor that drops it regresses the modeling).
    #[test]
    fn read_write_default_duality_is_recorded() {
        let root: serde_json::Value =
            serde_json::from_str(SUPERSETS_JSON).expect("valid manifest json");
        let closed = root
            .get("duality_audit")
            .and_then(|d| d.get("known_closed_not_reported"))
            .and_then(|v| v.as_array())
            .expect("duality_audit.known_closed_not_reported is an array");
        assert!(
            closed
                .iter()
                .any(|v| v.as_str() == Some("read<->write")),
            "duality_audit must record read<->write as a closed duality (CIRISPersist#532 gate 3 / \
             #527 cohort_scope read-vs-write default): {closed:?}"
        );
    }
}
