-- V079 — NEUTRALIZED (CIRISPersist#222).
--
-- This migration ORIGINALLY created `cirislens.trace_events_factor_rollup_1h`
-- as a TimescaleDB *continuous aggregate* (CREATE MATERIALIZED VIEW … WITH
-- (timescaledb.continuous) opened through a dblink autonomous connection,
-- plus add_continuous_aggregate_policy). The operator deployment is plain
-- PostgreSQL / SQLite — TimescaleDB is NOT available and MUST NOT be a
-- dependency. The continuous-aggregate body has been purged so NO
-- timescaledb / dblink / time_bucket DDL remains anywhere in the embedded
-- migration set (modulo V001's already-shipped, runtime-neutralized
-- hypertable guard, which V082 converts away).
--
-- The replacement is a plain, backend-agnostic rollup TABLE of the same
-- name created in V081 (both dialects), maintained by an idempotent
-- upsert (`refresh_factor_rollup`) and summed on read — sub-second on
-- plain PG AND sqlite, no TimescaleDB.
--
-- This file is left in place as an intentional no-op rather than deleted
-- so refinery's version sequence + already-applied schema_history rows
-- stay coherent. Backends run the migration set with
-- `set_abort_divergent(false)` so a database that applied the ORIGINAL
-- V079 (a timescale CI image) does not abort on the checksum change — the
-- old V079 already ran there, will not re-run, and V081 tears down the
-- CAGG it left behind.
--
-- Deliberately empty (a bare comment is a valid no-op migration body).
SELECT 1;
