#!/usr/bin/env python3
"""Generate `src/federation/directory_double.rs` — the FederationDirectory
fault-injecting double (CIRISPersist#603).

WHY GENERATED. The trait has 162 required methods and grows most releases. A
hand-written double is 162 chances to typo a delegation, and it rots the moment
someone adds a method. This parses the trait and emits every delegation, so the
double tracks the trait by construction.

WHY NOT A MACRO. A declarative macro cannot enumerate a trait's methods, and a
proc-macro crate is a heavier dependency than a script that emits committed code
a reviewer can read. The generated file IS committed: `cargo` never runs this,
so there is no build-time codegen and no surprise at compile time.

The compiler is still the backstop. If the trait gains a method and nobody
regenerates, the double fails to COMPILE — loud, and at the right moment.

Run:  python3 scripts/gen_directory_double.py
Check: python3 scripts/gen_directory_double.py --check   (CI: fails if stale)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "federation" / "mod.rs"
OUT = ROOT / "src" / "federation" / "directory_double.rs"


def trait_body(text: str) -> str:
    i = text.find("pub trait FederationDirectory")
    if i < 0:
        sys.exit("could not find `pub trait FederationDirectory`")
    j = text.index("{", i)
    depth, k = 0, j
    while True:
        if text[k] == "{":
            depth += 1
        elif text[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    return text[j + 1 : k]


def split_args(arg_str: str) -> list[str]:
    """Split a Rust argument list on top-level commas (generics/tuples nest)."""
    out, depth, cur = [], 0, ""
    for ch in arg_str:
        if ch in "<([":
            depth += 1
        elif ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def parse(body: str):
    """Yield (name, args_src, ret) for every REQUIRED (`;`-terminated) method."""
    methods = []
    # Only depth-0 items: nested impls/fns inside default bodies must not leak.
    depth, buf = 0, ""
    for line in body.split("\n"):
        if depth == 0:
            buf += line + "\n"
            if re.search(r"\bfn\s+[a-z0-9_]+", buf) and ";" in line and "{" not in buf:
                one = " ".join(buf.split())
                m = re.match(
                    r".*?\bfn\s+([a-z0-9_]+)\s*\((.*?)\)\s*(?:->\s*(.+?))?\s*;$", one
                )
                if m:
                    methods.append((m.group(1), m.group(2), (m.group(3) or "()").strip()))
                buf = ""
            elif "{" in line:
                buf = ""
        depth += line.count("{") - line.count("}")
        if depth < 0:
            depth = 0
    return methods


def render(methods) -> str:
    L: list[str] = []
    A = L.append
    A('//! **A composable `FederationDirectory` double (CIRISPersist#603/#604).**')
    A('//!')
    A('//! GENERATED by `scripts/gen_directory_double.py`. Do not edit by hand —')
    A('//! edit the generator. `scripts/gen_directory_double.py --check` fails if this')
    A('//! file is stale.')
    A('//!')
    A('//! # The arm nobody could reach')
    A('//!')
    A('//! `resolve_mesh_config` folds per-root reads and carries `unreadable_roots`,')
    A('//! so *"this backend cannot answer for root R"* and *"root R said nothing"* stay')
    A('//! distinct. **No test in this repo could reach that arm**: all three shipped')
    A('//! backends implement every method, so none can return `Error::Unsupported`.')
    A('//! The only party exercising it was CIRISServer, through their own directory')
    A('//! impl — which is how the defect was found in the first place (#603).')
    A('//!')
    A('//! #604 recorded the pattern across five workstreams in one week:')
    A('//!')
    A('//! ```text')
    A('//! Ok(value)  -> a real answer')
    A('//! Ok(empty)  -> a real answer that happens to be empty')
    A('//! Err(_)     -> WE COULD NOT ASK')
    A('//! ```')
    A('//!')
    A('//! Collapsing that third arm is how a zero becomes evidence it has not earned.')
    A('//! The Constitution\'s own discipline: **a zero is not evidence unless the')
    A('//! instrument can fail.** This is the instrument that can fail.')
    A('//!')
    A('//! # Shape')
    A('//!')
    A('//! It WRAPS a real directory rather than stubbing 162 methods, so every')
    A('//! un-faulted call keeps real behaviour and a fixture only declares the')
    A('//! divergence it cares about.')
    A('//!')
    A('//! ```ignore')
    A('//! let dbl = FaultInjectingDirectory::new(backend)')
    A('//!     .unsupported("list_attestations_for");')
    A('//! // every other method behaves exactly as `backend` does')
    A('//! ```')
    A('//!')
    A('//! Test-only: `#[cfg(any(test, feature = "test-anchor"))]`, and `pub` because')
    A('//! CIRISServer/Edge/Agent need it (#664 was the same wall one module over).')
    A("")
    A("// A glob import on purpose: this file delegates EVERY trait signature, so it")
    A("// needs the trait\'s whole type scope. Naming them individually would be a")
    A("// second list to keep in sync with the first — the exact failure this")
    A("// generator exists to remove.")
    A("#[allow(unused_imports)]")
    A("use super::*;")
    A("use std::collections::BTreeSet;")
    A("use std::sync::Arc;")
    A("")
    A("/// A `FederationDirectory` that delegates to `inner`, except where a method")
    A("/// has been declared faulted — there it returns [`Error::Unsupported`].")
    A("///")
    A("/// Cloneable and `Send + Sync`, so it drops into any fixture that takes a")
    A("/// directory. The fault set is by METHOD NAME, matching the `method` field")
    A("/// `Error::Unsupported` already carries, so a refusal names the same thing the")
    A("/// fixture declared.")
    A("#[derive(Clone)]")
    A("pub struct FaultInjectingDirectory {")
    A("    inner: Arc<dyn FederationDirectory>,")
    A("    unsupported: BTreeSet<&'static str>,")
    A("}")
    A("")
    A("impl std::fmt::Debug for FaultInjectingDirectory {")
    A("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
    A('        f.debug_struct("FaultInjectingDirectory")')
    A('            .field("unsupported", &self.unsupported)')
    A("            .finish_non_exhaustive()")
    A("    }")
    A("}")
    A("")
    A("impl FaultInjectingDirectory {")
    A("    /// Wrap a real directory. With no faults declared it is behaviourally")
    A("    /// identical to `inner` — a fixture opts INTO each divergence.")
    A("    #[must_use]")
    A("    pub fn new(inner: Arc<dyn FederationDirectory>) -> Self {")
    A("        Self { inner, unsupported: BTreeSet::new() }")
    A("    }")
    A("")
    A("    /// Declare that `method` answers `Error::Unsupported { method }`.")
    A("    ///")
    A("    /// The name is NOT validated against the trait: an unknown name is inert")
    A("    /// rather than an error, because a fixture written against a newer persist")
    A("    /// should degrade to *\"that fault did not fire\"* and fail on its own")
    A("    /// assertion, not panic inside the double. Use [`Self::faults`] to assert")
    A("    /// what was actually declared.")
    A("    #[must_use]")
    A("    pub fn unsupported(mut self, method: &'static str) -> Self {")
    A("        self.unsupported.insert(method);")
    A("        self")
    A("    }")
    A("")
    A("    /// The declared fault set — so a fixture can assert its own setup.")
    A("    #[must_use]")
    A("    pub fn faults(&self) -> &BTreeSet<&'static str> {")
    A("        &self.unsupported")
    A("    }")
    A("")
    A("    fn faulted(&self, method: &'static str) -> Option<Error> {")
    A("        self.unsupported")
    A("            .contains(method)")
    A("            .then_some(Error::Unsupported { method })")
    A("    }")
    A("}")
    A("")
    A(f"// {len(methods)} delegations, generated. Every one: fault first, then delegate.")
    A("#[async_trait::async_trait]")
    A("impl FederationDirectory for FaultInjectingDirectory {")
    for name, args_src, ret in methods:
        args = split_args(args_src)
        # drop the receiver
        params = [a for a in args if a.strip() not in ("&self", "self", "&mut self")]
        names = []
        for p in params:
            nm = p.split(":")[0].strip()
            # `str.lstrip` takes a CHARACTER SET, not a prefix — `lstrip("mut ")`
            # eats the leading `m` of `member_identity_key_id`. Strip the real
            # `mut ` token instead.
            if nm.startswith("mut "):
                nm = nm[4:].strip()
            names.append(nm)
        arglist = ", ".join(["&self"] + params)
        call = ", ".join(names)
        is_result = ret.startswith("Result<")
        A(f"    async fn {name}({arglist}) -> {ret} {{")
        if is_result:
            A(f'        if let Some(e) = self.faulted("{name}") {{')
            A("            return Err(e);")
            A("        }")
        A(f"        self.inner.{name}({call}).await")
        A("    }")
    A("}")
    return "\n".join(L) + "\n"


def rustfmt(text: str) -> str:
    """Run the emitted source through rustfmt.

    Without this, `cargo fmt --all` reformats the generated file and `--check`
    then reports STALE for a file nobody edited — the gate crying wolf at its own
    project's formatter. Generating already-formatted source makes "generated"
    and "formatted" the same string.
    """
    import subprocess

    try:
        r = subprocess.run(
            ["rustfmt", "--edition", "2021", "--emit", "stdout"],
            input=text,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        # No rustfmt (or it rejected the input): fall back to raw output rather
        # than failing. `cargo fmt --check` in CI is the real gate on formatting.
        return text
    out = r.stdout
    # rustfmt --emit stdout prefixes a `// rustfmt-...` banner line in some
    # versions; drop anything before our own module doc.
    i = out.find("//! ")
    return out[i:] if i > 0 else out


def main() -> None:
    methods = parse(trait_body(SRC.read_text()))
    if not methods:
        sys.exit("parsed zero methods — the trait shape changed; fix the generator")
    text = rustfmt(render(methods))
    if "--check" in sys.argv:
        cur = OUT.read_text() if OUT.exists() else ""
        if cur != text:
            sys.exit(
                f"STALE: {OUT.relative_to(ROOT)} does not match the trait "
                f"({len(methods)} methods). Run: python3 scripts/gen_directory_double.py"
            )
        print(f"OK directory double is current ({len(methods)} delegations)")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(methods)} delegations)")


if __name__ == "__main__":
    main()
