#!/usr/bin/env python3
"""mutants_matrix.py — scope files in, detection matrix out (CIRISPersist#1024).

`scripts/mutants.sh` drives a mutation tool; this script does the two parts
that are not shell: it resolves a scope file into the tool's own filter
arguments, and it turns the tool's raw output into ONE matrix format,
whichever tool produced it.

    mutants_matrix.py tests <scope>                     the scope's nextest filterset
    mutants_matrix.py resolve cargo-mutants <scope>     cargo-mutants args, one per line
    mutants_matrix.py resolve mutest <scope>            mutest's --filter-mutations value
    mutants_matrix.py collect cargo-mutants <mutants.out> <scope> <out-dir> [k=v ...]
    mutants_matrix.py collect mutest <json-dir> <scope> <out-dir> [k=v ...]

`collect` writes <out-dir>/matrix.json and <out-dir>/matrix.md. Trailing k=v
pairs (wall_secs, budget_secs, features, tool_version, budget_hit) are copied
into the JSON header.

The matrix (schema `ciris-persist/mutants-matrix/v1`):

    {
      "schema": ..., "tool": ..., "tool_version": ..., "scope": <path>,
      "test_filter": <filterset>, "features": ..., "wall_secs": N,
      "budget_secs": N, "complete": bool,
      "tests":   [<test name>, ...],        every witness the run executed
      "mutants": [{"id", "file", "line", "col", "description",
                   "outcome": caught|missed|timeout|unviable|not_run,
                   "killed_by": [<test name>, ...]}, ...],
      "out_of_scope": [<description>, ...],  generated by the tool, outside every
                                             scope range, dropped from the matrix
      "summary": {"mutants", "caught", "missed", "timeout", "unviable", "not_run"},
      "kills_per_test": {<test name>: N, ...},
      "tests_killing_nothing": [<test name>, ...],  ran, failed under no mutant
      "tests_never_run": [<test name>, ...]        the tool never ran it (mutest:
                                                   outside its static call graph)
    }

A mutant is `caught` when at least one witness failed under it. `killed_by`
lists every witness that failed, because the tools run with fail-fast off;
an empty `killed_by` on a `caught` mutant means it was caught by a crash or
a build failure the log does not attribute to one test.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCHEMA = "ciris-persist/mutants-matrix/v1"


# ── scope files ─────────────────────────────────────────────────────────────


def parse_scope(path: str) -> dict:
    scope = {"tests": None, "witnesses": [], "entries": []}
    for n, raw in enumerate(Path(path).read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("tests:"):
            scope["tests"] = line[len("tests:"):].strip()
            continue
        if line.startswith("witnesses:"):
            scope["witnesses"] += line[len("witnesses:"):].split()
            continue
        file, *fns = line.split()
        if not (REPO / file).is_file():
            raise SystemExit(f"{path}:{n}: no such file {file}")
        scope["entries"].append({"file": file, "fns": fns})
    if not scope["tests"]:
        raise SystemExit(f"{path}: no `tests:` line")
    if not scope["entries"]:
        raise SystemExit(f"{path}: no files")
    return scope


def _blank_literals(src: str) -> str:
    """The source with comments, strings and char literals blanked to spaces
    (newlines kept), so braces inside them cannot move a function's end."""
    out = list(src)
    i, n = 0, len(src)

    def blank(a: int, b: int) -> None:
        for k in range(a, min(b, n)):
            if out[k] != "\n":
                out[k] = " "

    while i < n:
        c = src[i]
        if src.startswith("//", i):
            j = src.find("\n", i)
            j = n if j < 0 else j
            blank(i, j)
            i = j
        elif src.startswith("/*", i):
            depth, j = 1, i + 2
            while j < n and depth:
                if src.startswith("/*", j):
                    depth, j = depth + 1, j + 2
                elif src.startswith("*/", j):
                    depth, j = depth - 1, j + 2
                else:
                    j += 1
            blank(i, j)
            i = j
        elif (m := re.match(r'b?r(#*)"', src[i:i + 300])) and (i == 0 or not (src[i - 1].isalnum() or src[i - 1] == "_")):
            close = '"' + m.group(1)
            j = src.find(close, i + m.end())
            j = n if j < 0 else j + len(close)
            blank(i, j)
            i = j
        elif c == '"':
            j = i + 1
            while j < n and src[j] != '"':
                j += 2 if src[j] == "\\" else 1
            blank(i, j + 1)
            i = j + 1
        elif c == "'" and (m := re.match(r"'(\\[^']{1,10}|[^\\'])'", src[i:i + 14])):
            blank(i, i + m.end())
            i += m.end()
        else:
            i += 1
    return "".join(out)


def fn_range(file: str, name: str) -> tuple[int, int]:
    """1-based inclusive line range of the one `fn <name>` body in `file`."""
    src = _blank_literals((REPO / file).read_text())
    hits = []
    for m in re.finditer(rf"\bfn\s+{re.escape(name)}\s*[<(]", src):
        # The body opens at the first `{` at paren/bracket depth 0; a `;`
        # first means a bodiless trait declaration.
        depth, j = 0, m.end() - 1
        while j < len(src):
            ch = src[j]
            if ch in "([":
                depth += 1
            elif ch in ")]":
                depth -= 1
            elif depth == 0 and ch == ";":
                j = -1
                break
            elif depth == 0 and ch == "{":
                break
            j += 1
        if j < 0:
            continue
        braces, k = 0, j
        while k < len(src):
            if src[k] == "{":
                braces += 1
            elif src[k] == "}":
                braces -= 1
                if braces == 0:
                    break
            k += 1
        start = src.count("\n", 0, m.start()) + 1
        hits.append((start, src.count("\n", 0, k) + 1))
    if len(hits) != 1:
        lines = ", ".join(str(h[0]) for h in hits) or "none"
        raise SystemExit(f"{file}: `fn {name}` must have exactly one body; found {len(hits)} (lines {lines})")
    return hits[0]


def scope_ranges(scope: dict) -> list[tuple[str, int, int]]:
    """(file, first line, last line); a whole file is (file, 1, huge)."""
    out = []
    for e in scope["entries"]:
        if not e["fns"]:
            out.append((e["file"], 1, 10**9))
        for fn in e["fns"]:
            out.append((e["file"], *fn_range(e["file"], fn)))
    return out


def in_scope(ranges, file: str, line: int) -> bool:
    return any(f == file and a <= line <= b for f, a, b in ranges)


def resolve(tool: str, scope_path: str) -> None:
    scope = parse_scope(scope_path)
    ranges = scope_ranges(scope)
    if tool == "cargo-mutants":
        files = sorted({f for f, _, _ in ranges})
        for f in files:
            print("-f")
            print(f)
        # Mutant names start `path:line:col:`; a range becomes an alternation
        # of its line numbers. cargo-mutants 27.1 does not apply -F to its
        # struct-field deletions, so `collect` re-checks every mutant.
        alts = []
        for f, a, b in ranges:
            if b == 10**9:
                alts.append(rf"^{re.escape(f)}:")
            else:
                alts.append(rf"^{re.escape(f)}:({'|'.join(str(x) for x in range(a, b + 1))}):")
        print("-F")
        print("|".join(alts))
    elif tool == "mutest":
        parts = []
        for f, a, b in ranges:
            parts.append(f"file:{f}" if b == 10**9 else f"file:{f}:{a}..{b}")
        print(",".join(parts))
    else:
        raise SystemExit(f"unknown tool {tool!r}")


# ── collection ──────────────────────────────────────────────────────────────

#: nextest's per-test status lines: `        FAIL [   0.012s] (  3/120) ciris-persist mod::test`
#: (the `(n/m)` counter is absent on older nextest). Binary id, then test name.
NEXTEST_LINE = re.compile(
    r"^\s*(PASS|FAIL|TIMEOUT|SIGSEGV|SIGABRT|SIGKILL|SIGBUS|ABORT|LEAK-FAIL|FLAKY \d+/\d+)"
    r"\s+\[[^\]]*\]\s+(?:\(\s*\d+/\d+\)\s+)?(\S+)\s+(\S+)\s*$"
)


def _nextest_results(log: str) -> dict[str, str]:
    res = {}
    for line in log.splitlines():
        m = NEXTEST_LINE.match(line)
        if m:
            res[m.group(3)] = m.group(1)
    return res


def collect_cargo_mutants(out_dir: Path, scope: dict) -> tuple[list, list, list]:
    ranges = scope_ranges(scope)
    mo = out_dir if (out_dir / "outcomes.json").exists() else out_dir / "mutants.out"
    outcomes = json.loads((mo / "outcomes.json").read_text())
    tests: set[str] = set()
    mutants, dropped = [], []
    summary_map = {
        "CaughtMutant": "caught", "MissedMutant": "missed", "Timeout": "timeout",
        "Unviable": "unviable", "Success": "missed", "Failure": "caught",
    }
    for i, o in enumerate(outcomes.get("outcomes", [])):
        scen = o.get("scenario")
        log_path = mo / o.get("log_path", "")
        log = log_path.read_text(errors="replace") if log_path.is_file() else ""
        results = _nextest_results(log)
        if scen == "Baseline":
            # A red baseline means no mutant was tested at all; an empty
            # matrix from it would read as "nothing to report".
            if o.get("summary") != "Success":
                raise SystemExit(f"baseline did not pass ({o.get('summary')}); see {log_path}")
            tests |= set(results)
            continue
        mut = (scen or {}).get("Mutant", {})
        file = mut.get("file", "")
        span = mut.get("span", {}).get("start", {})
        line, col = span.get("line", 0), span.get("column", 0)
        desc = f"{file}:{line}:{col}: {mut.get('name') or mut.get('replacement', '')}"
        name = mut.get("name")
        if name:
            desc = name if name.startswith(file) else f"{file}:{line}:{col}: {name}"
        if not in_scope(ranges, file, line):
            dropped.append(desc)
            continue
        tests |= set(results)
        killers = sorted(t for t, st in results.items() if st != "PASS" and not st.startswith("FLAKY"))
        mutants.append({
            "id": len(mutants) + 1, "file": file, "line": line, "col": col,
            "description": desc,
            "outcome": summary_map.get(o.get("summary", ""), "not_run"),
            "killed_by": killers,
        })
    # nextest runs every filtered witness under every mutant: none is unreached.
    return sorted(tests), mutants, dropped, []


def collect_mutest(json_dir: Path, scope: dict) -> tuple[list, list, list]:
    ranges = scope_ranges(scope)
    lib = next(json_dir.rglob("evaluation.json")).parent
    muts = json.loads((lib / "mutations.json").read_text())["mutations"]
    ev = json.loads((lib / "evaluation.json").read_text())
    run = ev["mutation_runs"][0]
    names = [t["name"] for t in ev["tests"]]
    # mutest's harness runs the whole lib suite; keep the scope's witnesses.
    # Only the `test(/<regex>/)` filterset form is translated.
    m = re.fullmatch(r"test\(/(.*)/\)", scope["tests"])
    keep = {t for t in names if m is None or re.search(m.group(1), t)}
    overall = run["mutation_detection_matrix"]["overall_detections"]
    per_test = run["mutation_detection_matrix"]["test_detections"]
    code = {"D": "caught", "-": "missed", "T": "timeout", "C": "caught", ".": "not_run"}
    mutants, dropped = [], []
    for k, m in enumerate(sorted(muts, key=lambda m: m["mutation_id"])):
        span = m["origin_span"]
        file, (line, col) = span["path"], span["begin"]
        desc = f"{file}:{line}:{col}: {m['display_name']} [{m['mutation_op']}]"
        if not in_scope(ranges, file, line):
            dropped.append(desc)
            continue
        idx = m["mutation_id"] - 1
        flag = overall[idx] if idx < len(overall) else "."
        killers = sorted(names[t] for t, row in enumerate(per_test)
                         if idx < len(row) and row[idx] in "DTC" and names[t] in keep)
        mutants.append({
            "id": len(mutants) + 1, "file": file, "line": line, "col": col,
            "description": desc, "outcome": code.get(flag, "not_run"),
            "killed_by": killers,
        })
    # mutest runs a test only under mutants its static call graph says the
    # test reaches. A witness whose row is all `.` was never run: it killed
    # nothing because it was never asked, which is a tool limit, not a verdict.
    ran = {names[t] for t, row in enumerate(per_test) if any(c != "." for c in row)}
    return sorted(keep), mutants, dropped, sorted(keep - ran)


def write_matrix(tool, scope_path, scope, tests, mutants, dropped, unreached, out: Path, extra: dict) -> dict:
    out.mkdir(parents=True, exist_ok=True)
    pattern = scope["tests"]
    kills = {t: 0 for t in tests}
    for m in mutants:
        for t in m["killed_by"]:
            kills[t] = kills.get(t, 0) + 1
    summary = {"mutants": len(mutants)}
    for k in ("caught", "missed", "timeout", "unviable", "not_run"):
        summary[k] = sum(1 for m in mutants if m["outcome"] == k)
    budget_hit = extra.pop("budget_hit", "0") not in ("0", "", "false")
    matrix = {
        "schema": SCHEMA, "tool": tool, "scope": scope_path, "test_filter": pattern,
        **{k: (int(v) if k.endswith("_secs") and str(v).isdigit() else v) for k, v in extra.items()},
        "complete": not budget_hit and summary["not_run"] == 0,
        "tests": tests, "mutants": mutants, "out_of_scope": dropped,
        "summary": summary, "kills_per_test": dict(sorted(kills.items())),
        "tests_killing_nothing": sorted(t for t, n in kills.items() if n == 0 and t not in unreached),
        "tests_never_run": unreached,
    }
    (out / "matrix.json").write_text(json.dumps(matrix, indent=2) + "\n")

    md = [f"# Mutation matrix — `{scope_path}`", ""]
    md.append(f"Tool `{tool}` {matrix.get('tool_version', '')}; witnesses `{pattern}`; "
              f"features `{matrix.get('features', '')}`; wall {matrix.get('wall_secs', '?')}s "
              f"of a {matrix.get('budget_secs', '?')}s budget; "
              f"{'complete' if matrix['complete'] else 'INCOMPLETE'}.")
    md += ["", "| mutants | caught | missed | timeout | unviable | not run |",
           "|---:|---:|---:|---:|---:|---:|",
           "| {mutants} | {caught} | {missed} | {timeout} | {unviable} | {not_run} |".format(**summary), ""]
    md += ["## Mutants", "", "| # | site | outcome | killed by |", "|---:|---|---|---|"]
    for m in mutants:
        site = m["description"].replace("|", "\\|").replace("`", "'")
        short = ", ".join(t.rsplit("::", 2)[-2] + "::" + t.rsplit("::", 1)[-1] if t.count("::") >= 2 else t
                          for t in m["killed_by"]) or "—"
        md.append(f"| {m['id']} | `{site}` | {m['outcome'].upper() if m['outcome'] == 'missed' else m['outcome']} | {short} |")
    md += ["", "## Kills per witness", "", "| witness | mutants killed |", "|---|---:|"]
    for t, n in matrix["kills_per_test"].items():
        note = " (never run by the tool)" if t in unreached else (" **(none)**" if n == 0 else "")
        md.append(f"| `{t}` | {n}{note} |")
    if dropped:
        md += ["", f"## Generated outside the scope ({len(dropped)}, dropped)", ""]
        md += [f"- `{d}`" for d in dropped]
    (out / "matrix.md").write_text("\n".join(md) + "\n")
    return matrix


def main(argv: list[str]) -> int:
    if len(argv) >= 3 and argv[1] == "tests":
        print(parse_scope(argv[2])["tests"])
        return 0
    if len(argv) == 4 and argv[1] == "resolve":
        resolve(argv[2], argv[3])
        return 0
    if len(argv) >= 6 and argv[1] == "collect":
        tool, raw, scope_path, out = argv[2], Path(argv[3]), argv[4], Path(argv[5])
        extra = dict(a.split("=", 1) for a in argv[6:])
        scope = parse_scope(scope_path)
        if tool == "cargo-mutants":
            tests, mutants, dropped, unreached = collect_cargo_mutants(raw, scope)
        elif tool == "mutest":
            tests, mutants, dropped, unreached = collect_mutest(raw, scope)
        else:
            raise SystemExit(f"unknown tool {tool!r}")
        m = write_matrix(tool, scope_path, scope, tests, mutants, dropped, unreached, out, extra)
        s = m["summary"]
        print(f"matrix: {s['mutants']} mutants, {s['caught']} caught, {s['missed']} missed, "
              f"{s['timeout']} timeout, {s['unviable']} unviable, {s['not_run']} not run; "
              f"{len(m['tests'])} witnesses, {len(m['tests_killing_nothing'])} killed nothing, "
              f"{len(unreached)} never run "
              f"-> {out}/matrix.json")
        return 0
    print(__doc__, file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
